TraceMachina/nativelink

cas/store/dedup_store.rs
cas/store/tests/dedup_store_test.rs
config/backends.rs
config/examples/basic_cas.json

Also change the default values after some testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/17)

Dedup store will now bypass deduplication when size is small

---

cas/grpc_service/cas_server.rs
cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/memory_store.rs
cas/store/s3_store.rs
cas/store/store_trait.rs
cas/store/tests/memory_store_test.rs
cas/store/tests/s3_store_test.rs
cas/store/tests/verify_store_test.rs
cas/store/verify_store.rs
util/evicting_map.rs
util/tests/evicting_map_test.rs

We already have the size in each of our stores for the objects,
so we now return the size of the entry or None. This will make it
easier to implement certain features in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/19)

`.has()` now returns size on success instead of boolean

---

cas/store/BUILD
cas/store/dedup_store.rs
cas/store/memory_store.rs
util/BUILD
util/common.rs
util/evicting_map.rs
util/tests/evicting_map_test.rs

Adds ability to snapshot the eviction map and restore it. Also adds some
deref() functions that will eventually be used to delete files when needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/23)

Adds more eviction templates and functions in prep for filesystem store

---

cas/store/memory_store.rs
util/BUILD
util/evicting_map.rs
util/tests/evicting_map_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/26)

Move evicting_map to use bytes instead of Vec for future efficencies

---

cas/cas_main.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
cas/store/dedup_store.rs
cas/store/tests/dedup_store_test.rs
config/backends.rs
config/examples/filesystem_cas.json

Fixes a bug in dedup store where because .has() call would call
.get_part() internally, if the part did not exist it would return
Code::NotFound as an error. When dealing with .get_part() this is
the proper thing to do, but .has() calls are supposed to return
None when object does not exist.
Also added following minor changes:
* Better debug messages when this happens
* filesystem_cas.json now uses dedup store by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/43)

Fix bug during .has() call in dedup store

---

cas/BUILD
cas/cas_main.rs
cas/grpc_service/BUILD
cas/grpc_service/ac_server.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/grpc_service/tests/cas_server_test.rs
cas/store/BUILD
cas/store/default_store_factory.rs
cas/store/lib.rs
cas/store/ref_store.rs
cas/store/tests/ref_store_test.rs
config/backends.rs
config/examples/filesystem_cas.json

Adds new RefStore. This store is used so you can reference another
store in the json / StoreManager by name. This will allow users
to reference the same store from multiple places.
Also restructures StoreManager to allow for this new functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/44)

Add RefStore and restructure StoreManager

---

cas/store/BUILD
cas/store/default_store_factory.rs
cas/store/size_partitioning_store.rs
cas/store/tests/size_partitioning_store_test.rs
config/backends.rs
config/examples/filesystem_cas.json

This new store can be used to partition objects based on the size
listed in the digest.
In addition, the filesystem_cas.json has been changed to take
advantage of the new config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/46)

Add SizePartitioningStore

---

proto/com/github/allada/turbo_cache/remote_execution/worker_api.proto
proto/genproto/com.github.allada.turbo_cache.remote_execution.pb.rs

* ConnectWorker is no longer stream<->stream, instead has function
calls and returns a stream for server->client updates.
* Added `reserved` keyword representing each `NextId`.
* Added ConnectionResult so worker itself knows it's own ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/48)

[RE] Various changes to worker_api.proto

---

cas/grpc_service/BUILD
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/scheduler/BUILD
cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
cas/scheduler/worker.rs

Adds server side connection API server to allow the worker to
interface with the scheduler. This PR only adds the connect_worker().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/49)

[RE] Add WorkerApiService and connection functionality

---

cas/BUILD
cas/cas_main.rs
cas/grpc_service/BUILD
cas/grpc_service/capabilities_server.rs
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/BUILD
cas/scheduler/platform_property_manager.rs
cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
config/README.md
config/cas_server.rs
config/examples/basic_cas.json
config/examples/filesystem_cas.json
config/examples/s3_backend_with_local_fast_cas.json

Restructure the format of how scheduler and platform properties
are in the config spec. This will allow more intuitive sharing
of scheduler and platform properties to different services.
* `schedulers` is now a root-level map and services reference the
name of that scheduler instead of defined inline.
* Platform properties are now owned by the scheduler.
* Updated example config files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/51)

Restructure config format in prep for WorkerApiServer

---

cas/BUILD
cas/cas_main.rs
cas/grpc_service/BUILD
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
config/cas_server.rs
config/examples/basic_cas.json
config/examples/filesystem_cas.json

Adds WorkerApiServer so it can now be served over the GRPC
connections based on config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/52)

Add WorkerApiServer to services being served

---

cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs

Implements the ability for the worker to notify the server that
it is shutting down and reschedule any jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/53)

Implement going_away() support to WorkerAPIServer

---

cas/grpc_service/BUILD
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/cas_server_test.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/scheduler/BUILD
cas/scheduler/action_messages.rs
cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
cas/scheduler/worker.rs
proto/com/github/allada/turbo_cache/remote_execution/worker_api.proto
proto/genproto/com.github.allada.turbo_cache.remote_execution.pb.rs
util/BUILD
util/common.rs
util/error.rs

Implements the execution_response() function. This will allow
workers to let the scheduler and thus the client know a job has
an updated state (usually completed or errord).
This required a few API changes, but nothing dramatic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/54)

Implement execution_response() in WorkerApiServer

---

cas/scheduler/platform_property_manager.rs
config/cas_server.rs
config/examples/basic_cas.json
config/examples/filesystem_cas.json
config/examples/s3_backend_with_local_fast_cas.json

* Adds the initial config for workers to use use
* Rename PropertyType::Metadata to PropertyType::Priority
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/55)

Add worker config definitions and rename Metadata to Priority

---

README.md

Fixes the URL used to show the CI badge on the Readme.md file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/58)

Fix github CI badge

---

cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
proto/com/github/allada/turbo_cache/remote_execution/worker_api.proto
proto/genproto/com.github.allada.turbo_cache.remote_execution.pb.rs

Updates the worker_api.proto so it can return error codes for
internal errors in the event that an internal error occurred.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/60)

Adds ability in proto for worker to return internal errors

---

cas/grpc_service/BUILD
cas/grpc_service/ac_server.rs
cas/grpc_service/execution_server.rs
cas/scheduler/BUILD
cas/scheduler/action_messages.rs
cas/scheduler/platform_property_manager.rs
cas/store/BUILD
cas/store/ac_utils.rs
config/cas_server.rs
config/examples/basic_cas.json

* Worker config is now a struct instead of string
* Moved ac_utils into store folder instead of scheduler
* Changed execution priority from i64 to i32
* Add PlatformPropertyValue::Unknown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/61)

Various minor updates

---

cas/store/memory_store.rs
cas/store/tests/memory_store_test.rs
util/buf_channel.rs

An edge case was discovered in another unit test where a zero
byte object (empty file) would error out during receive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/64)

Fix bug in memory store when receiving a zero byte object

---

cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/verify_store.rs

This will enable us to down-cast the stores into specific
implementations in certain cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/65)

Adds .as_any() to stores

---

cas/cas_main.rs
cas/store/BUILD
cas/store/fast_slow_store.rs
cas/worker/BUILD
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs
util/error.rs

Adds function download_to_directory() which is used to download
a digest encoded as a Directory proto and build a local directory
with those files present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/67)

Add functionality for worker to download and create working dir

---

cas/cas_main.rs
config/cas_server.rs
config/examples/basic_cas.json

We require a FastSlowStore to be used when configuring a LocalWorker.
There was a mistake made where it was enforced, but not documented.
This PR updates the documentation, renames some configs to make it
more clear and updates one of the example configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/73)

FastSlowStore now properly documented and used in LocalWorkerConfig

---

cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs

Not all providers provide the unix_mode flags, but all do provide
is_executable flag for files. This PR ensures that if you pass
is_executable it will `or` the flags with `0o111` to ensure it is
actually executable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/74)

`is_executable` flag on files now overrides unix_mode exec flag

---

.bazelrc
cas/grpc_service/capabilities_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/action_messages.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/scheduler_test.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs

The documentation in the bazel remote execution proto is confusing.
It states that the output_paths will be relative to working directory
which was interpreted as CWD. This PR fixes this miss-understanding
and now files are relative to input_root.
Also, it turns out that bazel does not yet support 2.1, so we
are now populating the deprecated fields as well as the new fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/75)

Support deprecated symlink fields & fix bug for workers use CWD

---

.bazelrc
cas/grpc_service/ac_server.rs
config/examples/basic_cas.json
proto/update_protos.py
util/evicting_map.rs

* Add cpu_count=1 to execution properties of self_execute config
* Add platform suffix to self_execute config
* Remove out-of-date comment
* Updated basic_cas.json.config to use remote execution better
* EvictingMap now gives an info message when items are removed
* `update_protos.py` fixed issue where it was using abspath instead
of realpath
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/76)

Various minor changes

---

cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/utils/mock_running_actions_manager.rs

`output_paths` were being created, but not `output_files`. This patch
fixes this discrepancy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/84)

Fix bug on output_files' folders were not being created

---

cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
cas/scheduler/worker.rs

There was a bug where platform properties were not being restored
on tasks after they were completed and worker<->task match making
was not being triggered on completed tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/85)

Fix scheduler so platform properties are properly restored

---

.bazelignore
cas/worker/local_worker.rs
cas/worker/tests/local_worker_test.rs
util/fs.rs

This fixes a bug when the worker does not shutdown properly there
might be stuff left over in the work_directory. Now the directory
is walked and all files and folders are removed before creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/89)

LocalWorker will now purge the work directory on construction

---

Cargo.toml
third_party/remote/BUILD.ahash-0.7.6.bazel
third_party/remote/BUILD.atty-0.2.14.bazel
third_party/remote/BUILD.clap-2.34.0.bazel
third_party/remote/BUILD.cpufeatures-0.2.2.bazel
third_party/remote/BUILD.dirs-sys-0.3.7.bazel
third_party/remote/BUILD.dirs-sys-next-0.1.2.bazel
third_party/remote/BUILD.filetime-0.2.16.bazel
third_party/remote/BUILD.getrandom-0.2.7.bazel
third_party/remote/BUILD.mio-0.8.3.bazel
third_party/remote/BUILD.native-tls-0.2.10.bazel
third_party/remote/BUILD.nix-0.23.1.bazel
third_party/remote/BUILD.num_cpus-1.13.1.bazel
third_party/remote/BUILD.parking_lot_core-0.9.3.bazel
third_party/remote/BUILD.rand-0.8.5.bazel
third_party/remote/BUILD.sha2-0.9.9.bazel
third_party/remote/BUILD.socket2-0.4.4.bazel
third_party/remote/BUILD.tempfile-3.3.0.bazel
third_party/remote/BUILD.time-0.2.27.bazel
third_party/remote/BUILD.tokio-1.19.2.bazel

We now support more platforms specifically ARM is now supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/91)

Support more platforms for compilation

---

util/BUILD
util/resource_info.rs
util/tests/resource_info_test.rs

Fixes a bug that if an upload is attempted but no instance_name is configured it will error out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/100)

Fix bug if no instance_name/resource_name is given upload does not work

---

cas/store/BUILD
cas/store/filesystem_store.rs
cas/store/tests/filesystem_store_test.rs
cas/worker/running_actions_manager.rs
util/evicting_map.rs
util/fs.rs
util/tests/evicting_map_test.rs

This PR introduces a massive overhaul to remove the dependency on renameat2 as well as fix bugs in the process. The bugs found are:
* unref() was not being called when insert() replaced an item
* Various extremely unlikely corner cases around files being created, replaced, deleted
* Edge case where the contents of a FileEntry could use the wrong data on data replacement (although very unlikely).
The paradime of "FileEntry" entries and it's corresponding file are now full immutable, meaning if the file gets replaced it will generate a new FileEntry and shuffle the files around so both may be read uninterrupted at any point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cac …

Overhaul filesystem store to no longer use renameat2

---

proto/BUILD
proto/gen_protos_tool.rs
proto/update_protos.py

Instead of invoking the gen_protos_tool on every file, make it run on all proto files at once. This way we can simplify the proto build file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/111)

Simplify proto generation logic

---

cas/scheduler/BUILD
cas/scheduler/action_messages.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/scheduler_test.rs

The ordering of scheduled jobs is incorrect, it currently executes them in a stack rather than a queue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/120)

Scheduled jobs should be in a queue, not a stack.

---

cas/store/BUILD
cas/store/default_store_factory.rs
cas/store/filesystem_store.rs
cas/store/tests/filesystem_store_test.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs

This is should have no functional difference, these callbacks were only used for testing and used up needless memory for live systems. This PR should save about 32 bytes per FileEntry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/114)

Remove the callbacks from the filesystem_store

---

README.md

Added documentation about needing to use `-c opt` for production builds.
I did some crude testing of various LTO testing as well and found that it does not appear to improve performance enough for the potential problems it might produce.
Results:
```
$ bazel build //cas
93.426  bazel unoptimized
663.727 turbocache unoptimized
$ bazel build -c opt //cas
10.077  bazel optimized
48.151  turbocache optimized
$ bazel build -c opt --@rules_rust//:extra_rustc_flags=--codegen=lto=thin //cas
9.673   bazel with thinlto
48.654  turbocache optimized with thinlto
$ bazel build -c opt --@rules_rust//:extra_rustc_flags=--codegen=lto=fat //cas
9.965   bazel with fatlto
47.874  turbocache optimized with fatlto
```
From these results `fat` is best, but this was only over 1 run, so it is unknown if it …

Document that users should use `-c opt` for release builds

---

cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
cas/scheduler/worker.rs

Currently each worker only tracks the last action that was sent to it,
and they might be running multiple, so if the worker is evicted only
the last action is retried.
Testing this exposes some issues in the do_try_match algorithm, namely
that it continues after performing an immediate_evict_worker which will
invalidate any of its assumptions due to the clone of queued_actions.
This also means that if a single action fails on a worker, we don't abort
all of the actions on that worker, only the action that failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/122)

Workers may be running multiple actions, so track them individually.

---

cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/utils/mock_running_actions_manager.rs

When the scheduler disconnects from the worker it continues to run the actions.  This is a pointless endeavour as, even if the scheduler reconnects, the actions will have been purged and the results will be ignored.  Therefore don't waste CPU (or RAM) and kill jobs immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/126)

Kill currently running actions on scheduler disconnect.

---

.bazelrc
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE
cas/grpc_service/tests/bytestream_server_test.rs
cas/scheduler/action_messages.rs
cas/scheduler/worker.rs
cas/store/grpc_store.rs
cas/worker/tests/utils/local_worker_test_utils.rs
proto/genproto/build.bazel.remote.execution.v2.pb.rs
proto/genproto/com.github.allada.turbo_cache.remote_execution.pb.rs
proto/genproto/google.bytestream.pb.rs
proto/genproto/google.longrunning.pb.rs

Update Rust to 1.70.0 and bring the Cargo.toml file in sync with the versions currently used in Cargo.Bazel.lock.
Explicitly depend on protobuf to make future transition to bzlmod simpler and to future-proof the repository for upcoming rust prost toolchains.
The fixed-buffer crate is excluded from these updates as changing it is a bit more involved and that code will likely be reworked as part of migration away from rusoto.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/143)

Update all dependencies to their latest versions

---

cas/worker/BUILD
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/wrapper_for_test.sh
config/cas_server.rs
config/examples/basic_cas.json
deployment-examples/docker-compose/worker.json
deployment-examples/terraform/scripts/worker.json
run_integration_tests.sh

Fixes an oversight where the design called for `entrypoint_cmd` config, but it was never implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/139)

Fixes the `entrypoint_cmd` configuration

---

.bazelrc

This allows builds to continue to work on older platforms.
This closes #146.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/147)

Change the version of C++ used for protoc to the earliest supported.

---

cas/grpc_service/execution_server.rs

This is the deprecated way of populating properties, but it's required to support Goma.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/159)

Goma places the platform properties in the command

---

cas/scheduler/action_messages.rs
util/common.rs
util/error.rs

Also addresses most clippy warnings related to these files as long as they don't affect other files too much.
The impls that could panic should be implemented via TryFrom, but changing this would affect more files. For now, keep it as From and change those in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/158)

Implement Into traits indirectly via From

---

cas/cas_main.rs
cas/grpc_service/capabilities_server.rs
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/BUILD
cas/scheduler/action_messages.rs
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/grpc_scheduler.rs
cas/scheduler/scheduler.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/worker/tests/local_worker_test.rs
config/schedulers.rs

This implements an ActionScheduler that is able to forward to an upstream GrpcScheduler.  This allows proxying scheduler tasks from one instance to another.  This is useful when combined with a CacheLookupScheduler.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/160)

Implement a GrpcScheduler to forward.

---

cas/store/filesystem_store.rs
cas/store/memory_store.rs
cas/store/tests/filesystem_store_test.rs
util/evicting_map.rs
util/tests/evicting_map_test.rs

Since this clippy warning requires touching several files we handle it separately. Most remaining warnings should be self-contained enough that we can handle them on a file-by-file basis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/163)

Add is_empty to LenEntry

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
cas/store/dedup_store.rs
util/BUILD
util/common.rs
util/evicting_map.rs

We make so many copies of DigestInfo and it's not trivial-copyable because of an optimization that adds around 40 bytes of data to each struct which tries to preserve the string representation of the digest when possible. This optimization seems to be pointless and likely ends up costing more than it saves.
On local testing, I found that the overhead of the LazyInit was slightly more than a single invocation of `.str()`. Since we usually only call `.str()` once per DigestInfo, it does not seem like a good idea to assume we would need the hex string more than once per struct.
There is also a significant chance this will give secondary optimizations because without this optimization the struct is trivially-copyable. This enables the optimizer to do even more clever tricks for inlining since …

Removes needless overoptimization of strings for DigestInfo

---

cas/scheduler/simple_scheduler.rs
cas/scheduler/worker.rs
cas/worker/local_worker.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/utils/local_worker_test_utils.rs
config/cas_server.rs

Our main issue is that some parts of our code base eat all of the RAM.  This is one of the mitigations against that.
This allows workers to be configured with minimum resource limits separately to the the platform properties.  This allows them to return a ResourceExhausted state which pauses the worker on the scheduler until an action has completed (if it has one).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/167)

Add support for backpressure from workers.

---

cas/cas_main.rs
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/BUILD
cas/scheduler/cache_lookup_scheduler.rs
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/grpc_scheduler.rs
cas/scheduler/scheduler.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/cache_lookup_scheduler_test.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/scheduler/tests/utils/mock_scheduler.rs
cas/scheduler/tests/utils/scheduler_utils.rs
config/BUILD
config/cas_server.rs
config/schedulers.rs
config/stores.rs

This scheduler sits in front of another one and looks up actions in
the cache if requested before queueing them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/161)

Implementation of a cache lookup scheduler

---

WORKSPACE

This issue has been fixed upstream, so we just override the version provided by com_google_protobuf with this newer version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/180)

Fix "unused function" warnings in utf8_range

---

cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/action_messages.rs
cas/scheduler/simple_scheduler.rs

In the code as it is written right now it is not possible for this to happen, but it could easily be implemented on the worker without needing to touch the scheduler code.
The case if the worker looked up the action in the cache and found a hit, it could return a result stating it was served from cache. In this event the scheduler would never flag the action as completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/179)

Fix potential bug where scheduer could drop action and remove Arc

---

.bazelrc

After this change it is a hard error to commit anything that doesn't
conform to Clippy's default warning set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/182)

Enable clippy

---

cas/grpc_service/bytestream_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/store/store_trait.rs

Spawns are very expensive to make and one of the most common API points is BystreamServer::read. From a long time ago it was really hard to get lifetimes to live long enough here for the stream API. Armed with more experience the lifetimes are now resolved, so we do not need to use this pointless spawn.
Now we will pipe the data from the store to the client in the same spawn, which means we will have a very high chance of being on the same thread when shipping bytes to the client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/183)

Remove need for spawn in BytestreamServer

---

.bazelrc
WORKSPACE
util/evicting_map.rs
util/tests/async_fixed_buffer_test.rs

Detecting data races and memory issues in unsafe code can be difficult and time consuming.
To aid with this, add an optional nightly toolchain which exposes experimental `-Zsanitizer` flags. This lets us run builds and test with `--config=asan` and `--config=tsan` to enable AddressSanitizer and ThreadSanitizer. These sanitizers incur heavy performance penalties and shouldn't be enabled in production builds.
We can't enable these in CI yet, since ref_store_test fails under asan and all runtime tests fail under tsan.
The changed rust files fix issues that trigger nightly clippy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/185)

Add optional sanitizer build configurations

---

.github/workflows/main.yml
cas/store/default_store_factory.rs
cas/store/ref_store.rs
cas/store/tests/ref_store_test.rs
deployment-examples/docker-compose/Dockerfile

Enables ASAN tests in CI and fixes the circular reference it found.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/187)

Fix ASAN error and enable ASAN in CI

---

.bazelrc
tools/BUILD
tools/tsan.sh

Bazel does not make it easy to add a file to every test as a dependency. But it does have --run_under, so we hijack this in order to make our suppression file. Later we may want to make a macro override for our test rules to add the suppression file if it grows too large.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/189)

Add TSAN suppression and harness

---

cas/grpc_service/execution_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/scheduler/action_messages.rs
cas/scheduler/cache_lookup_scheduler.rs
cas/scheduler/grpc_scheduler.rs
cas/scheduler/scheduler.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/cache_lookup_scheduler_test.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/scheduler/tests/utils/mock_scheduler.rs
cas/scheduler/tests/utils/scheduler_utils.rs
cas/worker/local_worker.rs
cas/worker/tests/local_worker_test.rs
proto/com/github/allada/turbo_cache/remote_execution/worker_api.proto
proto/genproto/com.github.allada.turbo_cache.remote_execution.pb.rs
util/common.rs

We already have a unique way to reference a task `ActionInfoHashKey`. This PR removes the need for name in the ActionState and adds `unique_qualifier` to this field instead. This PR also adds the utilities needed to convert to-from a string, so components can reference the task by a unique name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/186)

Removes name from action state

---

cas/store/BUILD
cas/store/grpc_store.rs
config/stores.rs
deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json

When forwarding AC to an upstream GrpcStore. the store type is lost along the way.  If the GrpcStore is used directly then there's optimisations, however, if it's wrapped in another store (such as a fast-slow store) then the context is lost and queries go to the CAS server.
Instead, we make it possible to specify the upstream server type and enforce the upstream request to go via the AC server endpoint.  This is a little less efficient as tonic decodes the message then we have to re-encode it so it can be used by other stores, but it's the simplest solution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/184)

Add store type to GrpcStore.

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
cas/grpc_service/execution_server.rs
cas/scheduler/BUILD
cas/scheduler/cache_lookup_scheduler.rs
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/grpc_scheduler.rs
cas/scheduler/scheduler.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/cache_lookup_scheduler_test.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/scheduler/tests/utils/mock_scheduler.rs
config/schedulers.rs

These functions are used by Goma.
This also resolves the issue of holding on to abandoned queued jobs.
I probably could break this down into a few more PRs, but I'd likely break something along the way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/177)

Implement the WaitExecution

---

cas/store/grpc_store.rs

Unexplicably, the Error context was removed when getting the upstream data from a GrpcStore.  This means that the Code::NotFound is removed and copious error messages are spewed for missing action cache entries.
Resolves #197
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/199)

Don't remove Error context.

---

cas/grpc_service/cas_server.rs
cas/scheduler/action_messages.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/action_messages_test.rs
cas/store/dedup_store.rs
cas/store/filesystem_store.rs
cas/store/grpc_store.rs
cas/store/memory_store.rs
cas/store/s3_store.rs
cas/store/tests/filesystem_store_test.rs
util/common.rs
util/evicting_map.rs

When re-factoring the GrpcScheduler change, a dodgy copy-paste made it in.  Fix up the type check to the correct type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/203)

Fix incorrect type check.

---

cas/grpc_service/cas_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/scheduler/cache_lookup_scheduler.rs
cas/store/BUILD
cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/grpc_store.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/verify_store.rs
util/BUILD
util/common.rs
util/evicting_map.rs

Currently the `has` method in the StoreTrait takes a single DigestInfo which means that it only has to do a single lookup at a time.  This is optimised in places for the GrpcStore to ensure that efficient upstream lookups are performed.
However, if the GrpcStore is wrapped in another store (e.g. FastSlowStore for a local cache) then the `has` call is performed for each DigestInfo which is very inefficient on the GrpcStore call.
This optimises that use case by having each Store implementation pass through all DigestInfos that are being requested meaning the by-pass is no longer required for GrpcStore::has and all other stores can make use of the optimised route.
- - - …

Change StoreTrait::has to take HashSet.

---

cas/store/filesystem_store.rs
cas/store/memory_store.rs
cas/store/verify_store.rs
util/evicting_map.rs
util/prometheus_utils.rs

This makes things a little easier to use and collapses more of the functions into a single main entry point `.publish()` with the exception of `.publish_stats()`, because we want the user to understand when they publish slices of numbers it is treated as a stat.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/210)

Improve prometheus utils api

---

cas/scheduler/BUILD
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/property_modifier_scheduler.rs
cas/scheduler/tests/property_modifier_scheduler_test.rs
config/schedulers.rs

In order to avoid modifying the Goma executable, add a wrapping scheduler that is able to modify the properties that are passed in from it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/214)

Add property modifying scheduler.

---

cas/BUILD
cas/cas_main.rs
cas/store/verify_store.rs
config/cas_server.rs
util/evicting_map.rs
util/prometheus_utils.rs

Adds the ability to disable metrics through env via TURBO_CACHE_DISABLE_METRICS or through config file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/215)

Add ability for metris to be disabled

---

config/cas_server.rs

Fixes minor regression where if the "max_action_timeout" was not set it would not not allow the worker to start.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/226)

Fix default config regression in master

---

cas/grpc_service/BUILD
cas/grpc_service/bytestream_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
config/cas_server.rs

On high latency network connections it is possible that streams will be dropped from time to time. This allows us to now resume from where the upload stream was dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/220)

Streams may now be resumed on disconnect

---

deployment-examples/docker-compose/Dockerfile
deployment-examples/docker-compose/docker-compose.yml

This will allow users to do things like install custom packages into the worker docker container.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/254)

Add ADDITIONAL_SETUP_WORKER_CMD to Dockerfile

---

.dockerignore
.github/workflows/main.yml
README.md
cas/store/tests/ac_utils_test.rs
deployment-examples/docker-compose/Dockerfile
deployment-examples/docker-compose/docker-compose.yml
deployment-examples/docker-compose/worker.json
run_integration_tests.sh

Dramatically simplifies the Dockerfile for docker-compose example, clarifies some documentation, makes tests run in 18.04, 20.04 and 22.04 and fixes a minor test flake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/258)

Simplify Dockerfile and prepare for Goma example

---

cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs

In the event the worker disconnects from the scheduler, we now wait until all actions are killed before we attempt to reconnect to the scheduler. This prevents a race condition where the scheduler does not know about an action the worker is doing resulting in a potential of the scheduler sending the same action to the worker that it has not cleaned up yet.
fixes #246
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/266)

Fix potential race condition if worker disconnects

---

Cargo.lock
README.md
cas/BUILD
cas/cas_main.rs
cas/grpc_service/bytestream_server.rs
cas/worker/local_worker.rs
gencargo/cas/Cargo.toml

To prevent an error message from the worker stating it cannot connect to the scheduler due to startup ordering, we now always startup workers after schedulers are listening.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/275)

Worker services now start after listeners to prevent error confiusion

---

cas/grpc_service/bytestream_server.rs
cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/grpc_store.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/tests/filesystem_store_test.rs
cas/store/verify_store.rs

Due to DropCloserWriteHalf being so fragile in how it is dropped, it was decided that we should prefer to pass an owned version to the store api and introduce `.get_part_ref()` to handle cases where the writer should not be dropped on the return.
This will protect from cases where users join!() the reader and writer sides, but a deadlock happens because the writer errors but doesn't drop, notifying the reader side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/292)

Introduce get_part_ref() and migrate primary use to .get_part()

---

Cargo.lock
cas/store/BUILD
cas/store/memory_store.rs
cas/store/tests/memory_store_test.rs
gencargo/memory_store_test/Cargo.toml

possibly fix: #289
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/294)

Always make a copy in MemoryStore to reduce long-lasting allocs

---

cas/cas_main.rs

#206 
Total ip/ports that have connected since server started are published in prometheus now for each service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)

Prometheus now publishes number of clients connected since server started and the timestamp when the server starts

---

proto/update_protos.py

The previous variant didn't account for different newline encodings on Unix and Windows. This wasn't (and still isn't) visible in CI because the Windows workflow only invokes Cargo tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/314)

Make update_protos test compatible with Windows

---

cas/store/tests/memory_store_test.rs

After looking at CI test failures it seems that the ASAN builds cause an RSS increase of ~14%  to ~17%. Set the limit to 20% to reduce flakiness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/318)

Reduce flakiness of memory_store_test

---

.bazelrc

Turns out that `startup:someconfig` is invalid syntax. Since the flag only applies to Windows it's safe to make it global.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/327)

Globally enable windows symlinks

---

.envrc
.github/workflows/nix.yaml
.gitignore
CONTRIBUTING.md
Cargo.lock
flake.lock
flake.nix
tools/wrapped-bazel.nix

Provide a mostly self-contained development environment automatically sets up tooling like Cargo and Bazel via nix.
This makes it easy for nix users to contribute to our project and enables future work on reproducible release binaries and containers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/330)

Introduce Nix development flake

---

integration_tests/simple_remote_execution_test.sh
run_integration_tests.sh

Minor issues related to MacOS for the integration tests.
Fixes # https://github.com/TraceMachina/turbo-cache/pull/316
Not technically an issue. It's blocking an in-progress PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/334)

Integration test should work for Mac OS.

---

cas/scheduler/grpc_scheduler.rs

The GrpcScheduler fails to close the downstream Receiver when the upstream one completes.  This causes it to hang forever even though its completed.
Fixes #323
Using a GrpcScheduler in front of a SimpleScheduler to a Reclient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/328)

Close on complete in GrpcScheduler

---

cas/store/s3_store.rs
util/buf_channel.rs
util/tests/buf_channel_test.rs

This variation on make_buf_channel_pair omits the EOF check. This works around the fact that S3 drops connections as soon as all data is sent or received.
Fixes #304 and fixes the same issue for non-oneshot cases where a similar issue occurred as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/341)

Add optimistic channels

---

.github/workflows/main.yml
.github/workflows/unit-test.yaml

Unify workflows for Unix and Windows and use more efficient caching for workflow artifacts. Harden the workflow with fixed action hashes.
Reduces Linux workflow runtime to ~1 min for best-case cache hits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/342)

Refactor Bazel unit test CI

---

README.md

The Bazel documentation and ecosystem more commonly refer to the remote execution protocol as the [RBE](https://bazel.build/remote/rbe).
Documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/349)

Update the README for discoverability.

---

cas/worker/running_actions_manager.rs

Small change to make it a little easier to debug when something goes wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/363)

Add more err_tip for easier debugging

---

cas/cas_main.rs
config/cas_server.rs
util/serde_utils.rs

Some users will want to tune advanced http2 configurations. This PR gives that ability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/365)

Add Http2 flags for advanced configurations

---

cas/worker/BUILD
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs
config/cas_server.rs
gencargo/running_actions_manager/Cargo.toml

This change allows the wrapper scripts to talk via a side channel file to instruct TurboCache that a timeout has occurred.
This also adds the ability to use the max timeout as TurboCache's timeout which allows the wrapper script to manage timeout manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/368)

Add ability for external scripts (ie: entrypoint_cmd) to manage timeout

---

cas/store/tests/filesystem_store_test.rs

Clippy complained with `never_loop`, and indeed these loops never loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/372)

Fix never looping loops

---

cas/store/tests/filesystem_store_test.rs

Reverts TraceMachina/turbo-cache#372
This is a pessimzation code-wise and appears to still not solve the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/373)

Revert "Fix never looping loops"

---

run_integration_tests.sh

Added server readiness string listening to integration tests to reduce flakiness
Listens for string from docker-compose logs to indicate that the servers are ready and listening before running integration tests.
Fixes #375 
Ran all tests individually and together. TLS test was flaky when running with all tests before change and had no failed runs afterwards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/378)

Fixed flakiness in integration tests

---

cas/worker/tests/local_worker_test.rs
cas/worker/tests/utils/local_worker_test_utils.rs
cas/worker/worker_utils.rs
config/cas_server.rs

Fixed the typo `WrokerProperty` to `WorkerProperty` in 12 occurrences.
There were no more typos of `Worker` besides this one.
Fixes #390 
Ran all tests individually and all together.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/391)

Fix the typo of WorkerProperty

---

Cargo.lock
cas/store/ac_utils.rs
cas/worker/running_actions_manager.rs
gencargo/fs/Cargo.toml
util/BUILD
util/fs.rs

Restructures some of the logic to allow recycling of already allocated memory during digest uploads and hashing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/396)

Reduce allocations needed to hash uploads

---

flake.nix

The previous implementation would automatically fetch rustc for cargo
builds. Explicitly add rustc to the flake so that it's version is pinned
and in sync with the cargo package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/398)

Add rustc explicitly to flake

---

Cargo.lock
cas/scheduler/BUILD
cas/scheduler/action_messages.rs
gencargo/action_messages/Cargo.toml

Migrate the internal hashing algorithm used to compute the hash for the action when sending to/from the worker/scheduler. This is a minor optimization to move away from Sha256.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/395)

Use Blake3 hasher for computing the action message

---

deployment-examples/terraform/AWS/scripts/start_turbo_cache.sh

- Accept shellcheck SC2155 recommendations in start_turbo_cache.sh
- Remove SCHEDULER_URL as it is both unused & refers to a nonexistent key
- Accept shellcheck SC2004
- Fix double negative when computing remaining memory % in terraform deployment
I saw this while browsing through the code. There was a double negative sign.
While I was there, I accepted some shellcheck recommendations, which you can 
see in the individual commits.
It has not been tested.
reviewability. You are welcome to squash it at merge time.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/407)

Fix subtraction bug in start_turbo_cache.sh

---

native-link-store/BUILD.bazel
native-link-store/src/s3_store.rs
native-link-store/tests/s3_store_test.rs

Some http servers can send empty strings in the stream, but we
do not allow this in our code since this is the EOF signal.
Also adds ability to use custom AWS_ENDPOINT_URL env to change
destination of s3 endpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/421)

Fix empty bytes error in s3 store and support AWS_ENDPOINT_URL

---

native-link-config/src/cas_server.rs
native-link-worker/src/running_actions_manager.rs

Minor changes to allow HttpServerConfig to use default values if not set in config.
Also a minor change for format_execute_response_message to format the digest_function value to lower case to make it compatible with bb_browser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/438)

Fixup configs to have defaults & digest function uses lower case

---

Cargo.Bazel.lock
WORKSPACE.bazel

Enable running rust tests on Apple Silicon.
```
CARGO_BAZEL_REPIN=true bazel test //...
```
- [] `bazel test //...`  passes locally
NOTE: Not all tests pass locally, this could be an indication of bug with implementation/test on osx.
```
//native-link-worker:integration_tests/local_worker_test                 FAILED in 0.5s
/private/var/tmp/_bazel_adam/40c88777425c71ea9813d14d612023d6/execroot/native-link/bazel-out/darwin_arm64-fastbuild/testlogs/native-link-worker/integration_tests/local_worker_test/test.log
//native-link-worker:integration_tests/running_actions_manager_test      FAILED in 0.7s
/private/var/tmp/_bazel_adam/40c88777425c71ea9813d14d612023d6/execroot/native-link/bazel-out/darwin_arm64-fastbuild …
```

Bazel enable aarch64-apple-darwin by adding to crates repository supported platforms

---

native-link-scheduler/src/cache_lookup_scheduler.rs
native-link-service/src/ac_server.rs
native-link-service/src/bytestream_server.rs
native-link-service/src/cas_server.rs
native-link-store/src/compression_store.rs
native-link-store/src/dedup_store.rs
native-link-store/src/existence_cache_store.rs
native-link-store/src/fast_slow_store.rs
native-link-store/src/filesystem_store.rs
native-link-store/src/grpc_store.rs
native-link-store/src/memory_store.rs
native-link-store/src/noop_store.rs
native-link-store/src/ref_store.rs
native-link-store/src/s3_store.rs
native-link-store/src/shard_store.rs
native-link-store/src/size_partitioning_store.rs
native-link-store/src/verify_store.rs
native-link-store/tests/ref_store_test.rs
native-link-util/src/store_trait.rs
native-link-worker/src/local_worker.rs
native-link-worker/src/running_actions_manager.rs

Adds `inner_store()` function to all stores that enables the resolution of inner stores recursively to get an underlying store. This is mostly for places that can perform optimizations when specific code paths can be optimized with specific stores.
towards: #409
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/410)

Add function to Store API to get the inner store when possible

---

Cargo.Bazel.lock
Cargo.toml
src/bin/cas.rs

This allows Ctrl+c killing the cas executable in environments that don't invoke the it via a shell wrapper. This is the case in, for instance, minimal container images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/434)

Handle SIGINT

---

native-link-store/src/filesystem_store.rs
native-link-store/tests/filesystem_store_test.rs

* Refactor `filesystem_store::FilesystemStore` to allow for controlling sleep function from outside of implementation. 
* Hoist `BytesMut.split()` to a position before the loop to prevent subsequent calls that result in an empty buffer. Original patch: https://github.com/TraceMachina/native-link/pull/426 / @Jirixek 
https://github.com/TraceMachina/native-link/pull/426
`get_part_timeout_test` unit test against non-hoisted `BytesMut.split()` will trigger the bug, once split is moved bug is no longer present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/439)

Fix lost file data in filesystem store (with test)

---

CONTRIBUTING.md
README.md
flake.lock
flake.nix
tools/llvmStdenv.nix

This commit makes Native Link directly buildable/runnable via nix:
```bash
nix run github:TraceMachina/native-link /path/to/config.json
```
To reduce closure size for upcoming container images the environment that builds the derivation is a fairly customized LLVM-based toolchain. This toolchain should make it easier to migrate to more sophisticated approaches in the future.
Test infrastructure is not yet enabled as it'll be a larger effort to make our testsuite compatible with strictly controlled environments like the nix build sandbox.
Importantly, the updated README now makes extensive use of emojis ✨
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/442)

Make Native Link installable via nix

---

.github/workflows/image.yaml
.gitignore
README.md
flake.nix
tools/local-image-test.nix
tools/publish-ghcr.nix

Introduce signed, fully reproducible container images that are created
on pushes to main and published via GitHub packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/443)

Publish container images

---

README.md
tools/publish-ghcr.nix

GitHub doesn't support our `TraceMachina` name for the registry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/447)

Make container registry lowercase

---

native-link-config/examples/basic_cas.json
native-link-config/src/cas_server.rs
native-link-scheduler/src/simple_scheduler.rs
native-link-scheduler/src/worker.rs
native-link-scheduler/src/worker_scheduler.rs
native-link-scheduler/tests/simple_scheduler_test.rs
src/bin/cas.rs

It implements an API to drain a specific worker.
It currently simply acts like pausing the worker and clearing existing running actions.
Fixes #351 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/413)

Implement API to drain a specific worker

---

native-link-store/tests/memory_store_test.rs

This is known to cause issues, especially for sanitized tests. Additional testing for MacOS showed that this needs to be at least 25%, so make it 30% to be on the safe side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/448)

Give flaky memory store test more wiggle room

---

.github/workflows/image.yaml
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml

This change gives our CI a more uniform structure where we have a native Bazel build, a native Cargo build and Nix-wrapped Bazel/Cargo builds. The updated files clarify where/how to add new runner architectures or remove old ones.
Also fixes a few dependency issues with the existing build files and enables cache-sharing between nix workflows on a per-derivation basis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/451)

Separate CI runs by build system

---

native-link-scheduler/src/simple_scheduler.rs
native-link-scheduler/tests/simple_scheduler_test.rs

Added error forwarding to client upon any command execution failures. Allows proper error workflow to complete for internal errors.
Fixes #257
Tested with plain bazel test //... to ensure all pass as well as bazel test //... after adding deliberate modifications to deployment-examples/docker-compose/worker.json to ensure error forwarding to client (ex. "entrypoint_cmd": "foo").
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/432)

Fixed error forwarding to client for failed command executions

---

.github/workflows/native-cargo.yaml

If we share caches between workflows, the runners run out of storage. If we separate the caches we have too many of them and keep stepping over GitHub's cache limitations. Remove caching entirely as this workflows doesn't take *that* long and we need the caches for Bazel and Nix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/458)

Remove caching from native cargo action

---

.github/workflows/image.yaml

Pauses a flake impacting the stability of the CI infrastructure as seen [here](https://github.com/TraceMachina/nativelink/pull/463#issuecomment-1850985745)
Fixes # (https://github.com/TraceMachina/nativelink/issues/465)
Comments out flakey workflow. 
No.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/466)

Pause Nix Derivation Flakes

---

src/bin/cas.rs

This enables rapid shutdown of deployments in k8s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/462)

Handle SIGTERM

---

deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json
deployment-examples/terraform/AWS/scripts/cas.json
deployment-examples/terraform/AWS/scripts/scheduler.json
deployment-examples/terraform/AWS/scripts/worker.json
deployment-examples/terraform/GCP/module/scripts/browser_proxy.json
deployment-examples/terraform/GCP/module/scripts/cas.json
deployment-examples/terraform/GCP/module/scripts/scheduler.json
deployment-examples/terraform/GCP/module/scripts/worker.json
nativelink-config/README.md
nativelink-config/examples/basic_cas.json
nativelink-config/examples/filesystem_cas.json
nativelink-config/examples/s3_backend_with_local_fast_cas.json
nativelink-config/src/cas_server.rs
nativelink-config/src/schedulers.rs
nativelink-config/src/stores.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/platform_property_manager.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/tests/compression_store_test.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs
src/bin/cas.rs

To make the configuration more standardized we have moved all config properties that might be set in the json to be lower case.
Before we had a mix of sometimes lower case and sometimes upper. By making this a hard rule, we simplify a lot of this thought.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/461)

[Breaking] Standardize configurations so they are all lower case

---

deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/terraform/AWS/scripts/cas.json
deployment-examples/terraform/GCP/module/scripts/browser_proxy.json
deployment-examples/terraform/GCP/module/scripts/cas.json
nativelink-config/README.md
nativelink-config/examples/basic_cas.json
nativelink-config/examples/filesystem_cas.json
nativelink-config/examples/s3_backend_with_local_fast_cas.json
nativelink-config/src/cas_server.rs
nativelink-service/src/bytestream_server.rs

Defaults "max_bytes_per_stream" to 64Kib in config file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/474)

Make max_bytes_per_stream optional in config

---

deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/docker-compose/scheduler.json
deployment-examples/terraform/AWS/scripts/cas.json
deployment-examples/terraform/AWS/scripts/scheduler.json
deployment-examples/terraform/GCP/module/scripts/browser_proxy.json
deployment-examples/terraform/GCP/module/scripts/cas.json
deployment-examples/terraform/GCP/module/scripts/scheduler.json
deployment-examples/terraform/GCP/module/scripts/worker.json
nativelink-config/README.md
nativelink-config/examples/basic_cas.json
nativelink-config/examples/filesystem_cas.json
nativelink-config/examples/s3_backend_with_local_fast_cas.json
nativelink-config/src/cas_server.rs
src/bin/cas.rs

Moved `listen_address` to `listener.http.socket_address` mapping.
This future proofs our config a bit more so we can add other kinds of listeners that are not http based (like unix sockets).
In doing this we also moved the http(s)/http2 related fields into the same struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/476)

[Breaking] listen_address renamed/remapped in config

---

deployment-examples/kubernetes/00_infra.sh
deployment-examples/kubernetes/01_operations.sh
deployment-examples/kubernetes/README.md

No need to use MetalLB since Cilium can do this as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/505)

Migrate L2 announcements and LB-IPAM to cilium

---

deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json
deployment-examples/terraform/AWS/scripts/cas.json
deployment-examples/terraform/AWS/scripts/scheduler.json
deployment-examples/terraform/AWS/scripts/worker.json
deployment-examples/terraform/GCP/module/scripts/scheduler.json
deployment-examples/terraform/GCP/module/scripts/worker.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/512)

Add OSFamily property to deployment examples

---

nativelink-store/BUILD.bazel
nativelink-store/src/cas_utils.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/lib.rs
nativelink-store/src/memory_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/cas_utils_test.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/memory_store_test.rs
nativelink-store/tests/s3_store_test.rs

[remote_execution.proto](https://github.com/TraceMachina/nativelink/blob/e1c495fa68b5d85872c98f9231689da4581161b1/nativelink-proto/build/bazel/remote/execution/v2/remote_execution.proto#L333) specification allows for uploading and fetching of empty digests regardless if they have been uploaded before a fetch. Expectation is the requests should always respond successfully. This can be an optimized path in cases but violates expectations in native link underlying storage consistencies.
Fixes # 
https://github.com/TraceMachina/nativelink/issues/498
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/507)

Support empty digests in stores

---

nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

This is to get around a docker-in-ci bug with how the host machine
is not able to sync files to disk properly.
see: #527
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/526)

Add small sleep in some tests to reduce flakes in CI

---

flake.nix
tools/llvmStdenv.nix

* Use built in darwin iconv library
* Make auto elf optional and not included on darwin
* On darwin use llvm linker and non-llvm use mold linker
Manually tests on MacOS
```
nix build
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/529)

MacOS enable flake nix builds

---

flake.nix

* Remove darwin based iconv for nix iconv lib
```
nix develop
nix build
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/534)

MacOS use non darwin iconv

---

.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/sanitizers.yaml

We cleaned up CI, so now we don't need to use the larger instances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/552)

Remove many of the large-* images in CI

---

BUILD.bazel
nativelink-config/BUILD.bazel
nativelink-proto/BUILD.bazel
nativelink-scheduler/BUILD.bazel
nativelink-service/BUILD.bazel
nativelink-store/BUILD.bazel
nativelink-util/BUILD.bazel
nativelink-worker/BUILD.bazel

Explicit short timeouts prevent tests from running indefinitely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/553)

Fix missing timeouts in tests

---

nativelink-worker/tests/running_actions_manager_test.rs

While I was testing on Windows x64 machine, I found out that running_actions_manager_tests::kill_all_waits_for_all_tasks_to_finish test never ends when I test with cargo test --all command.
Decreasing this number from 1000 to 100 seems to fix the problem on my machine.
I think being stuck or not depends on the operating system and the device's performance.
My Windows x64 machine was VPS with 8GB RAM. So maybe 1000 iteration got stuck I think.
In my opinion, 100 would be a reasonable number for this.
Fixes #492 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native …

Fix kill_all_waits_for_all_tasks_to_finish test stuck on windows

---

README.md
SECURITY.md

Reorders the README so getting started does not require Nix. 
Fixes (#517)
Documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/563)

Reorder README for Simplicity

---

nativelink-store/src/s3_store.rs

Credential provider is not supplied when creating [`aws_config::from_env()`](https://docs.rs/aws-config/0.57.1/aws_config/fn.from_env.html), that leads to failure responses seen in https://github.com/TraceMachina/nativelink/issues/428.
Pass the [`aws_config::default_provider::credentials.default_provider`](https://docs.rs/aws-config/0.57.1/aws_config/default_provider/credentials/fn.default_provider.html) into the `aws_config::from_env()` builder which should pick up the proper credentials for the environment based on the following [resolution order](https://docs.rs/aws-config/0.57.1/src/aws_config/default_provider/credentials.rs.html#27). 
https://github.com/TraceMachina/nativelink/issues/428 
Manually tested credentials …

S3 Store Credential Provider

---

.github/workflows/tagged_image.yaml
tools/publish-ghcr.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/569)

Publish SemVer-tagged images on tag pushes to main

---

CHANGELOG.md
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
README.md
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/572)

Release nativelink v0.2.0

---

BUILD.bazel
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
src/bin/nativelink.rs

[console-subscriber](https://docs.rs/crate/console-subscriber/latest) provides an instrumentation layer for async tokio applications. [console](https://github.com/tokio-rs/console)  provides viewing tasks, resources and histogram information. 
Tokio instrumentation is in unstable phase and requires additional build/rust flags to be enabled. These configuration are not enabled unless explicitly opted into, thus disabled by default in production/dev. Use the `tokio_unstable` **cfg** and `enable_tokio_console` **features** flags to enabled.
Example
======
Run native link with basic cas config.
```
cargo --config 'build.rustflags=["--cfg", "tokio_unstable"]' run --features enable_tokio_console -- nativelink-config/examples/basic_cas.json
```
New terminal (same host) to launch the tokio …

Add console-subscriber

---

nativelink-store/src/memory_store.rs
nativelink-store/src/shard_store.rs
nativelink-store/tests/shard_store_test.rs
nativelink-util/src/evicting_map.rs

* Fixes a bug where weights are not scaled to distribution space by summing weights after being scaled.
* Extend key data with size in bytes of digest object.
* Added test methods for getting internal length state, methods not needed for general use and marked as `_test`
* Added tests for verifying distributions with rounds of tests, spot checked the distributions look correct without statistical testing.  
https://github.com/TraceMachina/nativelink/issues/497
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/574)

Shard store weight scale distribution

---

nativelink-config/examples/basic_cas.json

I think we missed to add `OSFamily` and `container-image` property in `basic_cas.json` file.
I added `OSFamily` and `container-image` property for `local_worker` and `scheduler` in the configuration JSON file.
Fixes #576 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/577)

Add OSFamily property in basic_cas.json

---

.rustfmt.toml
flake.lock
flake.nix
tools/llvmStdenv.nix
tools/pre-commit-hooks.nix

Reduce container image sizes by over 50% to about 28 megabytes.
The nativelink executable is now fully self-contained and portable across linux systems regardless of the host's libc.
This change introduces new Rust toolchains on the nix side that mirror the Bazel toolchains. The new toolchains enable `cargo clippy` invocations without Bazel and allow invoking the same nightly `rustfmt` that is used in the Bazel build via pre-commit hooks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/583)

Build nativelink with musl

---

README.md

The `bazel run` command listed in the `README.md` file doesn't work.
I applied @aaronmondal 's recommendation for this PR and tested it works fine.
Detailed discussion can be found in the issue link below.
Fixes #582 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/590)

Fix the bazel run command documentation

---

nativelink-docs/docusaurus.config.js
nativelink-docs/src/css/custom.css

Fixes default theme selection so it is based off user preferences and also corrects the contrast to be more accessible as seen below.
Fixes #591
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/597)

Fix dark mode accessibility contrast and make theme dynamic

---

deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/terraform/experimental_AWS/scripts/cas.json
nativelink-config/README.md
nativelink-config/examples/filesystem_cas.json
nativelink-config/examples/s3_backend_with_local_fast_cas.json
nativelink-config/src/cas_server.rs
nativelink-config/src/stores.rs
nativelink-store/src/verify_store.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/digest_hasher.rs
src/bin/nativelink.rs

I've added Blake3 hash support Verify Store.
I just used the `digest_hasher` utiliy module to keep consistency.
For simplicity, I just used the default hash function which is set from the global config.
I've done integration tests on my machine to verify blake3 function actually works.
But since the global hash function is `OnceLock` and it can't be set twice, I couldn't add specific unit tests for blake3 and sha256 separately.
May it would be better if we add hash function config variable for the Verify Store Config?
Or is it just adding extra complexity?
I'd like to make this clear.
Fixes #444 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/575)

Add Blake3 support for Verify Store

---

nativelink-util/src/buf_channel.rs
nativelink-util/tests/buf_channel_test.rs

I fixed a potential bug in DropCloserReadHalf::take() function.
The regression test against the potential bug is done by `send_and_take_fuzz_test` in `nativelink-util/tests/buf_channel_test.rs`.
Detailed context can be found in the issue link below.
Fixes #578 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/606)

Fix a potential bug in DropCloserReadHalf::take()

---

nativelink-service/src/bytestream_server.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/evicting_map.rs

* Use `truncate` over `resize_with(1, || "".to_string())` reduce added function allocations/calls
* Reformat `if/let` logic 
* Fix spelling error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/607)

Minor refactor of functionally same code

---

.bazelrc
deployment-examples/docker-compose/local-storage-cas.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/565)

Enable blake3 for Bazel builds

---

deployment-examples/terraform/experimental_AWS/README.md

Add minor instruction to have AWS CLI IAM user configured. I started setting up nativelink from a new dev machine and forgot to setup my AWS credentials before running terraform. Figured a small reminder here couldn't hurt!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/608)

Update README.md for AWS Terraform Deployment

---

nativelink-config/src/stores.rs
nativelink-store/src/s3_store.rs

Add S3 TLS configuration to disable http2 in favor for http.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/604)

Add S3 http2 toggle flag

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
nativelink-config/src/cas_server.rs
nativelink-config/src/schedulers.rs
nativelink-config/src/serde_utils.rs
nativelink-config/src/stores.rs
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-service/Cargo.toml
nativelink-service/src/ac_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-store/Cargo.toml
nativelink-store/src/grpc_store.rs
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/lib.rs
nativelink-util/src/tls_utils.rs
nativelink-worker/Cargo.toml
nativelink-worker/src/local_worker.rs
src/bin/nativelink.rs

There is a need to secure the Action Cache for production builds which is not possible with out authentication of the store.  This can be provided by mTLS and the ability to make the action cache read only for some servers.
Fixes #467
Have a test system made of a storage, scheduler, build workers and Reclient consumers all utilising mTLS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/470)

Add support for mTLS

---

nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs

Implementation change for `EvictingMap` where all public methods should attempt at evicting keys that have expired. 
Refactor `size_for_key` to call `sizes_for_keys`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/601)

EvictingMap should evict keys on all public access

---

nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/fs.rs

In a rare case where a file is uploaded, but while the rename() function is called the future is dropped the filesystem store can get into a bad state.
fixes: #495
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/496)

Fix case where filesystem store future dropping causes issues

---

.rustfmt.toml
nativelink-proto/gen_lib_rs_tool.py
nativelink-proto/genproto/lib.rs

Fixes #618 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/617)

Unbreak manual rustfmt invocations via Bazel

---

deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json
deployment-examples/kubernetes/scheduler.json
deployment-examples/kubernetes/worker.json.template
nativelink-config/src/schedulers.rs
nativelink-config/src/stores.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/tls_utils.rs

Currently we apply no concurrency limits for GRPC calls to GrpcStore or GrpcScheduler.  This can cause issues for a heavily loaded upstream service that will start to build up reset streams and break.
This change modifies the configuration to have configuration per endpoint and adds an optional configuration to allow for setting a limit to the upstream concurrency.
Fixes #320
Local cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/627)

[BREAKING] Add concurrency limit to GRPC

---

nativelink-service/src/bytestream_server.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/buf_channel.rs

We see the first request in a GrpcStore request failing but this bypasses the retry logic because it's already passed out of the retry function.
Read the first message from the upstream GrpcStore within the retry logic, only exit from the retry logic after the first message was recieved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/616)

GrpcStore retry first

---

nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs

There's an unknown failure occuring under load where the filesystem store ends up with an entry in the temp path that doesn't exist.  I can't find that fault, but rather than persisting, it makes sense to avoid the failure persisting by removing it from the eviciting map in that case.
Therefore, this change introduces a change to the LenEntry such that touch() returns a bool.  If it returns false then it is removed from the EvictingMap immediately.
Running the code up on my cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/613)

Evict on touch failure

---

.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/tagged_image.yaml

This has been fixed upstream. Pull the change in early to speed up
workflows significantly. This also includes missing `github-token`
fields which increase the API rate limit.
Fixes: https://github.com/TraceMachina/nativelink/issues/464
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/631)

Reenable caching for nix workflows

---

.github/workflows/issues-notion-sync.yml

Allows notion to sync with issues in our public repo.
Secrets that will have to be set by an admin:
- NOTION_TOKEN
- NOTION_DATABASE
Database will likely get changed to task board if we decide to make task tracking based out of the repo (Dump into backlog by default and can be moved by user) but will be separate for now.
Fixes #639
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/642)

Create workflow for syncing Notion database and issues

---

nativelink-config/src/stores.rs
nativelink-error/src/lib.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/src/retry.rs
nativelink-util/tests/retry_test.rs

The retrier always retries on error.  However, some errors are permanent, for example NotFound.  This means that if a request is made to get something from the CAS (or GrpcStore AC) which is not there, it keeps trying even though it's still not there.  This defines the set of errors which shoudl be retried and fails otherwise.
Remote proxy getting data from the action cache now doesn't retry ad infinitum.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/634)

Don't retry permanent failures

---

nativelink-store/src/compression_store.rs
nativelink-store/src/existence_cache_store.rs

Adds metrics for existence cache store and compression store.
Fixes #647 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/651)

Add metrics to compression and existence cache store

---

nativelink-service/src/bytestream_server.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/resource_info.rs
nativelink-util/src/write_request_stream_wrapper.rs
nativelink-util/tests/resource_info_test.rs

The current implementation of retry in GrpcStore is awkward and only allows retry up until the first call to the WriteRequestStreamWrapper, however this has a buffer of the first message in it.  Therefore, with a bit of refactoring we are able to retry up until the second message is requested by Tonic without any degredation in performance.  This has the added benefit of being able to refactor the interface to be a Stream.
Using proxy in my cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/638)

GrpcStore Write Retry

---

README.md

Removes Alpha notice as it is out of date.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/657)

Remove Alpha notice

---

Cargo.lock
nativelink-config/src/schedulers.rs
nativelink-config/src/stores.rs
nativelink-scheduler/BUILD.bazel
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-store/src/grpc_store.rs
nativelink-util/BUILD.bazel
nativelink-util/src/grpc_utils.rs
nativelink-util/src/lib.rs
nativelink-util/src/retry.rs

Add a configuration option to limit the number of concurrent streams that are active with the upstream GrpcStore.
With this, we also introduce reconnection on error since Tonic doesn't do that.
Towards #602
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/656)

Max concurrent GrpcStore streams

---

nativelink-config/src/stores.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs

Fixes #595 
Should prevent scenarios where fragmented files take up more space than is allowed by `max_bytes` and could therefore exceed the maximum space available
`file_size` has been renamed to `data_size` since the actual file size on the disk after accounting for block size is provided by `get_file_size()` now.
`FileEntry::len` will now return get_file_size() since it is used by the `eviction_map` to determine what to evict based on size
All affected existing tests have been updated to use a block size of 1 so that they do not  have a max_bytes limit smaller than block size (which will hang but wouldn't occur in production)
A new test has been added to ensure that the `get_file_size` calculation returns the correct result for different inputs 
- - -
This change is [<img …

Account for block size in filesystem store for eviction purposes

---

README.md
nativelink-config/examples/basic_cas.json

This is a small change to both the `basic_cas.json` and the README to address a couple issues that have occured recently as a result of the documentation. 
Fixes #667 #666
Configuration, Documentation
It needs to be tested by readers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/669)

Basic Config to Use Filesystem

---

nativelink-store/src/fast_slow_store.rs
nativelink-store/tests/fast_slow_store_test.rs

FastSlow store now checks if the slow store is a no-op and replaces it with the fast store if it is.
Fixes #665
Checks if the slow store is replaced with the fast store if it is configured as a noop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/670)

Check for slow store to be noop and conditionally replace with fast

---

.bazelrc
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
Cargo.toml

This should fix recent CI breakages on main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/685)

Increase runner size for Cargo Dev and Sanitizer workflows

---

.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/tagged_image.yaml
deployment-examples/docker-compose/Dockerfile

Notably, the new workflows use Node 20 instead of Node 16 which might improve stability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/696)

Update GHA workflows

---

Cargo.lock
MODULE.bazel
nativelink-error/src/lib.rs
nativelink-proto/gen_protos_tool.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-service/src/ac_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-store/src/ac_utils.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/existence_cache_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/src/verify_store.rs
nativelink-util/src/common.rs
nativelink-util/src/health_utils.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/fastcdc_test.rs
nativelink-util/tests/health_utils_test.rs

Includes Rust 1.76.0, Rust nightly, zig-cc and python.
Fixes a bug in `ExistenceItem` where we didn't properly return the content length.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/690)

Update Bazel-tracked toolchains

---

Cargo.lock
Cargo.toml
nativelink-error/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-store/src/s3_store.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

The main change here is that we no longer differentiate between "other" and `Unhandled` errors. The distinction didn't make sense in the first place and is now handled uniformly as a retry case.
Towards #460
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/684)

Update AWS SDK to 1.x

---

Cargo.lock

Fixes https://osv.dev/vulnerability/RUSTSEC-2024-0019
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/719)

Bump mio to v0.8.11

---

README.md

This diagram is a general purpose diagram for describing NativeLink to people new to the project and looking to understand it conceptually.
Documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/705)

Draw a General Purpose Diagram

---

Cargo.lock
nativelink-store/src/ac_utils.rs
nativelink-util/Cargo.toml
nativelink-util/src/digest_hasher.rs
nativelink-util/src/fs.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Computing the digest now happens using mmap when using blake3 and changes default read size to 16k instead of 4k.
Towards: #409
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/720)

Optimize hashing files

---

nativelink-store/src/ac_utils.rs
nativelink-store/src/fast_slow_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/noop_store.rs
nativelink-store/tests/ac_utils_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/store_trait.rs
nativelink-worker/src/running_actions_manager.rs

When using nativelink with a local worker/CAS setup, adds optimizations which make it faster to upload files from the worker to the CAS.
This is specifically useful for Buck2 for users that want to build hermetically.
closes: #409
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/723)

Optimize file uploads when source is file

---

nativelink-config/examples/README.md

This PR is the beginning of more work to breakdown in a step-by-step fashion how to configure a NativeLink deployment. 
Beginning of addressing #681  
Documentation
WIP
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/680)

Document a Breakdown of Configuration

---

nativelink-docs/docs/About.mdx
nativelink-docs/docs/Configuration.mdx
nativelink-docs/docs/Contributing.mdx
nativelink-docs/docs/Quickstart.mdx

Adds a page to list out all configuration options to aid in customization. Can be viewed by running `yarn start` in `/nativelink-docs` folder and going to the `Configuration` page.
Fixes #724 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/725)
Preview Deployment: https://nativelink-docs-git-fork-blakehat-0da362-native-link-web-assets.vercel.app/Configuration

Add configuration breakdown page

---

Cargo.toml
flake.nix

The Cargo build now raises an error if the Rust version doesn't match.
Fixes a bug where the flake version wasn't in sync with the Bazel build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/734)

Set `rust-version`

---

nativelink-util/src/resource_info.rs

Prints out what was supplied by the user if a failure happens when parsing out the resource info string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/742)

Improve the error message in resource info parsing failure

---

nativelink-store/src/fast_slow_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/digest_hasher.rs
nativelink-util/src/fs.rs
nativelink-util/src/store_trait.rs
nativelink-worker/src/running_actions_manager.rs

Refactor fs.rs to use call_with_permit scheme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/741)

Refactor fs.rs to use call_with_permit scheme

---

nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Changes the running action manager to check the owner and group executable permissions of artifacts instead of just others. Prevents files from losing executable status when being copied from the worker to the CAS.
Fixes #675
This includes a regression test for losing executable permission when copying from worker to CAS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/727)

check owner and group executable bits

---

BUILD.bazel
Cargo.lock
Cargo.toml
flake.nix
src/bin/nativelink.rs

This should make allocation behavior more consistent across different builds and reduce memory fragmentation issues.
The allocation behavior of the `nativelink` executable is now configurable with `MIMALLOC_*` environment variables as described here:
https://microsoft.github.io/mimalloc/environment.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/749)

Use mimalloc as global memory allocator

---

.bazelignore

When building with //..., bazel will traverse down .direnv, which contains symlinks to the main source tree, so everything gets built twice.
Without this change:
```
➜  nativelink git:(a651f2c) bazel query //... | grep direnv
Loading: 0 packages loaded
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source:dummy_test
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source:dummy_test_sh
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source:nativelink
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source/local-remote-execution/examples:hello_lre
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source/local-remote-execution/generated/cc:cc-compiler-armeabi-v7a
//.direnv/flake-inputs/d7skygm91pd5xj8q368y063ss7fhys3a-source/local-remote-execution/generate …
```

Ignore .direnv for bazel builds

---

.github/workflows/native-bazel.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/sanitizers.yaml

This should fix remaining outdated node versions in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/760)

Migrate Bazelisk actions to new variant

---

nativelink-store/src/completeness_checking_store.rs
nativelink-store/tests/completeness_checking_store_test.rs

REv2 does not require clients to upload directory digests. Instead they are only required to upload the tree root which has all the directories in it.
closes #747
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/748)

Completeness checking store should not check if directory digests exist

---

deployment-examples/kubernetes/.gitignore

The worker files have been renamed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/788)

Fix `.gitignore` after 1a43ef9

---

tools/pre-commit-hooks.nix

This hook triggers on all non-excluded binary files.
Should prevent issues like #791 in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/792)

Forbid binary files in commits

---

.github/workflows/image.yaml
.gitignore
flake.nix
tools/create-worker.nix
tools/local-image-test.nix
tools/publish-ghcr.nix

This should make it easier to spin up test instances for C++ projects. The nativelink worker image may now be fetched from:
```
ghcr.io/tracemachina/nativelink-worker-lre-cc:<sometag>
```
Since the toolchain images are somewhat more complex than the minimal `nativelink` image, we now use trivy to scan images for vulnerabilities. The database for these scans is fetched dynamically. This breaks perfect reproducibility for the image publishing workflow when rolling back/reverting, but ensures that new commits aren't checked against outdated vulnerability databases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/794)

Publish nativelink-worker image for C++

---

README.md

The documentation says it supports Bazel 6.4.0+, but the project actually supports bazel 7.0.2+.
I think the documentation needs to be updated.
Here's the bazel version talking in the documenation.
https://github.com/TraceMachina/nativelink/blob/646253dec285868263ce77b60c26c9e69daaf1ae/README.md?plain=1#L114
Here's the actual bazel version supported from the `.bazelversion` file.
https://github.com/TraceMachina/nativelink/blob/646253dec285868263ce77b60c26c9e69daaf1ae/.bazelversion#L1
Fixes #800 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/801)

Fix incorrect bazel version 6.4.0+ in documenation

---

nativelink-config/src/cas_server.rs
nativelink-config/src/serde_utils.rs

This lets us use a combination of init-contaiers and entrypoint scripts to pass dynamic container image tags and other values into workers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/809)

Allow variables in platform property values

---

nativelink-service/tests/bytestream_server_test.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/proto_stream_utils.rs
nativelink-worker/src/running_actions_manager.rs

Implements suggested performance refactors and prevents future clippy warnings.
Using clippy for the nightly rust toolchain is currently showing warnings in a number of spots. This implements the suggested changes so that all builds will not suddenly start failing if the toolchain version used by precommit-hooks is updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/817)

Fix nightly clippy warnings

---

nativelink-scheduler/src/simple_scheduler.rs

Refactor scheduler to use a single struct for state management of all incomplete actions. Removes `RunningAction` entirely and adds an optional `worker_id` field to `AwaitedAction`
closes: #781
All existing tests pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/782)

Unify RunningAction and AwaitedAction

---

flake.nix

Adding a nix target that allows for enabling console or other features as needed for debugging nativelink images. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/811)

Nix: Add nativelink-debug target

---

nativelink-config/src/cas_server.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Modifies running actions manager and workers to create an action directory with a dedicated work directory inside instead of just creating a work directory for the task. Other directories can be mounted to this space and will be automatically cleaned on completion.
Added a test to ensure that any temporary resources in the directory are cleaned on action completion
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/752)

Create directory for action

---

nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

We get the metadata for a file after opening it, which causes two file descriptors to be used rather than one.  In order to ensure that every future requires exactly one file descriptor at a time and therefore not cause a deadlock in the OPEN FILE Semaphore, we simply get the metadata before we open the file.
Fixes #808 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/816)

Resolve upload deadlock

---

.github/workflows/main.yml
deployment-examples/docker-compose/README.md
flake.nix
run_integration_tests.sh

Bump some of the workflows and change the legacy `docker-compose` command to the new `docker compose`.
Fixes #828
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/829)

Update docker workflows

---

nativelink-config/src/schedulers.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs

We have duplicated work in `CacheLookupScheduler` and `CompletenessCheckingStore`.
To resolve this, I removed the validation logic in `CacheLookupScheduler` and instead make it have `CompletenessCheckingStore` always.
Fixes #677 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/826)

Unify `validate_output` logic in `CompletenessCheckingStore` and `CacheLookupScheduler`

---

Cargo.lock

See https://seanmonstar.com/blog/hyper-http2-continuation-flood/ for further information.
Fixes GHSA-q6cp-qfwq-4gcv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/835)

Update h2 to 0.3.26

---

Cargo.toml
MODULE.bazel
flake.nix

- rules_rust: 0.40.0 -> 0.41.1
- rust-stable: 1.76 -> 1.77
- rust-nightly: 2024-03-01 -> 2024-04-03
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/837)

Bump Rust toolchains

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-worker/BUILD.bazel
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

Implements worker api for requesting a currently running action to be killed. Allows for action cancellation requests to be sent from the scheduler during scenarios such as client disconnection.
towards: #338
Added a new test case to confirm that the request to kill an action is received and handled accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/840)

Implement worker api for killing running actions

---

nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Backport of running actions manager timeout changes which checks the timeout for an action and defaults to a maximum if not set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/743)

Add safe request timeout for running actions manager

---

nativelink-service/src/bytestream_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/ac_utils.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/ac_utils_test.rs
nativelink-store/tests/completeness_checking_store_test.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/dedup_store_test.rs
nativelink-store/tests/existence_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/memory_store_test.rs
nativelink-store/tests/ref_store_test.rs
nativelink-store/tests/s3_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-store/tests/size_partitioning_store_test.rs
nativelink-util/src/buf_channel.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/buf_channel_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

This is to remove some of the confusion of what .take() can mean. In rust .take() often is used to denote "taking ownership" but can also mean "take data". To remove any ambiguity it's renamed .consume() to ensure the user either knows what the api does or has to look it up.
Also removes .collect_all_with_size_hint() and replaces with
.consume()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/848)

Rename buf_channel::take() to buf_channel::consume()

---

nativelink-service/src/bytestream_server.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/fast_slow_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/src/verify_store.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/buf_channel.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/buf_channel_test.rs

Major rewrite of how DropCloserReadHalf and DropCloserWriteHalf.
* Simplified DropCloserReadHalf::consume()
* DropCloserWriteHalf will no longer wait for eof to be received
* Added utility func DropCloserWriteHalf::bind()
* DropCloserReadHalf can now be configured to hold a queue of recent data to aid with places that might need retry.
* EOF signal is now an AtomicBool instead of a tokio::once channel.
* DropCloserReadHalf::try_reset_stream added to put queue back onto head of stream if able.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/849)

Refactor buf_channel

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
deployment-examples/kubernetes/README.md

Updated deployment-examples/kubernetes/README.md for more context around tagging, building, and running images.
The original question for this improvement popped up here: https://nativelink.slack.com/archives/C066XC8JT0X/p1711386866760809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/846)

Updated Kubernetes Readme for more information about using docker images

---

nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/buf_channel.rs
nativelink-util/tests/buf_channel_test.rs

In the event the receiver is receiving the exact size of data, but the writer sends all the data, but not an eof then the writer decides not to send the eof the receiver will consider it "good". This issue has been fixed by this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/858)

Fix bug in buf_channel::consume() where exact size doesn't receive eof

---

README.md

The specific version must be pinned for now. IN the future, we could expand the CI to test multiple versions if that's helpful for users.
A community user attempted to build from source and encountered this bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/873)

Update README.md to pin version

---

.bazelrc
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/nix.yaml
MODULE.bazel

The zig-cc toolchain blocks updating the `cc` crate, which in turn blocks updating a bunch of other crates. We originally had it for backwards compatibility on older systems. Now that NativeLink's production builds are statically linked against musl this build has become obsolete.
Closes #694
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/876)

Remove zig-cc

---

nativelink-store/src/size_partitioning_store.rs

SizePartitioningStore now properly publishes metrics about the underlying store and config.
towards: #650
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/880)

Add metrics output to SizePartitioningStore

---

nativelink-store/src/verify_store.rs

Metrics of underlying VerifyStore are now forwarded for metrics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/897)

Add backend store metrics to VerifyStore

---

.bazelrc
flake.nix

The `--incompatible_sandbox_hermetic_tmp` flag doesn't work when `TMPDIR` or `TMP` are set to a location under `/tmp`. Nix shells set these environment variables to `/tmp/nix-shell.xxxxxx`, triggering mount errors. This change enables the flag by wrapping Bazel in the Nix shell with a script that unsets the `TMP` and `TMPDIR` environment variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/902)

Enable hermetic Bazel sandboxing

---

README.md

I removed an unnecessary "an" in "Example Deployments" and changed the copyright date to "2020-2024" (from 2023).
- [ x] Bug fix (non-breaking change which fixes an issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/903)

Update README.md (small edits)

---

deployment-examples/chromium/01_operations.sh
deployment-examples/kubernetes/01_operations.sh

The `curl` commands we send to Tekton can take longer to evaluate than it takes for bash to continue to the `kubectl wait` section.
In CI it's most likely not an issue if the `kubectl wait` fails since the `02_*` scripts will retry (and wait) until the pipelines succeed.
However, for manual invocations and examples it can be confusion if these scripts print error messages about non-existing pipelines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/906)

Fix operations scripts evaluating to quickly

---

nativelink-service/src/cas_server.rs
nativelink-service/tests/cas_server_test.rs

I handled get_tree() GRPC request in the CAS Server. Used FIFO(First-In-First-Out) traversal method ( BFS Algorithm ) to loop over directories using `VecDeque` data structure. Paging is supported and `page_token` in `GetTreeRequest` is used to point the directory to start traversing with. And `next_page_token` in `GetTreeResponse` refers the `page_token` parameter which will be used in the next request.
Fixes #355 
Still not tested yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/905)

Implement get_tree() feature

---

README.md

Currently, in `README.md`, the tag version is still `v0.3.0` even though we already upgraded it to `v0.4.0` recently.
https://github.com/TraceMachina/nativelink/blob/75105df746c626da76f74e412764e6755296a8ab/README.md?plain=1#L33
Fixes #922 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/923)

Update old tag version in `README.md`

---

nativelink-store/src/existence_cache_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/memory_store.rs
nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs

In prep to move to an abstract key instead of DigestInfo, this change cleans up EvictingMap and removes dependencies on DigestInfo.
towards: #931
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/932)

Refactor EvictingMap so it does not use DigestInfo

---

Cargo.lock
deployment-examples/docker-compose/Dockerfile
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/action_messages_test.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/action_messages.rs

Changes the field used for identifying which action an ActionState corresponds to include a uuid as well as the ActionInfoHashKey. All existing functionality is kept the same by making use of the nested ActionInfoHashKey contained within the Id. These changes will provide the basis for all usage of Id in followup changes to the scheduler.  This breaks compatibility for forwarding an operation from one remote execution system to another that does not use our operation name format (ie: very unlikely, but possible).
All existing tests have been modified to remain functionally equivalent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachin …

Include UUID in ActionState

---

tools/nixpkgs_disable_ratehammering_pulumi_tests.diff

On MacOS the pulumi testsuite hit the ratelimiting on github. Disable the pulumi tests with a patch on nixpkgs.
Commit 0eed7593b1a55ed9998569764080ea2c1b3406a4 didn't fix this issue.
Tested with nix flake on MacOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/953)

Fix pulumi ratelimiting build error

---

nativelink-scheduler/src/property_modifier_scheduler.rs

Fixes metrics being lost due to the underlying ActionScheduler not having it's metrics passed through the PropertyModifierScheduler. This should fix any scaling issues related to queued actions metrics not being available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/954)

Register metrics on PropertyModifierScheduler

---

nativelink-service/src/cas_server.rs

Nightly clippy reports a style issue when using double quotes around a
single char.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/955)

Use single quotes for char

---

.github/workflows/pre-commit.yaml

The original setting of 5 minutes was a bit too flaky. Increase it to 10 minutes so that cache misses don't break the job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/956)

Increase pre-commit timeout in CI

---

Cargo.lock
nativelink-error/BUILD.bazel
nativelink-error/Cargo.toml
nativelink-error/src/lib.rs
nativelink-scheduler/src/operation_state_manager.rs

Adds the ability to convert a RedisError into a Nativelink Error. This will dramatically simplifies error handling when dealing with errors returned by the new redis backend for the scheduler.
Compiler accepts conversion into nativelink_error::Error from RedisError::into
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/959)

Convert RedisError into nativelink Error

---

Cargo.toml

Adds a dev build profile that disables lto and optimizations for faster compilation times. Changes CI preferred build profile to inherit from dev profile and overrides it to strip all symbol and debuginfo, optimize for binary size, turn off loop vectorization and debuginfo generation.
Fixes All the Failing precommit checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/976)

Add dev build profile and remove lto from CI

---

nativelink-scheduler/src/simple_scheduler.rs
nativelink-service/tests/worker_api_server_test.rs

Being able to hold a lock over async code requires the use of `async_lock` over `parking_lot`, migrating `Mutex` & `MutexGuard` to that package. In addition updating function signatures to `async` for better fitting of API updates for new scheduler.
Fixes # (https://github.com/TraceMachina/nativelink/issues/979)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/971)

Refactor simple scheduler method signatures to async

---

.github/workflows/vale.yaml

This PR helps us to avoid running into the issue described in
<https://github.com/reviewdog/reviewdog/issues/1696>, where diffs that
are too large will cause Vale to fail
The diff between the versions of Vale and the new one can be viewed
[here](https://github.com/errata-ai/vale-action/compare/c99f2d..91ac40).
Since they also allow you to specify which version of reviewdog to use,
we'll use the most recent one which includes all the changes made so far
that are supposed to fix the issue with large diffs.
It hasn't, but we'll see how it runs on this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/978)

Update `Vale` CI action to handle large diffs

---

nativelink-scheduler/src/operation_state_manager.rs

Adjustment to operation state manager api to include a order by field.
Fixes # https://github.com/TraceMachina/nativelink/issues/983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/969)

Add OrderBy field for OperationFilter

---

nativelink-config/src/stores.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

Add a configuration option that allows for setting an optional prefix to all the keys used with a Redis store. I added some documentation to the `RedisStore` configuration struct, but I'm not sure if there's docs I should update elsewhere.
Fixes #977
I added duplicates of existing tests of the Redis store to use prefixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/981)

Add a config option to prefix keys in Redis stores

---

BUILD.bazel
CONTRIBUTING.md
flake.nix
nativelink-config/BUILD.bazel
nativelink-config/src/lib.rs
nativelink-config/src/serde_utils.rs
nativelink-error/BUILD.bazel
nativelink-macro/BUILD.bazel
nativelink-macro/Cargo.toml
nativelink-proto/BUILD.bazel
nativelink-proto/build/bazel/remote/execution/v2/remote_execution.proto
nativelink-proto/genproto/build.bazel.remote.execution.v2.pb.rs
nativelink-proto/genproto/google.api.pb.rs
nativelink-proto/google/api/http.proto
nativelink-scheduler/BUILD.bazel
nativelink-service/BUILD.bazel
nativelink-store/BUILD.bazel
nativelink-util/BUILD.bazel
nativelink-worker/BUILD.bazel
tools/docs.nix

This commit adds a new `docs` command to the flake which can be used to build rustdocs. The setup is compatible with Cargo and Bazel.
Docs may also be tested via `bazel test docs`.
This commit doesn't publish the docs and doesn't fully surface all configuration. It provides some basic infrastructure as a starting point for future enhancments to autogenerated documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/980)

Introduce basic rustdoc infrastructure

---

.github/workflows/lre.yaml
Cargo.lock
deployment-examples/chromium/01_operations.sh
deployment-examples/kubernetes/01_operations.sh
flake.nix
local-remote-execution/README.md
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/default_store_key_subscribe.rs
nativelink-util/src/lib.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/default_store_key_subscribe_test.rs

This adds the basic subscribe to the Store API that allows users to subscribe to individual keys and listen for when they change. The default store subscribe implementation will poll every 10 seconds for changes. Future PRs will be landed to specialize specific stores to make it optimized for stores that support a more optimized way to subscribe (like redis or memory).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/924)

Add subscribe API to Store API

---

Cargo.lock
nativelink-error/BUILD.bazel
nativelink-error/Cargo.toml
nativelink-error/src/lib.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/digest_hasher.rs
nativelink-util/src/platform_properties.rs

Make nativelink structs serializable and deserializable
Adds Serialize and Deserialize to most of the Proto wrapper
structs in order to support store and retrieval from Redis.
N/A
- [n/a] Tests added/amended
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/965)

Add serialize and deserialize to structs

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/worker.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/worker_api_server_test.rs
src/bin/nativelink.rs

`action_messages::WorkerId` uses `Uuid` as the internal tagging structure for new trait interfaces, removing the older structure `worker::WorkerId` that uses `u128`.
Fixes https://github.com/nativelink/nativelink/issues/991
`bazel test //... && cargo test --all`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nativelink/nativelink/992)

[refactor] Migrate `worker::WorkerId` for `action_messages::WorkerId`

---

.github/workflows/main.yml

The main branch will now run on nativelink.com's CI in addition to other tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1007)

Add CI test to run on nativelink.com

---

nativelink-util/src/evicting_map.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/evicting_map_test.rs

In prep to support the list operation in the store-api, we move the EvictingMap to a B-tree implementation.
This will allow us to prefix-filter items in the tree much faster than iterating everything then filtering.
towards: #995
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/996)

Move EvictingMap to B-tree

---

.github/workflows/main.yml

This was accidentally referencing a nonexistent `master` branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1008)

Enable the dotcom workflow on main

---

.github/workflows/pre-commit.yaml

This pipeline sometimes takes more than 10 mins to run due to nix cache slowness, so increase the timeout some.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1009)

Increase timeout of pre-commit-checks CI pipeline

---

nativelink-store/src/completeness_checking_store.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/existence_cache_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/noop_store.rs
nativelink-store/src/redis_store.rs
nativelink-store/src/ref_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/src/shard_store.rs
nativelink-store/src/size_partitioning_store.rs
nativelink-store/src/verify_store.rs
nativelink-store/tests/completeness_checking_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/ref_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-store/tests/size_partitioning_store_test.rs

We implicitly use all stores as Arc's anyway, so this PR just
makes it easier for stores to grab a Weak to self for some
specific cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/989)

[Refactor] Stores now return Arc for construction

---

nativelink-store/src/memory_store.rs
nativelink-store/tests/memory_store_test.rs
nativelink-util/src/evicting_map.rs
nativelink-util/src/store_trait.rs

Adds the list() api to all stores, but unimplemented by default.
Implements list() api for MemoryStore.
towards: #995
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1003)

Add list api to StoreApi and MemoryStore

---

.github/workflows/nix.yaml
flake.nix
tools/nativelink-is-executable-test.nix

The flake.nix uses the default crane toolchain on darwin. Override the default crane toolchain and specify 
the target to use the correct rust toolchain.
Fixes #948
Invoke nix build on MacOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/974)

Fix Cargo mismatch on MacOS build

---

Cargo.toml

This was fixed in: 591126d6531f36a5365cbedfe1c6f165a14b0ab6.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1011)

Sync Cargo MSRV to Bazel

---

flake.nix

This test requires building `nativelink`. When `nativelink` is cached, this isn't noticeable, but when changing the Rust sources this causes long wait times for flake reloads. Remove it from the devShell to prevent such rebuilds. The test is still runnable and tested in CI via `nix run .#nativelink-is-executable-test`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1014)

Remove installation test from devShell

---

nativelink-service/src/execution_server.rs
nativelink-util/BUILD.bazel
nativelink-util/src/action_messages.rs
nativelink-util/tests/operation_id_tests.rs

Execution server was leaking out `ActionInfoHashKey`, remove leakage and ensure `OperationId` is used for external communications.
Added tests around both `OperationId` and `ActionInfoHashKey` parsing.
Fixes https://github.com/TraceMachina/nativelink/issues/1000
Added new tests around key encoding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1001)

[bug] Ensure OperationId is used at external protocol points

---

.gitignore
CONTRIBUTING.md
MODULE.bazel

rust-analyzer can parse Cargo.toml files or rust-project.json files to
generate context about the projects it's run on. rust-project.json files
are a format intended to be generated by build tools other than Cargo,
such as Bazel. With this setup we can tell rust-analyzer to build the
project with Bazel instead of Cargo.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1019)

Add Bazel rules for generating rust-project.json

---

Cargo.lock
nativelink-config/src/stores.rs
nativelink-store/Cargo.toml
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

This PR brings support for using Redis in cluster mode as a store.
Fixes #869
Notably, no new tests have been added. Since we currently use a mock to test our redis support, we don't have infrastructure in place to test against a live redis cluster.
I'd like to add some tests that spin up a redis cluster and assert that everything works ok in cluster mode, but it's a non-trivial amount of work. I'd like for them to run using the rust test harness, so likely that'd mean grouping them under a cargo feature (like, "slow-tests") and using testcontainers to create a redis cluster.
- - - …

Support cluster mode when using Redis as a store

---

.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/tagged_image.yaml
deployment-examples/chromium/01_operations.sh
deployment-examples/chromium/02_application.sh
deployment-examples/chromium/03_build_chrome_tests.sh
deployment-examples/chromium/04_delete_application.sh
deployment-examples/chromium/worker-chromium.yaml
deployment-examples/kubernetes/01_operations.sh
deployment-examples/kubernetes/02_application.sh
deployment-examples/kubernetes/03_delete_application.sh
deployment-examples/kubernetes/worker-lre-cc.yaml
flake.nix
tools/create-worker.nix
tools/nativelink-worker-init.nix

Changes to `nativelink` no longer require rebuilding toolchain containers and vice versa.
The `nativelink` executable has been removed from the `createWorker` function. Instead, users should mount the `nativelink` executable into a toolchain container during deployment. This makes deployments more generic and provides out-of-the-box compatibility with any arbitrary toolchain container.
Introduce a new `nativelink-worker-init` image, a thin wrapper around the `nativelink` container that copies the bundled `nativelink` executable to specified location. This can be used in worker deployments to populate temporary volumes with the `nativelink` executable. The new setup significantly improves setup times (observerd 90%+) for LRE-style deployments as workflows can fetch the `nativelink-init` …

Decouple nativelink from toolchain containers

---

nativelink-config/Cargo.toml

Upon rebasing https://github.com/TraceMachina/nativelink/pull/891, I realized that I accidentally dropped the Serde version. This PR restores it (unless that breaks something). 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/966)

bump serde to more current version

---

nativelink-scheduler/src/operation_state_manager.rs
nativelink-scheduler/src/scheduler_state/metrics.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/worker_api_server.rs

Implement WorkerStateManager for simple scheduler
Implementation of `WorkerStateManager` where the beginnings of being able to
tuck mutations behind a trait for `StateManager`. `StateManager` now wraps
the `StateManagerImpl` for inner state structure `StateManagerImpl`.
All mutations should be done on a lock on `inner` in the future.
Moving implementation code of `update_action` into `WorkerStateManager` trait.
Fixes https://github.com/nativelink/nativelink/issues/994
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/993)

Implementation of WorkerStateManager

---

nativelink-scheduler/src/scheduler_state/metrics.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/worker_api_server.rs

`worker_api_server.rs::WorkerApiServer::inner_execution_response` contains the failure case/flow for `action_stage: Result<ActionStage, Error>` in `WorkerStageManager::update_operation`.
As of now that implementation is not handled when let `action_stage = action_stage.expect("Unimplemented error in update_operation()");` is evaluated.
This ticket represents the need to refactor and consolidate that implementation into a single code path of update_action/update_operation.
Fixes https://github.com/TraceMachina/nativelink/issues/1054
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1053)

Move `update_action_with_internal_error` into `StateManager`

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/operation_state_manager.rs
nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs
nativelink-scheduler/src/scheduler_state/metrics.rs
nativelink-scheduler/src/scheduler_state/mod.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-scheduler/src/simple_scheduler.rs

Implement MatchingEngineStateManager
Implement `MatchingEngineStateManager` for `StateManager`. This hides implementation
logic for `do_try_match()` behind `MatchingEngineStateManager` on `filter_operations` and
`update_operation`. `tasks_or_workers_change_notify` has been moved into the `StateManager`.
Fixes https://github.com/TraceMachina/nativelink/issues/1043
```
bazel test //...
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1041)

Implement MatchingEngineStateManager

---

.github/workflows/lre.yaml
deployment-examples/kubernetes/worker-lre-cc.yaml
deployment-examples/kubernetes/worker-lre-java.yaml
native-cli/components/embedded/nix2container-copyto.yaml
native-cli/components/embedded/nix2container-image-info.yaml

The failures were caused by "ambiguous directory permission" errors from git. Locally this was hard to notice because local permissions might've been different and the infra is set up in a way that it reuses previous images.
Long-term we should implement a proper mechanism to make the git repo available to cluster-internal Tekton steps.
Fixes #986
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1058)

Unbreak LRE Remote workflow

---

Cargo.lock
nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/default_store_key_subscribe.rs
nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs
nativelink-worker/Cargo.toml
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/src/worker_api_client_wrapper.rs
nativelink-worker/tests/utils/local_worker_test_utils.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

`async fn` and `-> impl Trait` is stable in traits. This uses it wherever possible. Due to trait bound requirements, all converted functions need `-> impl Future + Send`.
Due to compiler limitations, namely `dyn Trait` compatibility, it is not possible at this time to convert the remaining uses without creating concrete types and implementing `Future` by hand.
Fixes #620
Code simplification
`cargo check` passes as expected; `bazel test //...` succeeds as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1055)

Remove `#[async_trait]` where possible

---

nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/simple_scheduler.rs

Removed unused test method and relocated notify function in `add_action`.
Fixes https://github.com/TraceMachina/nativelink/issues/1059
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1060)

Reduce references to self.state_manager.inner

---

nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs

Refactoring to include the `awaited_action` watch channel `notify_channel: watch::Sender<Arc<ActionState>>` to be provided via `MatchingEngineActionStateResult`. This aids the matching engine's need for access to `OperationId`.
Fixes https://github.com/TraceMachina/nativelink/issues/1063
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1064)

Include ActionState to MatchingEngineActionStateResult

---

README.md
docs/scripts/md_to_mdx.ts

Reverts TraceMachina/nativelink#1074
The bracket change broke the docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1080)

Revert "Improve README branding and links"

---

nativelink-config/src/cas_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/tests/bytestream_server_test.rs

I can imagine there are lots of use cases "where a simple rule can generate lots of stdout." @ltekieli pointed out this issue and shared a patch for how it could be fixed. I copied it and added a test to ensure that the configured limit is enforced.  
I may need to figure out how to document this change better. Please advise. 
Fixes #1070 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1076)

Make bytestream limits configurable

---

nativelink-config/src/cas_server.rs

Removes a TODO from our docs. 
Fixes #1084 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1085)

Fixed the docs and removed errant TODO

---

.github/workflows/codeql.yaml
.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/sanitizers.yaml
.github/workflows/scorecard.yaml
.github/workflows/tagged_image.yaml
.github/workflows/vale.yaml

When a new push happens on a PR in github it will cancel the previous workflows. This will free up more resources for other PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1090)

Github actions will now cancel existing workflows on push

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/action_scheduler.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_action_listener.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/lib.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-service/src/execution_server.rs

This will enable the underlying scheduler to intercept the Drop call allowing easier cleanups of actively listened actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1091)

ActionScheduler will now use ActionListener instead of tokio::watch

---

native-cli/components/embedded/envoy.template.yaml

Some dashboards like Capacitor require this to properly stream Logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1098)

Allow WebSocket upgrades in devcluster Loadbalancer

---

nativelink-scheduler/src/action_scheduler.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_action_listener.rs
nativelink-scheduler/src/scheduler_state/client_action_state_result.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/execution_server.rs

ActionStateResult is now wired up to ActionListener allowing it to be notified of Drop calls. This will be used to do client operation id cleanups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1093)

StateManager can now be notified of noone listeneing

---

nativelink-config/examples/filesystem_cas.json

Filesystem cas was broken by a change in the naming scheme for `hash_verification_function`
Fixes #1110 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1111)

Fix filesystem_cas.json

---

deployment-examples/chromium/01_operations.sh
deployment-examples/kubernetes/01_operations.sh
native-cli/components/embedded/trigger.yaml

The `eventMetadata` field in Flux Alerts is of the form:
```yaml
eventMetadata:
key: value
```
When such an Alert triggers, the corresponding Provider will send a JSON like `{"metadata": {"key": "value"}}` to the Provider's address. This commit makes the Tekton Eventlistener compatible with this pattern.
Part of preparations for the NativeLink operator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1094)

Allow Tekton pipelines to be triggered by Flux Alerts

---

native-cli/components/embedded/kustomization.yaml
native-cli/components/embedded/rebuild-nativelink.yaml
native-cli/components/embedded/trigger.yaml
native-cli/components/embedded/update-image-tags.yaml

This allows watching the `nativelink-image-tags` configmap to detect changes to the images running in the cluster.
Preparation for the NativeLink operator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1100)

Write Tekton image tag outputs to a ConfigMap

---

nativelink-scheduler/src/action_scheduler.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/client_action_state_result.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-util/src/action_messages.rs

StateManager will now properly remove items from the maps if the client disconnects after a set amount of time. Currently these values are hard codded, but will be easy to transition them to use config variables once we design it out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1107)

StateManager will now cleanup actions on client disconnect

---

native-cli/components/embedded/capacitor.yaml
native-cli/components/embedded/kustomization.yaml
native-cli/components/embedded/nativelink-gateways.yaml
native-cli/components/embedded/nativelink-routes.yaml
native-cli/components/loadbalancer.go
native-cli/programs/local.go

This lets us view logs and deployment statuses of Kustomizations.
The new dashboard is available via `localhost:9000`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1115)

Add Capacitor dashboard to devcluster

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/tests/local_worker_test.rs

Removes unused proto field in worker api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1117)

Remove unused proto field

---

nativelink-scheduler/src/operation_state_manager.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs

We don't actually need this API, since the StateManager can now own the output struct, which means it controls the Drop function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1119)

Remove MatchingEngineStateManager::remove_operation

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/scheduler_state/client_action_state_result.rs

Remove missing src from BUILD file and format so bazel test passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1123)

Fix bazel build and test on dev

---

.github/workflows/main.yml

Adds BEP to CI workflow using shared Trace Machina account BEP headers associated with it's shared CAS from the quickstart.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1124)

Add BEP to CI

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

Workers should only talk OperationId.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1125)

Remove all need for workers to know about ActionId

---

nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/operation_state_manager.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/completed_action.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/worker.rs
nativelink-scheduler/tests/action_messages_test.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/execution_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-util/src/action_messages.rs
nativelink-util/tests/operation_id_tests.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

We no longer need `salt` as part of the action key, because we now put the key as an value in an enum in ActionUniqueQualifier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1126)

Remove all uses of salt and put under ActionUniqueQualifier

---

nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs

Instead of using Weak references and custom spawns, we now use
a channel to notify receivers that cleanups are needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1130)

ClientAwaitedAction now uses a channel to notify drops happened

---

nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs
nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-worker/src/running_actions_manager.rs

We no longer drop errors in subscription handling.
Also cleanup some small todo!'s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1135)

Errors are now properly handled in subscription

---

nativelink-util/src/action_messages.rs
nativelink-util/tests/operation_id_tests.rs

Instead of `0` and `1` if something is cachable we use `c` and `u`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1136)

Change encoding for items that are cachable

---

nativelink-config/src/schedulers.rs
nativelink-scheduler/src/simple_scheduler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1137)

SimpleScheduler now uses config for action pruning

---

docs/astro.config.mjs

Turns out I added this already and it just didn't work because of a typo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1133)

Fix overflowing mermaid diagrams in docs

---

.github/workflows/main.yml

Changes using the url variables for the NativeLink Cloud from secrets to vars
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1143)

Change remote cache URLs from secrets to vars

---

.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/sanitizers.yaml

This is a bit risky and we might want to reenable some of these, but let's see how this goes. Reasoning for the disabled workflows:
- `main.yaml`: This is independent of docs
- `native-bazel.yaml`: Dev-only workflow and covered by nix workflows.
- `native-cargo.yaml`: Dev-only workflow and covered by nix workflows.
- `sanitizers.yaml`: Independent of the docs.
This change deliberately doesn't touch the Nix workflows as parts of the development tooling used by doc workflows relies on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1148)

Disable some workflows on PRs that only change docs

---

nativelink-util/Cargo.toml
nativelink-util/src/lib.rs

`NL_LOG` envionment variable is used to control the logging format that `tracing_subscriber` emits out. We currently want to allow for better ingestion of formatted logs in json.
`NL_LOG` can be configured with `pretty`, `json`, or `compact`. See [Format](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html) for more detail on console logging format configurations for tracing_subscriber.
Fixes https://github.com/TraceMachina/nativelink/issues/1153
Run from console to see the different log formats
**Default**
```
$ cargo run --bin nativelink -- nativelink-config/examples/basic_cas.json
Running `target/debug/nativelink nativelink-config/examples/basic_cas.json`
2024-07-13T05:38:08.874357Z  WARN nativelink: …
```

Introduce NL_LOG to control logging format

---

Cargo.lock
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/task.rs
src/bin/nativelink.rs

Instead of custom-managing a pool of futures we now spawn tasks directly. This simplifies task handling significantly and enables migration to hyper 1.x which wasn't compatible with the old TaskExecutor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1159)

Make TaskExecutor a wrapper around TokioExecutor

---

nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1163)

Add awaited action versions

---

nativelink-scheduler/src/awaited_action_db/awaited_action.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1166)

AwaitedActionSortKey now a u64

---

nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-util/src/operation_state_manager.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1171)

Add scheduler metrics back

---

CONTRIBUTING.md
nativelink-config/src/schedulers.rs
nativelink-service/src/bytestream_server.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/fastcdc.rs
nativelink-util/src/resource_info.rs

There are typos of misusing `it's` instead of `its` in the documentation and comments. Those typos can be found in the contribution documentation file and code comments of this project. No more typos like this exist after this commit.
More details can be found in the issue link below.
Fixes #1173 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1174)

Fix typos in the documentation and comments

---

nativelink-store/src/s3_store.rs
nativelink-util/src/buf_channel.rs
nativelink-util/tests/buf_channel_test.rs

Fixes an upload bug where it blindly accepts data without receiving EOF.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1178)

Fix bug in S3 where it ignores EOF

---

nativelink-store/src/verify_store.rs
nativelink-store/tests/verify_store_test.rs

VerifyStore's job is to protect corrupted data from being received. It is possible for the down-stream component to try and accept data before receiving the EOF. To keep this from being a problem, we have VeifyStore do the checks when conditions are met before sending the last chunk of data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1180)

Double protect output stream of verify store

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
docs/astro.config.mjs
docs/scripts/md_to_mdx.ts
docs/src/content/docs/nativelink-cloud/api-key.mdx

Adds a section to the docs for production grade setups for API key secrets in different CI systems, specifically github actions to start.
:::note
Will pass vale pre-commit warning level before landing
:::
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1185)

Add documentation for api key setup in github actions

---

docs/src/content/docs/nativelink-cloud/api-key.mdx

A separate sections for read-only keys has been created in the cloud API key docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1187)

Add read only key instructions to docs

---

nativelink-error/src/lib.rs
nativelink-util/src/action_messages.rs

Implements Serialize/Deserialize for ActionStage to allow for storage
and retrieval from stores such as Redis.
towards: #1182
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1186)

Implement Serialize/Deserialize for ActionStage

---

docs/astro.config.mjs
docs/src/content/docs/nativelink-cloud/api-key.mdx

Added instructions for read only keys and BEP to api key docs. Also fixed formatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1196)

Add CI focused content to api key docs

---

Cargo.lock
nativelink-config/src/stores.rs
nativelink-store/BUILD.bazel
nativelink-store/Cargo.toml
nativelink-store/src/default_store_factory.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/src/instant_wrapper.rs

This feature enables users to setup s3 buckets to evict items after some N amount of time and NativeLink will ignore items that are older than some age. As long as NatliveLink's ignore time is shorter than the eviction time (plus some buffer), clients will upload the artifact again instead of assuming it exists.
closes: #35
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1205)

S3 store can ignore `.has()` requests based on LastModified

---

nativelink-store/Cargo.toml
nativelink-store/src/existence_cache_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/tests/existence_store_test.rs
nativelink-util/src/evicting_map.rs
nativelink-util/src/instant_wrapper.rs

To protect against a case where the parent layer store has items hot in cache and those items are frequently touched, we would never actually ask the underlying store for the data. This caused a problem because the underlying store might evict our item, then our parent ExistenceCacheStore would never let go of the item causing the node to be required to shutdown to clear it up.
This was a vary rare event, because most items have `.get()` eventually called on the digest, which refreshes the underlying store object.
closes #1199
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1203)

ExistenceCacheStore now only evicts based on insert

---

.bazelrc
MODULE.bazel
nativelink-proto/BUILD.bazel
nativelink-proto/google/bytestream/bytestream.proto

This massive compile time improvement comes from a few evil platform tricks to fetch a precompiled protoc. This saves 713 compile actions.
Observed speedups for clean builds are between 20% and 50%.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1210)

Significantly reduce Bazel test time

---

BUILD.bazel

This package was already removed from Cargo.toml and should be removed from BUILD.bazel to keep in sync.
Ensured that code generation using nativelink-proto through bazel still works and exists as a target
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1209)

Remove nativelink-proto as build dependency

---

Cargo.lock
nativelink-scheduler/BUILD.bazel
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/awaited_action_db/awaited_action.rs

Makes AwaitedAction Serialize/Deserialize and adds ability to convert to
and from raw bytes. This will be used to communicate operation data to
and external data storage such as Redis through the store API.
Towards #1182
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1206)

Convert AwaitedAction to and from raw bytes

---

nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/memory_awaited_action_db.rs

Removes unnecessary sync bounds from functions inside of the
AwaitedActionDb trait. These bounds interfere with implementations while
attempting to communicate to with the redis store.
towards #1182
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1227)

Remove unnecessary sync trait bounds.

---

.github/workflows/main.yml

Docker compose on github runners appears to have been updated, so we need to use the new-er command `docker compose` instead of `docker-compose`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1238)

Fix docker-compose

---

Cargo.toml
nativelink-error/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

During the pruning of features we disabled a bit too many features and cargo would complain if compiled from the parent package, but to a sub-package because certain packages needed features enabled but only for those tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1236)

Fix Cargo.toml files when using cargo test on specific packages

---

nativelink-scheduler/src/action_scheduler.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_action_listener.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/tests/action_messages_test.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-service/src/execution_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-util/BUILD.bazel
nativelink-util/src/action_messages.rs
nativelink-util/src/operation_state_manager.rs
nativelink-util/tests/operation_id_tests.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

This is in prep to support generic layering of workers & schedulers. We can no longer know if the source is a client or just an up-stream-component, so we need to fall back to just using OperationId.
towards #1213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1214)

Remove ClientOperationId and move all to OperationId

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/action_scheduler.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/execution_server.rs
nativelink-util/src/operation_state_manager.rs

Mostly a cosmetic change to move the compatible parts of
ActionSchedulers to use ClientStateManager API instead and implement all
related requirements to existing schedulers.
towards #1213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1241)

Migrate much of the ActionScheduler API to ClientStateManager API

---

nativelink-store/Cargo.toml

Feature `rt-tokio` had been transitively dependended on, durning refactors of `Cargo.toml` files it was accidentally dropped.
Fixes https://github.com/TraceMachina/nativelink/issues/1247
Will be deployed to staging systems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1248)

[Bug] Add rt-tokio feature to aws-sdk-s3

---

Cargo.lock
nativelink-scheduler/BUILD.bazel
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/awaited_action_db/mod.rs

Implements a number of convenience implementations to simplify compatibility with fred and conversions into redis keys/values. Breakout of some changes necessary for implementing RedisAwaitedActionDb
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1243)

Conversion implementations for awaited action db structs

---

README.md

specify both ports to ensure easy setup
When I launch the docker container with just `-p 50051` then it shows up under `docker ps` as `0.0.0.0:32772->50051/tcp, :::32772->50051/tcp`, meaning I have to point my clients at `:32772` in order to use the remote cache. Using `-p 50051:50051` means the host port is fixed to 50051 too. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1255)

Update README.md for starting Docker container

---

flake.nix
native-cli/components/embedded/nix2container-copyto.yaml
native-cli/components/embedded/nix2container-image-info.yaml

This rewrites the logic for the production-grade executables and images.
The new setup allows both linux and mac systems to crosscompile
NativeLink for `x86_64-linux` and `aarch64-linux`.
The Kubernetes example and devcluster are now deployable natively on
MacOS.
Closes https://github.com/TraceMachina/nativelink/issues/751
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1233)

Crosscompile NativeLink

---

src/bin/nativelink.rs

Fix a small typo in the error message for the "experimental_bep" service inside src/bin/nativelink.rs
https://github.com/TraceMachina/nativelink/blob/7777938294047377cb4ce9f4d8649c45055596ed/src/bin/nativelink.rs#L415-L440
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1259)

Fix error message typo in `nativelink.rs`

---

deployment-examples/docker-compose/Dockerfile
integration_tests/simple_prometheus_test.sh

Recently, I found out that there were 2 typos remaining in this project.
1. Here, `my` should be `may`.
https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/deployment-examples/docker-compose/Dockerfile#L21
2. Here, the code comments for `simple_cache_test.sh` and `simple_prometheus_test.sh` are the same currently.
For `simple_prometheus_test.sh`, the comment should be changed.
https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/integration_tests/simple_cache_test.sh#L16
https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/integration_tests/simple_prometheus_test.sh#L16
Fixes #1189 
- - -
This change is [<img …

Fix typos in code comments

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/lib.rs
nativelink-scheduler/src/platform_property_manager.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/worker.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/capabilities_server.rs
nativelink-service/src/execution_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-util/BUILD.bazel
nativelink-util/src/action_messages.rs
nativelink-util/src/known_platform_property_provider.rs
nativelink-util/src/lib.rs
nativelink-util/src/operation_state_manager.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
src/bin/nativelink.rs

We want to phase out ActionScheduler in favor of ClientStateManager. In doing so, we need to have a way to let CapabilitiesServer know about platform properties; if we do this, it'd be a breaking change. Instead of causing a breaking change, we instead are going to make the provided scheduler allow the capabilities service query the optionally provided property provider interface and if it does not exist throw a warning and have it return an empty set (most RBE clients ignore this field anyway).
towards #1213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1260)

Remove ActionScheduler and introduce KnownPlatformPropertyProvider

---

flake.nix
tools/create-worker-experimental.nix

Append buck2 toolchain with additional packages
A toolchain for buck2 depends on more than llvm and rust,
appending more packages for compiling buck2 using remote
execution on nativelink. This mirrors similar to what is
used in [buck2/flake.nix](https://github.com/facebook/buck2/blob/main/flake.nix)
`create-worker-experimental.nix` now flattens out the container
image layout to a standard unix filesystem layout. Using the
nix store layout requires client knowledge of toolchains and
a similar setup as rbe gen/local remote execution which isn't
available at the moment.
Fixes  https://github.com/TraceMachina/nativelink/issues/1263
Build with nix and copy to local docker daemon. 
Run a docker shell and inspected environment.
```
nix run .#nativelink-worker-buck2-toolchain.copyToDockerDaemon …
```

Append buck2 toolchain with additional packages

---

CONTRIBUTING.md
docs/src/content/docs/contribute/nix.mdx
docs/src/content/docs/faq/lre.mdx
docs/src/content/docs/faq/remote-execution.mdx
docs/src/content/docs/introduction/contributors.mdx
local-remote-execution/README.md
nativelink-config/README.md

Relative links in markdown files produce 404 error when it's deployed on the documentation site. Reviewed all relative links in markdown files and fixed them all. This commit doesn't include any CIs to prevent from 404 errors permanently ( maybe that's what to do next from here ), but it's a hotfix for currently not available links in the documentation website which are actually hurting user experience.
Fixes #1242 
( Not a perfect fix for the issue, just a hotfix to solve the user-interfacing problems only )
It's been tested by deploying the documentation website locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink …

Fix invalid links in the documentation

---

nativelink-store/src/verify_store.rs
nativelink-store/tests/verify_store_test.rs

Fixes bug where `verify_size` & `verify_hash` are both set to true, it'd cause small messages to always fail the hash check.
fixes #1272
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1273)

Fix verify_size w/ verify_hash set to true in VerifyStore

---

nativelink-config/src/stores.rs

Fix the build warning in the docs caused by the `,ignore` flag
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1270)

Fix `docs` build warning from `nativelink-config`

---

nativelink-config/src/cas_server.rs
nativelink-config/src/schedulers.rs
nativelink-config/src/stores.rs
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/platform_property_manager.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/bep_server_test.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/grpc_store.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/dedup_store_test.rs
nativelink-store/tests/existence_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-store/tests/size_partitioning_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/digest_hasher.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/src/worker_utils.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
src/bin/nativelink.rs

Rather than using lowercase names for types, we can annotate structs and enums with `serde(rename_all = "snake_case")` to have serde rename things during de/serialization. That way, the code has Rust-style names in the source tree, but the serialized variants remain snake_cased.
`bazel test //...` passed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1271)

Make de/serialized structs compliant with Rust naming practices

---

.github/workflows/lre.yaml
.github/workflows/main.yml
tools/toolchain-nativelink/Dockerfile
tools/toolchain-nativelink/toolchain-nativelink.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1277)

Support remote build execution on main and read-only remote cache on PRs

---

.github/workflows/main.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1293)

Fix broken variables in NativeLink Cloud CI jobs and disable RBE test

---

flake.lock
flake.nix

A change in GitHub's hashing scheme caused this to evaluate differently. Add a temporary override to nix2container to unbreak CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1294)

Fix nix2container skopeo patch hash

---

.github/workflows/lre.yaml
native-cli/components/tekton.go
native-cli/programs/local.go

The `native up` command did not always finish successfully on macOS, prompting for a `pulumi refresh` instead.
By ordering the Tekton dependencies correctly in Pulumi using `dependsOn`, this issue should now be resolved.
Tested on MacOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1291)

Fix Tekton depedency order within Pulumi

---

flake.lock
flake.nix

The fix has landed upstream so this is no longer necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1296)

Remove nix2container patch hash workaround

---

nativelink-util/src/buf_channel.rs
nativelink-util/tests/buf_channel_test.rs

In a rare case if an EOF is sent, then a retry is triggered by contract an EOF needs to be sent again, but without this patch we are not allowed to send and EOF after one is already sent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1295)

Fix rare case where eof was sent on buf_channel when retry happens

---

nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/execution_server.rs
nativelink-util/src/action_messages.rs
nativelink-worker/src/local_worker.rs

Fix bug in scheduler where OperationId::String was being created instead of OperationId::Uuid when rejoining existing jobs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1301)

Fix bug where OperationId::String was being used instead of Uuid version

---

nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/worker.rs
nativelink-util/src/action_messages.rs

Adds a few more metrics and event messages to aid in debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1303)

Add more metrics & event messages

---

nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

Note: This is unlikely to have been observed from the RBE API.
We are supposed to check if an item exists even if it has zero bytes stored in it, but since redis is quite tricky to do this, we were only checking existance if it was a zero byte digest or if the length was zero bytes. In this case we might have a zero-byte proto that is actually valid that does not follow the CAS rules (hash of contents equals key).
This is in prep for a Redis Scheduler.
fixes #1286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1304)

Fix bug in redis store when zero data stored but data does not exist

---

nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs

This is mostly cosmetic to support other schedulers easier. Instead of doing a version change in the parent state manager we now do it in the underlying manager that actually owns the data.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1307)

Move where increment_version() is triggered for scheduler code

---

nativelink-config/src/schedulers.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/tests/simple_scheduler_test.rs

It is easier to do this in one PR than in two because they are dependent
on each other.
1. Moves where notifications happen in the scheduler to happen instead
in the underlying AwaitedActionDb.
2. Prepare the config changes (non-breaking).
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1306)

Prepare scheduler config & move owner of notify task change owner

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/lib.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs

In the event of a failure of version matching for scheduler owning an
operation we use Aborted error code to now signal that the version
failed and can be retried.
This is not a bug, current in-memory scheduler guarantees protections
here, this is for lockless schedulers.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1308)

SimpleScheduler version matching uses Aborted to know if failure

---

docs/README.md
docs/src/content/docs/nativelink-cloud/api-key.mdx
docs/src/content/docs/nativelink-cloud/rbe.mdx
docs/starlight.conf.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1322)

Update cloud docs for RBE and Read Only

---

nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-util/src/instant_wrapper.rs
nativelink-util/src/operation_state_manager.rs

This ensures that actions are periodically updated with with a keep
alive message, which will be heavily used with a distributed scheduling
model.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1310)

Add KeepAlive updating to ApiWorkerScheduler

---

nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/tests/action_messages_test.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/execution_server.rs
nativelink-util/src/action_messages.rs

Gives more clear separation of client_operation_id and operation_id in
AwaitedAction.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1311)

AwaitedAction's operation_id and client_operation_id now separated

---

nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/tests/simple_scheduler_test.rs

Cosmetic change to make it easier to support databases that are async in
nature. This makes all operations in the AwaitedAction API to be able to
return a result before returning a stream or other items.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1312)

Change AwaitedAction's API to always return Result<Future>

---

nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-store/src/ac_utils.rs
nativelink-util/src/action_messages.rs

In debugging Scheduler errors when developing the Redis scheduler,
adding these messages to the hints helped find the bugs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1313)

Improve debugging on some error messages

---

.github/workflows/main.yml
tools/toolchain-nativelink/Dockerfile

Fixes #1297 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1326)

Improve docker image for RBE and re-enable RBE on main

---

nativelink-service/src/bytestream_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/cas_utils.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/existence_cache_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/shard_store.rs
nativelink-store/src/size_partitioning_store.rs
nativelink-store/src/verify_store.rs
nativelink-store/tests/cas_utils_test.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/memory_store_test.rs
nativelink-store/tests/redis_store_test.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/common.rs
nativelink-util/src/digest_hasher.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/proto_stream_utils_test.rs
nativelink-worker/src/running_actions_manager.rs

It is weird that we use i64 in the code base for this in the first place. There is some historical reason for having it this way, specifically around keeping it in sync with the Digest proto, but once converted we don't need to do this.
Also implement a more standard format/display function for DigestInfo using the common '{hash}-{size}' format.
Removes direct access to modify the internals of DigestInfo and requires member access to go through accessors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1327)

Cleanup digest function to use u64 instead of i64

---

.github/workflows/docs.yaml
.github/workflows/native-bazel.yaml
.github/workflows/nix.yaml

Reduce out of disk space errors on Mac runners by deleting `~/Applications/*` and iOS Simulators/cache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1334)

Delete ~/Applications and iOS simulators/cache from Mac runners

---

Cargo.lock
nativelink-store/src/filesystem_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/verify_store.rs
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/common.rs
nativelink-util/tests/common_test.rs
nativelink-util/tests/proto_stream_utils_test.rs
nativelink-worker/src/running_actions_manager.rs

We no longer make a few heap allocations to convert DigestInfo messages into strings. Now we can get a &str of a DigestInfo and do all the operations on the stack.
In addition serde's [De]Serialization now treats DigestInfo as a string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1338)

DigestInfo now does string conversions on the stack

---

nativelink-service/src/cas_server.rs
nativelink-service/tests/cas_server_test.rs

Fixes issue #1339
The RemoteExecution v2 API `GetTreeRequest` does not require that the `page_token` value be a non-empty string (or exist) only that it should only exist when the client wants the resume/offset the response based on a prior `GetTreeResponse.next_page_token`. The original implementation of the `get_tree` functionality (https://github.com/TraceMachina/nativelink/pull/905) requires that there _always_ be a value in the `page_token` field.
The [reference implementation in `buildfarm`](https://github.com/bazelbuild/bazel-buildfarm/blob/635d9fed03bedc076d019dcf4f430f20744eafe8/src/main/java/build/buildfarm/common/TreeIterator.java#L51-L52) treats an empty `page_token` as an initial request which seems entirely reasonable.
Added new unit tests.
Follow details in #1339 but run a …

Allow empty page_token for get_tree

---

nativelink-service/src/bep_server.rs
nativelink-service/tests/bep_server_test.rs

":" is the preferred way since Redis Insight from Redis itself shows your keys inside directories with ":"
This might break existing client setups which rely on the bep events.
Used bazel with the bep_backend to inspect the delivered bep keys in redis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1345)

[Change] BEP Redis key format

---

.gitignore
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs
nativelink-util/src/buf_channel.rs

There was a logic bug in our original implementation of the redis store that persisted across the rewrite to fred -- there could be an infinite loop in `RedisStore::update`. This PR fixes that.
See: https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pu9LV5ux4ILuT6MND
The test suite has been validated to pass and behave as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1269)

Fix potential infinite loop in `RedisStore::update`

---

web/platform/src/content/posts/CaseStudy_CIQ.md
web/platform/src/content/posts/CaseStudy_Samsung.md

The publication date on one of our case studies was wrong. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1357)

Fix the dates on case studies.

---

web/platform/deno.lock
web/platform/package.json

The deno deploy variables --org and --project are already set in the web workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1362)

Remove duplicated deno deploy env variables

---

modules/nativelink.nix
web/platform/src/content/docs/docs/nativelink-cloud/nix.mdx

After verifying that the LRE workflows behave as intended it's safe to enable this by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1369)

Allow nativelink flake module to upload results

---

.github/workflows/main.yml
modules/nativelink.nix
web/platform/src/content/docs/docs/nativelink-cloud/nix.mdx

This reverts commit 9600839bd2ba0a6915908c55fca24f373c3a2106.
The original idea was to implement a `readonly` setting to dynamically configure `--remote_upload_local_results`. While this is fairly straightforward to implement it turned out that the UX implications around the environment variables/scripts/files to configure this are nontrivial and we need to evaluate the different approaches in more depth first.
For now, revert to readonly by default and also add a small modifier to the relevant workflow so that the write-access workflow retains the ability to write artifacts on pushes to main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1372)

Revert "Allow nativelink flake module to upload results (#1369)"

---

.bazelrc
nativelink-config/src/serde_utils.rs
nativelink-error/src/lib.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-service/src/ac_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/src/execution_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/src/redis_store.rs
nativelink-store/src/size_partitioning_store.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/origin_context.rs
nativelink-util/src/resource_info.rs
nativelink-util/src/store_trait.rs
nativelink-worker/src/running_actions_manager.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1380)

Fix clippy::redundant_closure_for_method_calls

---

web/platform/astro.config.ts

Add a 301 redirect for the indexed  "/blog/case-study%3A-samsung-internet's-integration-with-nativelink"
to "/resources/blog/case-study-samsung"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1378)

Redirect indexed broken link

---

nativelink-store/src/s3_store.rs
nativelink-util/src/buf_channel.rs
nativelink-util/tests/buf_channel_test.rs

If using S3Store + VerifyStore is in use, S3 store could receive data that VerifyStore deemed invalid due to retry logic.
This only effects S3Store + VerifyStore due to the way AwsS3Sdk crate works, we need to hold recent data in the BufChannel, in the event VerifyStore got an invalid hash, the retry logic in S3 would trigger, but instead of being seen as "invalid" it would actually have stored the sent data and sent it, causing S3 to to still receive the invalid data. This PR causes BuffChannel logic to set a flag making the next read in S3 store always trigger the error condition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1383)

Fix S3Store retry might cause poisoned data

---

.bazelrc
nativelink-metric-collector/src/metrics_visitors.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-util/src/connection_manager.rs
nativelink-util/src/origin_context.rs
nativelink-util/src/retry.rs
nativelink-util/src/store_trait.rs
nativelink-worker/src/running_actions_manager.rs
src/bin/nativelink.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1393)

Fix clippy::semicolon_if_nothing_returned

---

nativelink-store/src/dedup_store.rs
nativelink-store/tests/dedup_store_test.rs

Fixes #1397
Added new test case in unit tests
- [X ] Tests added/amended
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1398)

Handle empty file request on dedup store

---

.github/workflows/coverage.yaml
CONTRIBUTING.md
Cargo.toml
flake.nix
nativelink-worker/Cargo.toml
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
web/platform/starlight.conf.ts

Reports may now be build via:
```nix
nix build .#nativelinkCoverageForHost
```
The `result` symlink then contains the contents of a webpage to view the
existing reports.
Pushes to main publish the site at tracemachina.github.io/nativelink.
Reports are built in release mode to closely resemble production coverage
of the testsuite. This also means that most worker tests are ignored via
a new `nix` feature to make the testsuite run in nix sandboxes. It's not
ideal, but accurately reflects our production coverage guarantees. A
future resolution for this might be  to implement more elaborate mocking
functionality for `nativelink-worker`.
Coverage leverages nix caching, but not Bazel caching. While Bazel has
builtin support for coverage, the reports were not satisfactory as they
rely on …

Introduce reproducible branch-based coverage

---

.bazelrc
nativelink-store/tests/s3_store_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1395)

Fix clippy::range_plus_one

---

README.md
web/platform/README.md
web/platform/src/content/docs/docs/faq/lre.mdx
web/platform/src/content/docs/docs/faq/remote-execution.mdx
web/platform/src/content/docs/docs/introduction/contributors.mdx

URLs starting `docs.nativelink.com` is redirected to introduction URL always. Found all occurrences of `docs.nativelink.com` and replaced that with `nativelink.com/docs`.
More details can be found in the link below.
Fixes #1385 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1386)

Fix `docs.nativelink.com` based URL not working

---

Cargo.lock
Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric-collector/tests/metric_collector_test.rs
nativelink-scheduler/Cargo.toml
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/Cargo.toml
nativelink-store/BUILD.bazel
nativelink-store/Cargo.toml
nativelink-store/tests/existence_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/Cargo.toml
nativelink-util/src/instant_wrapper.rs
nativelink-util/tests/evicting_map_test.rs
nativelink-worker/BUILD.bazel
nativelink-worker/Cargo.toml
nativelink-worker/tests/running_actions_manager_test.rs

- Update mock_clock
- Update tower
- Update tokio-rustls
- Remove the direct dependency on once_cell, as the functionality is now part of the standard library.
- Partially update the opentelemetry stack. A full upgrade is not yet possible as opentelemetry-prometheus relies on an outdated version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1402)

Bump nontrivial Rust dependencies

---

web/platform/src/components/qwik/sections/feature.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1404)

Fix broken demo button link

---

.bazelrc
nativelink-error/src/lib.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/execution_server.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/compression_store_test.rs
nativelink-util/src/health_utils.rs
nativelink-util/tests/health_utils_test.rs
src/bin/nativelink.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1413)

Fix clippy::needless_pass_by_value

---

flake.lock
flake.nix

This PR resolves a hash mismatch error encountered during the Local Remote Execution / Remote Workflow when building skopeo-1.16.1.drv.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1424)

Fix LRE Remote Workflow

---

nativelink-config/src/stores.rs
nativelink-metric-collector/Cargo.toml
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

Adds retry logic and configs for redis store. This will setup redis to reconnect and retry commands if the connection to redis is lost.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1407)

[Bug fix] Adds retry logic to redis store

---

nativelink-config/src/schedulers.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs

In the event a client is no longer requesting to execute a task, the
scheduler will now move items out of the queued state after 60 seconds
(configurable). This will ensure we don't end up with items in the queue
forever.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1414)

In redis scheduler removes items that are queued for too long

---

nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/utils/local_worker_test_utils.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs
src/bin/nativelink.rs

This PR implements graceful shutdown for worker instances to ensure that the scheduler is properly notified when workers are shutting down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1394)

Add graceful shutdown to worker instances

---

.bazelrc
nativelink-metric-collector/src/metrics_visitors.rs
nativelink-metric/src/lib.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-store/src/compression_store.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/platform_properties.rs
nativelink-util/src/retry.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1433)

Fix clippy::match_same_arms

---

tools/local-image-test.nix

The ECR registry currently has a lower chance to run into ratelimiting issues. Technically it's a less scalable registry though, so we might need to revisit this in the future.
Fixes #1438
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1442)

Work around trivy ratelimits

---

web/platform/astro.config.ts
web/platform/src/content/posts/CaseStudy_Samsung.md

A minor change we made resulted in redirect loops hurting our domain authority.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1469)

Stop Redirect Errors

---

web/platform/astro.config.ts
web/platform/src/layouts/Layout.astro
web/platform/src/thirdParty/GoogleTagManager.astro

Again, nothing to see here, just fixing third party scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1474)

Directly Inject LDFR Script

---

nativelink-config/Cargo.toml
nativelink-config/src/serde_utils.rs
nativelink-config/tests/deserialization_test.rs

These turned out to be much buggier than anticipated. The new implementation behaves like the old one but no longer requires `FromStr` and has consistent behavior with what we'd expect from yaml-to-json conversions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1471)

Make shellexpand fields more robust

---

nativelink-util/BUILD.bazel
nativelink-util/src/lib.rs
nativelink-util/src/shutdown_guard.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/utils/local_worker_test_utils.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs
src/bin/nativelink.rs

This makes makes it easier to manage more complex shutdown cases. For example, some services might need to shutdown last, so we introduce a priority system that services can opt into.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1491)

Add ShutdownGuard to replace oneshot for shutdown

---

.bazelrc
.github/workflows/main.yml
deployment-examples/docker-compose/README.md
deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json

Previously, the `docker compose` example used a default `instance_name` of "main", which meant that `--remote_instance_name=main` needed to be added to Bazel to get it to work as expected. This can be confusing for people who are just getting started and unfamiliar with all of the available configuration options. Since the value defaults to an empty string if this configuration item isn't provided, using that in the example should make it easier for someone to spin-up.
Fixes #1484
- Bug fix (non-breaking change which fixes an issue)
Manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1486)

Use an empty instance_name in docker compose example

---

native-cli/components/flux.go
native-cli/components/tekton.go
native-cli/programs/local.go

This PR introduces the Tekton operator with a TektonConfig to replace the existing Tekton pipelines, triggers, and dashboard.
There is currently a bug where we are only waiting for 60 seconds for the webhooks, instead of checking if they have reached a running/ready status, so there is a possibility that the tekton-webhooks are in an unready state when trying to deploy the tasks, pipelines and triggers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1337)

Add tekton operator to local dev cluster

---

web/platform/src/content/posts/NativeLink_for_Semiconductors.md
web/platform/src/pages/resources/index.astro

Makes generic blogposts discoverable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1520)

Discoverable generic blogposts

---

web/platform/src/components/qwik/pages/company.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1521)

Update company site on web/platform

---

nativelink-store/src/filesystem_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/store_trait.rs

Fixes # 1108
/claim #1108
https://hackmd.io/@HPxqrI77Q02izyGstTHbdg/ByS50OhGJx
Passes all of current test suite
- [] Updated documentation if needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1489)

Support native StoreKey in FilesystemStore

---

.bazelrc
MODULE.bazel
nativelink-proto/BUILD.bazel

Close the final nonhermeticity by reconfiguring rules_python to use a statically linked musl toolchain. This makes nativelink fully buildable and testable with lre-rs in remote execution with perfect parity to local execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1543)

Achieve perfect reproducibility for Linux Bazel builds

---

nativelink-service/src/bep_server.rs
nativelink-service/tests/bep_server_test.rs

LifetimeEvents and BuildEvents were racing to who would get the entry first. This partitions the data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1539)

Minor fix to BEP key encoding

---

tools/public/local-image-test.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1545)

Fix hardcoded value in local-image-test

---

nativelink-util/BUILD.bazel
nativelink-util/src/origin_event.rs
nativelink-util/src/origin_event_publisher.rs
nativelink-util/tests/origin_event_test.rs

We now encode information about the event type into the UUID of OriginEvents. This allows the parent_event_id to have info about who the parent is that generated the ID as well as the child now knows what kind of event it is even if the parent id is not able to be lookedup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1550)

Add event type info to node_id info in UUID

---

web/platform/src/components/qwik/components/header.tsx
web/platform/src/components/qwik/pages/community.tsx
web/platform/src/components/qwik/sections/community.tsx
web/platform/starlight.conf.ts

The Slack link on the website is now expired, though it was previously a never expires.  This change converts that link to a functioning one. 
I sent the URL to a user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1557)

Fix broken Slack link

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
local-remote-execution/README.md
web/platform/src/components/qwik/pages/home.tsx
web/platform/src/pages/resources/index.astro

Add Aaron Mondals awesome talk on the bazelcon to the homepage and resource page 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1452)

Add Aaron's awesome talk to homepage and resource page

---

web/platform/src/content/posts/CaseStudy_Fortune50.md

Add an anonymized blog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1567)

Add ananonymized blog

---

nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs

Clamp down some trait bounds so that thread safety issues have a higher chance of providing useful compiler errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1564)

Ensure that EvictingMap is threadsafe

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/events.proto
nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.events.pb.rs
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/src/worker.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/execution_server.rs
nativelink-store/src/compression_store.rs
nativelink-util/src/operation_state_manager.rs
nativelink-util/src/origin_context.rs
nativelink-util/src/origin_event.rs
nativelink-util/src/origin_event_middleware.rs
nativelink-util/src/platform_properties.rs
nativelink-util/tests/origin_event_test.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
src/bin/nativelink.rs

Adds an OriginEvent for when the scheduler schedules an action. This can be used for external systems to give visuals to what is happening inside the system or for debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1574)

Add OriginEvent for scheduler scheduling action

---

Cargo.lock
nativelink-config/src/cas_server.rs
nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/worker.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/BUILD.bazel
nativelink-service/Cargo.toml
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-util/src/action_messages.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/worker_api_client_wrapper.rs
nativelink-worker/src/worker_utils.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/utils/local_worker_test_utils.rs
src/bin/nativelink.rs

WorkerId can now be prefixed with a config. This will cause all internal WorkerIds to be prefixed with this config followed by a generated UUIDv6.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1578)

Add ability to prefix worker_id in config

---

nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/tests/simple_scheduler_test.rs

When the scheduler was updated to add the keep alive to the AwaitedAction the MemoryAwaitedActionDb was not updated to set this when a ClientKeepAlive was received.
Fix the test client_reconnect_keeps_action_alive which was not performing the eviction due to optimisations in the filter_operations function which then detected the issue.
Then update the ActionEvent::ClientKeepAlive event handler to update the client keep alive timestamp in the AwaitedAction.
Fixes #1579.
Fixed the existing test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1580)

ClientKeepAlive update action ClientKeepAlive

---

Cargo.lock
nativelink-config/src/stores.rs
nativelink-store/BUILD.bazel
nativelink-store/Cargo.toml
nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/evicting_map.rs
nativelink-util/tests/evicting_map_test.rs

FilesystemStore will no longer keep atime of files up-to-date. This
was an expensive operation, since every time any CAS/AC item was
touched, it'd update the atime, which caused a lot of sys calls.
While the system is running this PR has no effect, but when the
program is restarted, items are now inserted in order of atime then
mtime, but it relies on the filesystem to keep atime up-to-date.
This means that .has() calls do not "refresh" the atime on disk.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1584)

Remove atime references to FilesystemStore

---

nativelink-store/src/grpc_store.rs
nativelink-store/src/memory_store.rs
nativelink-store/src/s3_store.rs

Adds these stores to registry to be checked by the health checker if enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1586)

Add Grpc, Memory & S3 store to health checker registry

---

.github/actions/prepare-nix/action.yaml
.github/workflows/codeql.yaml
.github/workflows/coverage.yaml
.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/sanitizers.yaml
.github/workflows/scorecard.yaml
.github/workflows/tagged_image.yaml
.github/workflows/vale.yaml
.github/workflows/web.yaml
Cargo.lock
deployment-examples/docker-compose/Dockerfile
flake.nix

- Unify the nix setup across actions
- Bump most workflows to run on Ubuntu 24.04 and MacOS 15 by default
- Remove Ubuntu 20.04 as it's reaching EOL
- Fix outdated bazel setups
- Fix ring crate build missing clang on x86_64-linux
- Bump workflow versions
- Temporarily disable docker compose workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1589)

Refactor GitHub actions

---

native-cli/README.md
web/platform/src/content/docs/docs/contribute/native-cli.mdx
web/platform/starlight.conf.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1625)

Document contributing to the native-cli

---

flake.nix

Nix issues an evaluation warning if `stdenv` isn't defined as a function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1642)

Use selector function for stdenv

---

Cargo.toml

All of these settings are the default, so there is no reason to set them explicitly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1659)

Remove redundant settings in `Cargo.toml`

---

nativelink-config/src/cas_server.rs
nativelink-config/src/schedulers.rs
nativelink-config/src/stores.rs
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/default_scheduler_factory.rs
nativelink-scheduler/src/platform_property_manager.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/bep_server_test.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/grpc_store.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/dedup_store_test.rs
nativelink-store/tests/existence_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-store/tests/size_partitioning_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/digest_hasher.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/src/worker_utils.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
src/bin/nativelink.rs

`non_camel_case_types` has been changed to use `serde`'s renaming functionality, with the variants being renamed
- Renaming variants to follow Rust's naming conventions is inherently breaking. This only affects the Rust API, as `serde` attributes are used to maintain compatibility with snake case names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1666)

Rename variants to Rust standards

---

nativelink-macro/src/lib.rs
nativelink-proto/gen_lib_rs_tool.py
nativelink-proto/genproto/lib.rs
nativelink-scheduler/tests/utils/mock_scheduler.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs
nativelink-service/src/ac_server.rs
nativelink-service/src/bep_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/src/capabilities_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/src/execution_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-store/src/completeness_checking_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/memory_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/fastcdc.rs
nativelink-util/src/origin_event_publisher.rs
nativelink-util/src/retry.rs
nativelink-util/src/task.rs
nativelink-util/tests/proto_stream_utils_test.rs
nativelink-worker/tests/running_actions_manager_test.rs
src/bin/nativelink.rs

All remaining clippy lints are converted to `#[expect]` with reasons attached. The only exceptions are a handful of `#[allow]` attributes in testing due to the manner in which tests are compiled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1661)

Resolve, rework, explain clippy lints

---

src/bin/nativelink.rs

Right now, if you run `nix run -L .#nativelink -- ./nativelink-config/examples/basic_cas.json5` you get 
```
thread 'main' panicked at src/bin/nativelink.rs:672:31:
Path segments must not start with `:`. For capture groups, use `{capture}`. If you meant to literally match a segment starting with a colon, call `without_v07_checks` on the router.
```
because https://github.com/TraceMachina/nativelink/pull/1674 upgraded axum to 0.8.x [and they changed the router syntax](https://github.com/tokio-rs/axum/pull/2645), but there's no tests that run a config with the admin enabled. https://github.com/TraceMachina/nativelink/pull/1646 does do this, and hence a) why I've hit it and b) why I haven't added a test yet, as that PR will do the testing.
`nix run …

Fix admin router syntax for axum 0.8

---

deploy/chromium-example/build_chromium_tests.sh
web/platform/src/content/docs/docs/nativelink-cloud/Reclient.mdx

`rbe_cfg_dir` is deprecated for Chromium/Reclient usage, adding `reclient_cfg_dir` instead.
Fixes https://github.com/TraceMachina/nativelink/issues/1668
Made sure that change is appeared in docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1679)

Actualize param for reclient config dir (#1668)

---

nativelink-service/BUILD.bazel
nativelink-service/src/execution_server.rs

Request parsing for `ExecutionServer` splits instance name from operation ID  incorrectly when the former contains a slash.
Fixes #1688
Added unit test for `NativelinkOperationId::from_name`.
Manually tested with chromium siso v1.1.27.
```json
"instance_name": "projects/rbe-chromium-untrusted/instances/default_instance",
```
```sh
autoninja base -reapi_address 127.0.0.1:50051 -reapi_insecure -project rbe-chromium-untrusted
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1689)

Handle slashes in instance name of `WaitExecutionRequest`

---

BUILD.bazel
nativelink-config/BUILD.bazel
nativelink-error/BUILD.bazel
nativelink-macro/BUILD.bazel
nativelink-metric-collector/BUILD.bazel
nativelink-metric/BUILD.bazel
nativelink-scheduler/BUILD.bazel
nativelink-store/BUILD.bazel
nativelink-store/src/s3_store.rs
nativelink-util/BUILD.bazel
nativelink-worker/BUILD.bazel

This adds the ability to run unit tests to all nativelink crates, with the exception being `nativelink-proto`. It shouldn't be necessary for that crate given that it's codgen'd, plus it causes some errors that appear to be formatting-related (i.e. not at all relevant).
This also includes a drive-by change of adding an `#[allow]` to a false positive of a lint. I've noticed this before but it's now breaking bazel without it, leaving me with no choice but to silence it. This is not `#[expect]` because it's not triggering consistently (varying by build).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1691)

Add unit tests to bazel

---

flake.lock
flake.nix
local-remote-execution/README.md
local-remote-execution/flake-module.nix
local-remote-execution/modules/lre.nix

This change is breaking for flake module users:
- Renames `flakeModule` to `flakeModules`
- Renames the flake module `local-remote-execution` to `lre`. In particular import it with `nativelink.flakeModules.lre` and install `lre.bazelrc` with `${config.lre.installationScript}` in your shell hook.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1698)

Standardize flake naming

---

web/platform/utils/metaphase.ts
web/platform/utils/rustdoc_types.ts

This reflects the changes in Rustdoc JSON Types in https://github.com/rust-lang/rust/pull/135799. Fixes #1707.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1708)

Rename name to path in rustdoc

---

web/platform/utils/metaphase_aot.ts

Now `bun run build.docs` raises an error if it fails. In particular `.github/workflows/web.yaml` fails if the auto generated Rust documentation fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1710)

Throw error on generate docs fail

---

nativelink-config/examples/README.md
nativelink-config/examples/s3_backend_with_local_fast_cas.json5
nativelink-config/src/stores.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/s3_store_test.rs

We have made the changes to the S3Store such that it follows a generalised CloudObjectStore that can handle multiple cloud objects like GCS and Azure. This PR is a follow-up to the conversation in the following PR: https://github.com/TraceMachina/nativelink/pull/1645#pullrequestreview-2792790467
Updating the S3Store to a more generalised ObjectStore [Breaking Change]
This runs against the standard tests, so it should be fine. 
- - - …

[Breaking] Change S3Store to a generic CloudObjectStore

---

nativelink-config/README.md

This PR updates configuration examples in `nativelink-config/README.md` for the format of "stores" fields.
Before:
```json
{
"stores": {
"CAS_MAIN_STORE": {
"verify": {
"backend": {
```
After:
```json
{
"stores": [
{
"name": "CAS_MAIN_STORE",
"verify": {
"backend": {
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1727)

Update configuration example "stores" field format

---

nativelink-config/src/stores.rs
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

Advances #901 by enabling the locality-sensitive-hash store to be persisted and queried in Redis.
Adapted unit tests from the implementation for `MemoryStore`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1697)

Implement `StoreDriver::list` for `RedisStore`

---

nativelink-service/tests/bytestream_server_test.rs

Make the test self-documenting and remove redundant logic that isn't part of what we intend to cover.
Note that this isn't just a stylistic change, as variable elision influences codegen, especially under lower optimization levels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1726)

Refactor `write_too_many_bytes_fails` test

---

.github/workflows/coverage.yaml
.github/workflows/lre.yaml
.github/workflows/nix.yaml

This is slowing down CI too much. This change also increases some of the Ubuntu runner corecounts to improve CI runtime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1732)

[Breaking] Remove support for MacOS 13 on x86_64

---

web/platform/utils/md_to_mdx.ts

Restrict replacing curly brackets in the `md` to `mdx` conversion to comments in `js` codeblocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1742)

Fix formatting in configuration-intro

---

nativelink-service/tests/bep_server_test.rs

In a distributed system, connections are terminated. We need to have a test to ensure that NativeLink will remain correct even if the event stream is termintated.
Fixes #1740 
Ran the integration tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1741)

Test stream termination

---

kubernetes/components/worker/worker.json5
kubernetes/nativelink/nativelink-config.json5

This syncs the directory locations to what we use in the Helm chart. Generally it seems more portable and efficient to skip the home directory lookup and use static `/tmp` paths instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1761)

Make K8s filesystem paths independent of `$HOME`

---

.bazelrc
Cargo.toml
nativelink-metric/nativelink-metric-macro-derive/src/lib.rs
nativelink-metric/src/lib.rs
nativelink-proto/gen_lib_rs_tool.py
nativelink-proto/genproto/lib.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-service/src/cas_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/bep_server_test.rs
nativelink-service/tests/bytestream_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/fast_slow_store.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/gcs_client/mocks.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/action_messages.rs
nativelink-worker/src/running_actions_manager.rs
src/bin/nativelink.rs

The mentioned commit broke clippy for the bazel build, effectively
disabling clippy entirely. This fixes that and adjusts the lints to
prepare for clippy::pedantic.
Reenabling the lints pointed out various improperly fixed lints. This
change fixes those as well and while it keeps the `option_with_else`
lint disabled, refactors some potential occurances manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1758)

Fix clippy lints after d106fe7

---

.bazelrc
Cargo.toml

We had a bunch of unnecessarily enabled lints that were already in the style or pedantic sets. This change removes all of them and makes it easier to see which lints are intentionally pulled from the restriction set and which ones from the nursery set we handle specially.
In terms of strictness this change is a no-op, but aside from the readibility improvements this is actually a network I/O improvement when using remote execution due to the shortened command lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1764)

Simplify clippy configs

---

.bazelrc
Cargo.toml
nativelink-proto/gen_lib_rs_tool.py
nativelink-proto/genproto/lib.rs

Turns out this was already fine and just needed to be added as exclude to the generated proto files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1767)

Fix clippy::doc_link_with_quotes

---

deployment-examples/docker-compose/local-storage-cas.json5
deployment-examples/docker-compose/scheduler.json5
integration_tests/buildstream/buildstream_cas.json5
kubernetes/nativelink/nativelink-config.json5
nativelink-config/BUILD.bazel
nativelink-config/README.md
nativelink-config/examples/README.md
nativelink-config/examples/basic_cas.json5
nativelink-config/examples/filesystem_cas.json5
nativelink-config/examples/gcs_backend.json5
nativelink-config/examples/redis.json5
nativelink-config/examples/s3_backend_with_local_fast_cas.json5
nativelink-config/src/backcompat.rs
nativelink-config/src/cas_server.rs
nativelink-config/src/lib.rs
nativelink-service/src/ac_server.rs
nativelink-service/src/capabilities_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/src/execution_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/cas_server_test.rs
toolchain-examples/nativelink-config.json5
web/platform/src/content/docs/docs/config/basic-configs.mdx
web/platform/src/content/docs/docs/config/production-config.mdx

This includes a backwards-compatibility layer to avoid breaking anything. When the old format is fully removed, this can be trivially accomplished by removing `backcompat.rs` and removing the `#[serde(deserialize_with)]` annotations from the fields.
This does not change the config for bytestream, as it is far more involved than the other fields.
Part of #1649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1712)

Largely change from map-based to array-based config

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
web/platform/src/content/docs/docs/config/production-config.mdx
web/platform/src/content/posts/Finetune_LLM_On_CPU.md

This PR:
1. Creates a web page for my blog on Fine-tunuing an LLM on CPUs using Bazel and NativeLink
2. Adds some new words to vale vocab 
3. Makes a minor formatting change to nativelink/web/platform/src/content/docs/docs/config/production-config.mdx that is also presented in PR #1743. This formatting change needs to be merged into production before I can create a new blog post. Since PR #1743 will probably get merged later, I had to commit that change in this PR as well to make all the CI tests pass.
The content and design of this web page are heavily inspired by the web page I made for my full AI Customer Service Agent blog post, which has already received LGTMs from Marcus and Aaron, though the latter has not yet been added to production. Once the page development was complete and the …

Add Finetuning LLMs on CPUs Blog Post

---

.bazelrc
Cargo.toml
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-util/src/action_messages.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

clippy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1771)

Resolve `clippy::fallible_impl_from`

---

Cargo.lock
nativelink-config/src/stores.rs
nativelink-util/BUILD.bazel
nativelink-util/Cargo.toml
nativelink-util/src/tls_utils.rs
nativelink-util/tests/tls_utils_test.rs

There currently is no way to connect to a given gRPC endpoint using TLS without manually providing a CA certificate file, certificate file, and/or key file. This causes issues when using managed certificates where it is not possible to connect via TLS to a secured endpoint unless the relevant secrets are distributed across workers and manually accessed via the config. 
The proposed changes add an option for the `ClientTlsConfig` of `use_native_roots`. This will ensure that tonic will use the root native certs for it's tls config. If the field `use_native_roots` is present ca, cert, and key files will be ignored if provided but are not required. This adds the tonic `tls-native-roots` feature.
NOTE: The `ca_file` field in the `nativelink_config::stores::ClientTlsConfig` is no longer …

Add support for native root certs

---

Cargo.lock
nativelink-config/src/stores.rs
nativelink-store/Cargo.toml
nativelink-store/src/s3_store.rs

Switch from `webpki-roots` to `rustls-platform-verifier` for TLS certificate verification.
Similarly to #1782, it makes sense to use platform certificates. This makes it easier for users to update certificates.
See also https://docs.rs/rustls-platform-verifier/latest/rustls_platform_verifier/.
I've tested this change by running the `bazel` Nix template against a `nativelink-worker-lre-cc` running in Docker, configured with `s3_backend_with_local_fast_cas.json5` and an AWS S3 instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1785)

Use native root certs for S3 stores

---

.github/actions/prepare-nix/action.yaml

Bump the nix installer action and remove the no longer functional cache
action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1813)

 Update nix setup for GHA workflows

---

web/platform/src/components/qwik/sections/hero.tsx

The current video on the website's landing page is very blurry. This PR replaces that with a newly recorded, clearer video. 
Fixes #1784 
I had created a PR before the Memorial Day Weekend to fix this same issue; I closed it and made the following changes:
1. Used a dedicated mic to improve audio quality
2. Recorded in 1080p instead of 720p
3. Cleaned local cache before running bazel test commands
4. Used temporary API keys that are now deleted to not expose my Nativelink Cloud account
Once the video link was updated, the page was examined via `rm -rd dist && bun preview` and everything looked as expected. To check how the website would look on mobile, I clicked to inspect the page on Chrome; this opened the Developer's console and simulated the web page on a modern phone. Everything was …

Replace video for website's hero section

---

Cargo.lock
flake.nix
nativelink-config/BUILD.bazel
nativelink-config/Cargo.toml
nativelink-config/src/cas_server.rs
nativelink-config/tests/json5_test.rs
nativelink-error/BUILD.bazel
nativelink-error/Cargo.toml
nativelink-error/src/lib.rs
src/bin/nativelink.rs

This confirms that all the example JSON5 configs actually pass the parser. It turned out to be fine, but I was worried we could make changes and accidentally break them.
It could be expanded to also pull in the other demo configs in the repo, but that's a bit tricky given fun of where Bazel has certain files and not being able to go up a directory in the config.
Existing test suites
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1818)

Check example JSON5 files pass the parser

---

web/platform/src/routeData.ts
web/platform/starlight.conf.ts

[The current reclient page](https://www.nativelink.com/docs/nativelink-cloud/reclient) has a duplicated ToC due to the tabs setup breaking the generation entirely. The ideal scenario would be doing the tabs on a per-step basis and syncing the OS choice somehow, but this at least mostly fixes the ToC for now.
local testing with `bun run build && bun serve`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1827)

Override the reclient ToC with a working version

---

deployment-examples/docker-compose/local-storage-cas.json5
deployment-examples/docker-compose/scheduler.json5
deployment-examples/docker-compose/worker.json5
integration_tests/buildstream/buildstream_cas.json5
kubernetes/components/worker/worker.json5
kubernetes/nativelink/nativelink-config.json5
nativelink-config/examples/basic_cas.json5
nativelink-config/examples/filesystem_cas.json5
nativelink-config/examples/gcs_backend.json5
nativelink-config/examples/redis.json5
nativelink-config/examples/s3_backend_with_local_fast_cas.json5
toolchain-examples/nativelink-config.json5
tools/pre-commit-hooks.nix

This adds formatting for JSON5 files to the pre-commit, and applies it to all the current files. Their formatting was previously mostly good, but somewhat inconsistent. Note this removes the quote formatting around properties which makes the diff notably larger, but the tool I've been using doesn't support that as an option. I like it personally, but that's an open question if it's a preferred style or not.
Existing test suites.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1817)

Add JSON5 formatting to pre-commit

---

nativelink-store/src/gcs_client/client.rs
nativelink-store/src/gcs_client/mocks.rs
nativelink-store/src/gcs_client/types.rs
nativelink-store/src/gcs_store.rs
nativelink-store/tests/gcs_client_test.rs

The GCS store implementation had numerous bugs to do with edge cases of upload sizes and did way more cloning that is necessary.  Update the implementation to remove the excessive clones, modify the get_part implementation to stream instead of buffer huge files in memory.  For upload the last chunk is not written if it sits on a chunk boundary, so change a flag to fix that.  Finally update all of the types to u64 rather than constantly switching back and forth between u64 and i64 unnecessarily.
Fixes #1845
I implemented a test client to push a 100Mb file up to the CAS. Notably this failed before this change and passes afterward.
- - - …

Fix GCS store implementation

---

web/platform/src/components/qwik/components/footer.tsx
web/platform/src/components/qwik/components/video.tsx

I removed the background video on the main page for **mobile devices only**, to improve performance and reduce LCP (Largest Contentful Paint).
The logic is simple: I avoided hardcoding the video `source` URL directly in the `<video>` tag. Instead, I first detect whether the user is on a mobile or desktop device, and then assign the `source` URL accordingly.
I’ve removed both background videos — one from the header and one from the footer.
Fixes #1799 
- Bug fix (non-breaking change which fixes an issue)
before the change the some background video downloaded twice for Hader and Footer
with caching 
- - -
This change is [<img …

Remove background video on mobile

---

nativelink-error/src/lib.rs
nativelink-store/src/gcs_store.rs
nativelink-store/tests/gcs_store_test.rs

While trying to fix some GCS permission errors it wasn't always clear what path/bucket wasn't able to be accessed. This PR adds some extra context to make fixing those a little easier.
Regular `cargo test` stuff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1849)

Add GCS bucket/path when we fail to load metadata

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/lib.rs
nativelink-scheduler/src/mock_scheduler.rs
nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-scheduler/tests/property_modifier_scheduler_test.rs
nativelink-service/BUILD.bazel
nativelink-service/src/execution_server.rs
nativelink-service/tests/execution_server_test.rs

Was getting `ERROR nativelink_service::execution_server: error: status: Internal, message: "Instance name '{}' not configured : Failed on execute() command", details: [], metadata: MetadataMap { headers: {} }` i.e. a non-formatted instance name error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1858)

Fix execution_server instance name error

---

.github/workflows/lre.yaml

Mostly trying to aid debugging the build issues with https://github.com/TraceMachina/nativelink/pull/1848
Github :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1857)

Add debug helpers to check LRE kustomization

---

.github/workflows/main.yaml
tools/toolchain-nativelink/Dockerfile
tools/toolchain-nativelink/toolchain-nativelink.sh

Fixes the RBE test image pulls e.g. https://github.com/TraceMachina/nativelink/actions/runs/16192179075/job/45710433918
Mostly I've just built out the image and pushed it, so the pull step should at least work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1862)

Fix RBE testing

---

.github/actions/prepare-nix/action.yaml

[It was removed](https://github.com/TraceMachina/nativelink/pull/1813), but now appears to be unbroken again (see for example https://github.com/DeterminateSystems/magic-nix-cache-action/pull/132). It's not entirely clear, but as far as I can tell the problems are apparently resolved?
Github :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1851)

Re-add Nix magic cache

---

nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Per a user's report, if an action fails on worker X, and the failed action is returned the queue, if worker x picks up the action again, there can be a directory collision because worker x may be immediately available due its most recent action failing and the queue being empty. 
The physical cleanup should happen before an action is eligible for retry. 
One tradeoff to consider here: there is some risk of impact to performance but I'm fine with is because it improves stability and predictability.
Fixes # ([1859](https://github.com/TraceMachina/nativelink/issues/1859))
- - - …

Fix directory collision on action retries by waiting for cleanup and removing stales

---

Cargo.lock
nativelink-config/BUILD.bazel
nativelink-config/Cargo.toml
nativelink-config/src/backcompat.rs
nativelink-config/src/cas_server.rs
nativelink-config/src/schedulers.rs

Previously, the backwards compatibility helper gave an example of how to fix things, but wasn't clear regarding a) it was only an example and b) which one it was complaining about.
This PR now outputs the exact config that was wrong and a better config.
Example:
```
2025-07-21T19:31:54.138311Z  WARN test_configs_deserialization: nativelink_config::backcompat: WARNING: Using deprecated map format for services. Please migrate to the new array format:
// Old:
{
"bar": {
"store": "bar_store"
},
"foo": {
"store": "foo_store"
}
}
// New:
[
{
"instance_name": "bar",
"store": "bar_store"
},
{
"instance_name": "foo",
"store": "foo_store"
}
]
```
- - -
This change is [<img …

Backwards compatibility now says what to change

---

nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

In [PR#1394](https://github.com/TraceMachina/nativelink/pull/1394) the worker shutdown was made to happen gracefully and wait for scheduled actions to complete.  However it missed three separate race conditions which can cause this to misbehave and timeouts to occur at the scheduler.
Firstly, there is the condition where a shutdown request is handled while an action is in-flight (being downloaded, but not yet registered with the running actions manager).  If there are no other actions then this can result in the complete_actions returning immediately even though there are still actions in-flight which then get dropped and have to time out at the scheduler.
Secondly, there is the race of sending the GoingAwayRequest to the scheduler and it assigning new work.  This means that if the …

Graceful worker shutdown

---

nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-scheduler/tests/utils/scheduler_utils.rs

Currently the tests have a mock Redis implementation that means complex scheduler tests require a lot of mock values to be populated by the developer.
Instead, implement a fake Redis implementation that provides the bare minimum Redis interface to allow for a scheduler to work.
This is a test only change, it's only tests :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1895)

Fake Redis test

---

nativelink-scheduler/src/simple_scheduler.rs

If the do_try_match algorithm fails then it does not re-try until there is another task or worker event.  However if the algorithm failed due to a worker disconnect then the action will permanently be stuck.
Ensure that the do_try_match gets to run again in a reasonable time by executing it after a short delay if the previous execution failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1892)

Retry matching on failure

---

nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/awaited_action_db/mod.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-scheduler/tests/redis_store_awaited_action_db_test.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-store/src/mongo_store.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/mongo_store_test.rs
nativelink-util/src/operation_state_manager.rs
nativelink-util/src/store_trait.rs
src/bin/nativelink.rs

This suite of changes hardens the Redis scheduler for scaling and ensures that operations are correctly queued.  The existing scheduler has issues during shutdown and re-queuing of failed operations.  Here we ensure that worker disconnects during action assignment do not count against attempts (worker scale down), scheduler shutdown correctly sets operations back to queued (scheduler scale down) and operation re-joining when an action has completed correctly schedules a new operation rather than leaving it permanently in the executing stage.
Tested on my build cluster which is now functioning without issues even when scaling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/ …

Retry on disconnect

---

web/platform/src/components/qwik/components/cards.tsx

Updated the Product pricing page. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1923)

Update product pricing p2

---

.github/workflows/native-cargo.yaml
BUILD.bazel
Cargo.toml
flake.nix
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-util/Cargo.toml
nativelink-util/src/platform_properties.rs
src/bin/nativelink.rs

Sometimes when you've got some workers who's config varies from the CAS config it'll reject them and it's unclear why. This PR adds a feature flag to add logging to this path. It's disabled by default as otherwise it'd slow down situations with many heterogenous workers.
Manually mostly, in a production scenario we were having difficulty determining issues with without this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1925)

Add worker_find_logging

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-scheduler/src/api_worker_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/src/worker_scheduler.rs
nativelink-service/src/worker_api_server.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/worker_api_client_wrapper.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/utils/local_worker_test_utils.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

This reverts commit `85c279a4467c5322159c5f55bca05be6b3bf92c4` for now, until we fix the underlying issue that is causing the worker panic.
We can reference the old commit in the branch: https://github.com/amankrx/nativelink/tree/early-scheduling
Panic logs: 
```
thread 'main' panicked at src/bin/nativelink.rs:829:9:
Error { code: Internal, messages: ["status: Internal, message: \"Action Uuid(b9eaa6f2-df15-45d7-a1a8-e33683fdb61c) is already completed with state Completed(ActionResult { output_files: [], output_folders: [], output_directory_symlinks: [], output_file_symlinks: [], exit_code: -178, stdout_digest: DigestInfo(\\\"0000000000000000000000000000000000000000000000000000000000000000-0\\\"), stderr_digest: DigestInfo(\\\"0000000000000000000000000000000000000000000000000000000000000000 …
```

Revert ExecutionComplete early scheduling optimization

---

nativelink-config/src/serde_utils.rs
nativelink-config/tests/deserialization_test.rs

Previously, it said "no value can be found" which is a bit unclear
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1939)

Make the error on a size field clearer

---

nativelink-store/src/filesystem_store.rs
nativelink-store/tests/filesystem_store_test.rs

We've seen some scenarios where our temp storage exceeds the expected usage of said, despite deletes occurring. One possibility there is that we've got a _lot_ of extra delete spawns in flight and this PR adds logging around that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1941)

Add more logging around active_drop_spawns
