TraceMachina/nativelink

cas/grpc_service/ac_server.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/grpc_service/tests/cas_server_test.rs
cas/store/memory_store.rs
cas/store/s3_store.rs
cas/store/store_trait.rs
cas/store/tests/memory_store_test.rs
cas/store/tests/s3_store_test.rs
cas/store/tests/verify_store_test.rs
cas/store/verify_store.rs
util/common.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/4)

Remove DigestInfo.trust_size & add expected_size to update() function

---

cas/grpc_service/ac_server.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
util/async_read_taker.rs

Also fixes some spelling errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/5)

Various changes to improve debugging

---

cas/store/s3_store.rs
cas/store/tests/s3_store_test.rs
config/examples/basic_cas.json
util/async_read_taker.rs
util/tests/async_read_taker_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/6)

Fix s3_store

---

.bazelrc
cas/cas_main.rs
cas/grpc_service/ac_server.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
cas/store/s3_store.rs
cas/store/tests/s3_store_test.rs
util/error.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/9)

Fix bug in s3_store where 5mb is calculated wrong

---

Cargo.lock
Cargo.toml
cas/store/s3_store.rs
util/BUILD
util/common.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/12)

Fix case where s3 uploads in wrong order

---

util/fastcdc.rs
util/tests/fastcdc_test.rs

Made some minor changes to give fastcdc a slight boost in speed
by getting some of the rust-checks out of the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/16)

Slightly improve the performance of fastcdc by ~30%

---

cas/store/BUILD
cas/store/fast_slow_store.rs
cas/store/lib.rs
cas/store/tests/fast_slow_store_test.rs
config/backends.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/20)

Adds FastSlow store that will try the fast store before slow store

---

cas/store/fast_slow_store.rs
config/examples/basic_cas.json

A case where the client can close the connection causing the future
to be destoryed resulting in the EOF to fail to write to underlying
store. We no longer care if the EOF suceeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/21)

Fix minor issue in FastSlowStore

---

cas/store/memory_store.rs
util/evicting_map.rs
util/tests/evicting_map_test.rs

This is in prep to make it more generalized so file system store
can use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/22)

EvictingMap is now a template

---

util/fastcdc.rs
util/tests/fastcdc_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/25)

Minor change to make fastcdc return Bytes intead of BytesMut

---

cas/grpc_service/tests/bytestream_server_test.rs
util/BUILD
util/buf_channel.rs
util/error.rs
util/tests/buf_channel_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/27)

Add buf_channel that will be used to help transport bytes around

---

cas/grpc_service/BUILD
cas/grpc_service/bytestream_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
util/buf_channel.rs

Simple ability to tell the client if an upload is in progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/29)

Adds simple query_write_status support

---

cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/memory_store.rs
cas/store/s3_store.rs
cas/store/store_trait.rs
cas/store/verify_store.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/30)

Cleanup un-needed lifetime annotations in store traits

---

Cargo.lock
Cargo.toml
cas/cas_main.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/grpc_service/tests/cas_server_test.rs
cas/store/BUILD
cas/store/filesystem_store.rs
cas/store/lib.rs
cas/store/memory_store.rs
cas/store/tests/filesystem_store_test.rs
config/backends.rs
config/examples/basic_cas.json
third_party/BUILD.bazel
third_party/crates.bzl
third_party/remote/BUILD.filetime-0.2.15.bazel
third_party/remote/BUILD.tokio-stream-0.1.8.bazel
util/BUILD
util/evicting_map.rs
util/tests/evicting_map_test.rs

This store will use the filesystem to store the files in a persistent
manner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/32)

Add filesystem store

---

config/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/34)

Adds readme to configuration

---

cas/cas_main.rs
cas/grpc_service/BUILD
cas/grpc_service/ac_server.rs
cas/grpc_service/ac_utils.rs
cas/grpc_service/capabilities_server.rs
cas/grpc_service/execution_server.rs
cas/scheduler/BUILD
cas/scheduler/platform_property_manager.rs
cas/scheduler/scheduler.rs
config/BUILD
config/README.md
config/cas_server.rs
config/examples/basic_cas.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/36)

Add basic scaffolding for scheduler + remote execution

---

cas/store/dedup_store.rs
cas/store/tests/dedup_store_test.rs

.has() call in dedup store will now verify that all entries in the
index exist in the content store. This will ensure that if we are
using an eviction-like store as the content store it will properly
return None in the event that any part of the content was purged.
In addition we remove the is_small_object optimization in dedup
store. This optimization should be done in another store that will
be created in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/rust_cas/39)

Remove small item optimization in dedup_store and .has() calls

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/45)

Rename project turbo-cache

---

.github/workflows/main.yml
README.md

Adds github actions automated testing to pull requests and master
pushes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/56)

Adds automated CI tests on pull requests and master

---

cas/cas_main.rs

This is a minor performance improvement that allows different
services to run in their own spawn, since they don't depend on
each other anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/57)

Services in main() now run in their own spawn

---

cas/grpc_service/execution_server.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/action_messages.rs
cas/scheduler/tests/scheduler_test.rs
cas/scheduler/worker.rs
cas/worker/tests/local_worker_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/69)

Remove the requirement of using reference for action_messages

---

cas/store/filesystem_store.rs
cas/store/tests/filesystem_store_test.rs

Fixes a case where we'd check if the temp directory is clean after
some tests, but the Drop condition it was checking against was
the one actually deleting the files in that directory (in a spawn).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/71)

Fixes flakey filesystem_store_test

---

cas/scheduler/BUILD
cas/scheduler/action_messages.rs
cas/scheduler/tests/action_messages_test.rs

It requires a "more" full URL path not the short path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/72)

Fix wrong `type_url` in google-proto's Any type

---

cas/store/filesystem_store.rs

There was a rare condition that could happen where the store would
atomically swap the temp file and the final location then delete
the temp file immediately after. Normally this would be fine, however
during a hardlink, the interal kernel command first queries the inode
then creates a hardlink for the queried inode. If the file was not
swapped yet and the inode was queried, it'll get the inode of the
file about to be deleted, then if the file is deleted then the
hardlink will use an inode that doesn't exist any more.
This is solved by adding a 100ms delay. In testing 1ms would be
enough on my 16 core testbench, but to give plenty of leeway we add
a substantial delay.
This is also incredibly hard to write a test for, since it was a
flake condition and I don't have control over the innards …

Filesystem store now delays before deleting temp file

---

cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs

The scheduler had a bug where it was not removing actions from the
HashSet when an action completed. This caused an error to be returned
if the same action tried to be executed again.
Also adds test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/80)

Fix bug in scheduler of not removing actions after execution

---

cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/verify_store.rs

This will be used in future PR that need to pass this across threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/82)

Add Send trait to as_any() store calls

---

.bazelrc
.github/workflows/main.yml
.gitignore
cas/grpc_service/BUILD
cas/grpc_service/ac_server.rs
cas/grpc_service/bytestream_server.rs
cas/grpc_service/cas_server.rs
cas/grpc_service/execution_server.rs
cas/store/BUILD
cas/store/default_store_factory.rs
cas/store/grpc_store.rs
config/backends.rs
deployment-examples/docker-compose/Dockerfile
deployment-examples/docker-compose/docker-compose.yml
deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/docker-compose/memory-cas.json
deployment-examples/docker-compose/scheduler.json
deployment-examples/docker-compose/worker.json
integration_tests/simple_cache_test.sh
integration_tests/simple_remote_execution_test.sh
run_integration_tests.sh
util/BUILD
util/error.rs
util/resource_info.rs
util/write_request_stream_wrapper.rs

GrpcStore can be used to forward tasks to another any BRE CAS
service.
Integration tests are also added to ensure everything works properly
together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/86)

Adds GrpcStore and first integration tests

---

.gitignore
README.md
cas/cas_main.rs
deployment-examples/docker-compose/Dockerfile
deployment-examples/docker-compose/docker-compose.yml
deployment-examples/terraform/README.md
deployment-examples/terraform/ami.tf
deployment-examples/terraform/auto_scaling_groups.tf
deployment-examples/terraform/certificates.tf
deployment-examples/terraform/common.tf
deployment-examples/terraform/dns.tf
deployment-examples/terraform/iam.tf
deployment-examples/terraform/lambdas.tf
deployment-examples/terraform/load_balancers.tf
deployment-examples/terraform/main.tf
deployment-examples/terraform/s3.tf
deployment-examples/terraform/scripts/cas.json
deployment-examples/terraform/scripts/create_filesystem.sh
deployment-examples/terraform/scripts/lambdas/update_scheduler_ips.py
deployment-examples/terraform/scripts/scheduler.json
deployment-examples/terraform/scripts/start_turbo_cache.sh
deployment-examples/terraform/scripts/turbo-cache.service
deployment-examples/terraform/scripts/worker.json
deployment-examples/terraform/security_groups.tf
deployment-examples/terraform/ssh_keys.tf
deployment-examples/terraform/variables.tf
deployment-examples/terraform/vpc.tf

This adds a reference implementation of a terraform deployment
script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/95)

Add terraform deployment example and documentation

---

WORKSPACE

Requires a slight change to rust_register_toolchains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/102)

Update rules_rust to 0.20.0

---

cas/scheduler/action_messages.rs
cas/worker/running_actions_manager.rs

Some nits that weren't in #113 because it auto-merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/119)

Fix a couple of nits with the timestamp additions.

---

cas/cas_main.rs
config/cas_server.rs

Gzip is quite an expensive compression algorithm and many configurations are server-to-server or partially localhost setups. Because of this, it is better to have gzip disabled by default and enable it only for use cases that specifically request it to be enabled through the config files.
These numbers are served from localhost compiling turbo-cache twice once to populate the cache and another to serve the cache. Between runs the cache was cleared completely and restarted. Gzip enabled ~48.151s
Gzip disabled ~2.475s
fixes #109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/127)

Gzip compression is now disabled by default and configurable

---

cas/store/filesystem_store.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/130)

Perform parallel reading of content directory to speed up startup.

---

cas/BUILD
cas/cas_main.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/BUILD
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/platform_property_manager.rs
cas/scheduler/scheduler.rs
cas/scheduler/tests/scheduler_test.rs
config/BUILD
config/cas_server.rs
config/examples/basic_cas.json
config/examples/filesystem_cas.json
config/examples/s3_backend_with_local_fast_cas.json
config/lib.rs
config/schedulers.rs
deployment-examples/docker-compose/scheduler.json
deployment-examples/terraform/scripts/cas.json
deployment-examples/terraform/scripts/scheduler.json

This is a step in the direction to support different scheduler impls.
towards: #140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/141)

Scheduler config now supports multiple impls

---

.github/workflows/main.yml
deployment-examples/docker-compose/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/144)

Use recent Ubuntu with Clang as build environment

---

cas/store/tests/filesystem_store_test.rs

I had a concern that the loading of filetimes from the disk may have been broken while looking into the ordering of entries in the evicting map.  It turns out that this was unfounded as writing a test proves that the function works as expected.
I then broke the function on purpose by changing the sort order and found this new test was the only one that failed.  Therefore adding it to the test suite seems reasonable since it is now written.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/157)

Add a test for filestore loading from disk.

---

.dockerignore
.github/workflows/main.yml
deployment-examples/docker-compose/Dockerfile
run_integration_tests.sh

closes #145
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/151)

Remove dependency on `satackey/action-docker-layer-caching`

---

.github/workflows/main.yml
deployment-examples/docker-compose/Dockerfile

This will allow us to more easily test different OSs and such.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/165)

Move CI tests to run under docker

---

cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/utils/mock_running_actions_manager.rs
cas/worker/tests/utils/mock_worker_api_client.rs
cas/worker/worker_utils.rs

These are mostly trivial fixes.
The remaining issues in this directory are some bad integer conversions and lifetime issues that should be handled separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/169)

Fix most clippy warnings in worker files

---

cas/grpc_service/bytestream_server.rs
cas/grpc_service/capabilities_server.rs
cas/grpc_service/cas_server.rs
cas/grpc_service/execution_server.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/grpc_service/tests/cas_server_test.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/170)

Fix clippy cas/grpc_service folder

---

cas/grpc_service/cas_server.rs

Taking inspiration from the work in CacheLookupScheduler, modify the CasServer to use UnorderedFutures to perform batch operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/173)

Move to UnorderedFutures in cas_store.

---

cas/store/ac_utils.rs
cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/default_store_factory.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/grpc_store.rs
cas/store/lib.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/tests/compression_store_test.rs
cas/store/tests/dedup_store_test.rs
cas/store/tests/fast_slow_store_test.rs
cas/store/tests/filesystem_store_test.rs
cas/store/tests/memory_store_test.rs
cas/store/tests/ref_store_test.rs
cas/store/tests/s3_store_test.rs
cas/store/tests/size_partitioning_store_test.rs
cas/store/tests/verify_store_test.rs
cas/store/verify_store.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/171)

Fix clippy messages in cas/store

---

cas/grpc_service/cas_server.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/store/ac_utils.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/tests/compression_store_test.rs
cas/store/tests/dedup_store_test.rs
cas/store/tests/fast_slow_store_test.rs
cas/store/tests/filesystem_store_test.rs
cas/store/tests/memory_store_test.rs
cas/store/tests/s3_store_test.rs
cas/store/tests/verify_store_test.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/utils/mock_running_actions_manager.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/175)

Fix digest clones and a few other minor clippy warnings

---

cas/grpc_service/tests/worker_api_server_test.rs
cas/scheduler/default_scheduler_factory.rs
cas/scheduler/grpc_scheduler.rs
cas/scheduler/platform_property_manager.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/simple_scheduler_test.rs

Final clippy patch. After this we can enable clippy by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/181)

Fix clippy warnings for scheduler directory

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
cas/store/BUILD
cas/store/dedup_store.rs
cas/store/tests/dedup_store_test.rs

I don't know how to get the `LAST_CHUNK_HASH` out of the EvictingMap, so the `check_missing_last_chunk_test()` in dedug_store_test fails, however all the other tests are passing successfully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/205)

Add blake3 in DedubStore

---

.github/workflows/main.yml
deployment-examples/docker-compose/Dockerfile
integration_tests/simple_prometheus_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/217)

Improve caching in CI and fix flakey prometheus test

---

cas/worker/running_actions_manager.rs

There was a serial operation of uploading stderr and stdout then uploading the files. This PR makes it so they get uploaded in parallel.
fixes: #212
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/218)

Fix inefficient upload of stderr/stdout in workers

---

deployment-examples/terraform/ami.tf
deployment-examples/terraform/scripts/create_filesystem.sh
deployment-examples/terraform/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/219)

Fix the AWS deployment examples

---

cas/store/dedup_store.rs
cas/store/tests/dedup_store_test.rs

Found a few fence-post bugs in dedup store reading where the chunk that was desired fell exactly on the boundary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/221)

Fix fence post bugs in dedup store

---

cas/scheduler/action_messages.rs
cas/scheduler/cache_lookup_scheduler.rs
cas/scheduler/simple_scheduler.rs
cas/scheduler/tests/action_messages_test.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/worker/BUILD
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
config/cas_server.rs
util/error.rs

fixes: #211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/223)

Jobs now honor timeout in action

---

.github/workflows/main.yml
README.md
cas/store/tests/filesystem_store_test.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/worker_utils.rs
util/fs.rs

Officially windows is now supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/235)

Add windows support

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/242)

Fix readme TLDR

---

Cargo.lock
cas/scheduler/BUILD
cas/scheduler/property_modifier_scheduler.rs
cas/scheduler/tests/property_modifier_scheduler_test.rs
gencargo/property_modifier_scheduler/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/243)

Removed properties should be known to the property manager.

---

cas/cas_main.rs
cas/grpc_service/tests/ac_server_test.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/grpc_service/tests/cas_server_test.rs
cas/scheduler/default_scheduler_factory.rs
cas/store/default_store_factory.rs
config/examples/basic_cas.json
deployment-examples/docker-compose/docker-compose.yml
deployment-examples/docker-compose/local-storage-cas.json
deployment-examples/terraform/scripts/scheduler.json
integration_tests/simple_prometheus_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/229)

Fix prometheus metrics to not publish multiple times

---

cas/grpc_service/bytestream_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
cas/store/ac_utils.rs
cas/store/fast_slow_store.rs

resolves #245
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/250)

Fix bug in BytestreamServer where it would ignore finish_write

---

util/evicting_map.rs

Changes some of the stats published in prometheus in EvictingMap to be more useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/255)

Make stats in EvictingMap more useful

---

Cargo.lock
cas/store/BUILD
cas/store/fast_slow_store.rs
gencargo/fast_slow_store/Cargo.toml

Register the fast and slow metrics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/263)

Implement fast slow metrics.

---

cas/store/tests/filesystem_store_test.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/265)

Fix flakey tests

---

README.md

very minor change to improve clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/249)

improve clarity for getting started.

---

cas/store/grpc_store.rs

Fixes #271
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/273)

Don't download zero size blobs

---

cas/store/filesystem_store.rs
cas/store/tests/ac_utils_test.rs
cas/store/tests/filesystem_store_test.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
util/tests/fs_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/274)

Attempt to fix flaky tests regarding Text file busy error

---

Cargo.lock
cas/store/BUILD
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/tests/fast_slow_store_test.rs
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
gencargo/fast_slow_store/Cargo.toml

Resolves #270
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/272)

Populate the fast store on partial read

---

cas/scheduler/platform_property_manager.rs
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/running_actions_manager_test.rs
config/cas_server.rs

Resolves #261
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/262)

Support injecting property values into entry point command.

---

Cargo.lock
cas/scheduler/BUILD
cas/scheduler/cache_lookup_scheduler.rs
gencargo/cache_lookup_scheduler/Cargo.toml
util/common.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/allada/turbo-cache/279)

Minor optimizations and documentation to CacheLookupScheduler

---

README.md
cas/cas_main.rs
util/fastcdc.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/283)

Change Copyright to Trace Machina, Inc.

---

cas/store/dedup_store.rs

This is an effort to remove spawns that are likely needless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/277)

Remove spawn in dedup store

---

cas/grpc_service/bytestream_server.rs
cas/store/compression_store.rs
cas/store/dedup_store.rs
cas/store/fast_slow_store.rs
cas/store/filesystem_store.rs
cas/store/grpc_store.rs
cas/store/memory_store.rs
cas/store/ref_store.rs
cas/store/s3_store.rs
cas/store/size_partitioning_store.rs
cas/store/store_trait.rs
cas/store/tests/filesystem_store_test.rs
cas/store/verify_store.rs

Makes this(https://github.com/TraceMachina/turbo-cache/issues/288) possible
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/290)

Store::get_part's writer is now a mutable reference.

---

cas/grpc_service/bytestream_server.rs
cas/grpc_service/tests/bytestream_server_test.rs
util/resource_info.rs
util/tests/resource_info_test.rs
util/write_request_stream_wrapper.rs

closes #269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/282)

Refactor resource_info to support v2.3 resource names

---

cas/cas_main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/300)

Prometheus now publishes total client connections since server started and time server started

---

.github/pull_request_template.md

This is a simple PR template that I think we should consider to help people along when they open PRs. It's a bit of overhead for us, but if it slows down the frequency of requests from others it will be worth it long term. It's also quite cookie cutter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/303)

Propose a PR template to help newcomers get started more easily.

---

Cargo.Bazel.lock
Cargo.lock
WORKSPACE
cas/grpc_service/bytestream_server.rs
cas/grpc_service/execution_server.rs
cas/scheduler/tests/utils/mock_scheduler.rs
cas/store/filesystem_store.rs
cas/worker/tests/utils/mock_running_actions_manager.rs
util/evicting_map.rs

Requires minor formatting changes due to updates in rustfmt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/307)

Update rules_rust to 0.29.0

---

cas/cas_main.rs
cas/scheduler/default_scheduler_factory.rs

If we fail to create a scheduler we can't continue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/336)

Remove futures from scheduler_factory

---

cas/cas_main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/337)

Inline format args in cas_main

---

README.md

Standardize on RBE per industry and the docs. 
Docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/364)

RBE consistency.

---

Cargo.Bazel.lock
WORKSPACE
cas/cas_main.rs
cas/scheduler/action_messages.rs
util/common.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/371)

Update Rust version to 1.73.0

---

cas/store/grpc_store.rs

When writing to the GrpcStore retry was not implemented as there was no easy way to rewind the stream.  However, most errors due to high concurrency occur before any data has been written.  Therefore, refactor the GrpcStore::write such that it can retry if the stream has not yet been used.
Fixes #325
High concurrency use of the GrpcStore, no longer producing errors from the ByteStreamServer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/326)

Retry GrpcStore write

---

cas/grpc_service/tests/worker_api_server_test.rs
cas/grpc_service/worker_api_server.rs
cas/scheduler/tests/simple_scheduler_test.rs
cas/scheduler/worker.rs
cas/worker/local_worker.rs
cas/worker/running_actions_manager.rs
cas/worker/tests/local_worker_test.rs
cas/worker/tests/running_actions_manager_test.rs
cas/worker/tests/utils/local_worker_test_utils.rs
cas/worker/tests/utils/mock_running_actions_manager.rs
cas/worker/tests/utils/mock_worker_api_client.rs
cas/worker/worker_api_client_wrapper.rs
cas/worker/worker_utils.rs
proto/BUILD.bazel
proto/com/github/trace_machina/turbo_cache/remote_execution/worker_api.proto
proto/genproto/com.github.trace_machina.turbo_cache.remote_execution.pb.rs
proto/genproto/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/389)

Rename proto organization to trace_machina

---

.github/workflows/pre-commit.yaml
.gitignore
flake.lock
flake.nix
tools/pre-commit-hooks.nix

Does not include any hooks yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/401)

Add pre-commit infrastructure

---

README.md
deployment-examples/docker-compose/Dockerfile
deployment-examples/terraform/AWS/ami.tf

We no longer need this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/412)

Remove OpenSSL from build requirements

---

tools/pre-commit-hooks.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/414)

Add pre-commit hooks for Starlark

---

README.md
native-link-config/README.md
proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto
proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs

After the [rewrite of the build infrastructure](https://github.com/TraceMachina/native-link/commit/3147265047544572e3483c985e4aab0f9fdded38), all path problems are resolved successfully in code files.
But we missed some of them in the documentation.
Updating documentation needs to be done since it needs to be read by users.
Those documentation issues are fixed.
Fixes #415 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/416)

Fix the incorrect config path in the documentation

---

Cargo.lock
native-link-config/src/stores.rs
native-link-store/BUILD.bazel
native-link-store/Cargo.toml
native-link-store/src/default_store_factory.rs
native-link-store/src/existence_store.rs
native-link-store/src/noop_store.rs
native-link-store/tests/existence_store_test.rs
native-link-util/src/buf_channel.rs
native-link-util/src/evicting_map.rs

Refactor Existance Store to be compatible with store API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/418)

Refactor ExistanceStore

---

deployment-examples/docker-compose/README.md

Added README for Docker-Compose deployment example covering setup, configuration, notes & tips.
Fixes #425
-[x] Documentation Update
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/427)

Added README to docker-compose deployment-example

---

native-link-config/src/stores.rs
native-link-store/BUILD.bazel
native-link-store/src/default_store_factory.rs
native-link-store/src/existence_cache_store.rs
native-link-store/src/lib.rs
native-link-store/tests/existence_store_test.rs

Minor changes to ExistanceStore to be more consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/437)

Rename ExistanceStore to ExistanceCacheStore

---

native-link-worker/tests/local_worker_test.rs
native-link-worker/tests/running_actions_manager_test.rs

These didn't work due to issues with bash/echo on MacOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/449)

Fix MacOS tests

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
README.md
WORKSPACE.bazel
error/Cargo.toml
native-link-config/Cargo.toml
native-link-scheduler/Cargo.toml
native-link-service/Cargo.toml
native-link-store/Cargo.toml
native-link-util/Cargo.toml
native-link-worker/Cargo.toml

Also run `cargo upgrade` to bump trivially bumpable deps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/native-link/459)

Bump Rust version to 1.74

---

nativelink-docs/README.md
nativelink-docs/contributing.mdx
nativelink-docs/introduction.mdx
nativelink-docs/logo/dark.svg
nativelink-docs/logo/light.svg
nativelink-docs/mint.json
nativelink-docs/package-lock.json
nativelink-docs/quickstart.mdx

Also fix some remaining `native-link` occurrences.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/482)

Fix pre-commit hooks after 378b806

---

nativelink-store/src/fast_slow_store.rs
nativelink-store/tests/fast_slow_store_test.rs

Currently we send the EOF to the fast store and the requester at the same time. The bytestream_server drops the get_part future as soon as it receives the EOF which means that the fast store doesn't get time to sync and populate.
This is resolved by only sending the EOF to the requestor in the fast_slow_store once all of the futures have completed.  The alternative is to spawn for the fast store or to complete the get_part future in bytestream_server, but this seems like the least heavy weight solution which doesn't require thought by the user.
Fixes #478
Testing with long latency link between two instances.
- - - …

Avoid writer EOF until fast store complete

---

.github/workflows/codeql.yaml

This scans the Python and javascript/typescript files in the repository. At the moment this is mostly a no-op but it provides a decent foundation for future changes around documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/484)

Add CodeQL scanning for Python and JS/TS

---

.github/workflows/scorecard.yaml

Ensure that we follow some security best practices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/486)

Add OpenSSF scorecard action

---

nativelink-proto/genproto/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/489)

Update protos after 1aadd42

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
nativelink-error/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/488)

Bump trivially bumpable deps

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE.bazel
nativelink-error/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-proto/genproto/build.bazel.remote.execution.v2.pb.rs
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-proto/genproto/google.api.pb.rs
nativelink-proto/genproto/google.bytestream.pb.rs
nativelink-proto/genproto/google.longrunning.pb.rs
nativelink-proto/genproto/google.rpc.pb.rs
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-util/src/action_messages.rs
nativelink-util/src/digest_hasher.rs
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/493)

Update protobuf dependencies

---

nativelink-docs/mint.json

Integrates google analytics into the documentation site to monitor user activity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/503)

Integrate Google Analytics

---

.github/workflows/codeql.yaml
.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/sanitizers.yaml
.github/workflows/scorecard.yaml

Run on fast machine.
CI stinks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/511)

Update native-cargo.yaml Runner Group

---

.github/workflows/native-cargo.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/514)

Remove beta toolchain from native Cargo builds

---

.github/workflows/codeql.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/scorecard.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/516)

Scale back a few CI runs

---

src/bin/cas.rs

Looking to implement an idea from Blaise. I need to add a test. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/510)

Increase the Max Blocking Threads

---

src/bin/cas.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/520)

Fix rustfmt after 6d07a86

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/521)

Add fancy badges

---

.github/workflows/nix.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/524)

Mark nix-cargo and bazel tests as large ci instances

---

CHANGELOG.md
Cargo.Bazel.lock
Cargo.lock
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/533)

Release nativelink 0.1.0

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/558)

Update OSSF domain

---

nativelink-docs/quickstart.mdx

A user kicking the tires found a typo and alerted someone who alerted me a couple minutes ago.  Thanks to that person. 
Fixes #(unfiled)
Typo fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/560)

Fix a Quickstart Typo

---

flake.nix
local-remote-execution/image.nix
local-remote-execution/rbe-configs-gen.nix
tools/customClang.nix
tools/generate-toolchains.nix
tools/llvmStdenv.nix
tools/local-image-test.nix
tools/pre-commit-hooks.nix
tools/publish-ghcr.nix

Alejandra formats, statix lints antipatterns, deadnix scans dead code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/561)

Add Nix formatters and linters to pre-commit hooks

---

nativelink-docs/deployment-examples.mdx
nativelink-docs/mint.json

Add terraform deployment examples to docs.
Fixes #581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/584)

Add deployment examples to docs

---

nativelink-docs/docs/deployment-examples/Kubernetes-Deployment.mdx

Adds Kubernetes instructions to docs and labels them as experimental
Fixes #593 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/596)

Add Kubernetes Example to docs

---

README.md
nativelink-docs/docs/Quickstart.mdx

Add warnings to README and documentation for users building from source and updated cargo emoji.
Fixes #592
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/599)

Add artifact warning to documentation and swap out cargo emoji

---

Cargo.Bazel.lock
Cargo.lock
WORKSPACE.bazel
flake.lock
flake.nix
nativelink-store/src/grpc_store.rs
nativelink-util/src/evicting_map.rs

This includes a few dependency updates and a small clippy fix for the latest nightly clippy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/588)

Update rules_rust to 0.36.2

---

.github/workflows/lre.yaml

This makes it easier to spot when/why something is failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/614)

Separate K8s setup steps in CI

---

.github/workflows/image.yaml
.github/workflows/lre.yaml

Fixes #611
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/619)

Disable flaky caching for LRE-Remote workflow

---

nativelink-util/src/tls_utils.rs

Tonic has changed its behaviour such that the TLS configuration is ignored within transport/service/connector.rs if the scheme isn't https.  Firstly, add support for grpcs scheme by swapping it out in the endpoint Uri if set. Secondly, add a warning to the unsuspecting user that sets the TLS configuration, but not the correct scheme.
I spent a long time trying to figure out why my TLS configuration wasn't working with the Tonic upgrade to 0.10.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/609)

Add warning for TLS

---

run_integration_tests.sh

Throughout the codebase, there are a number of scripts that either need to be invoked or are invoked automatically on the user's behalf. We need to reduce the friction associated with a number of these errors as they are somewhat opaque. 
Fixes #624 
Developer Experience
Both shell scripts and integration tests are notoriously difficult to test so I have not put much thought into it. Maybe we will be there in the future and can revisit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/625)

Helpful Error Output for Integration Test

---

Cargo.lock

Fixes https://github.com/TraceMachina/nativelink/security/dependabot/23
Fixes https://github.com/TraceMachina/nativelink/security/dependabot/24
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/629)

[Security] Bump trivially bumpable deps

---

local-remote-execution/README.md

Improve the Local Remote Execution README as a continuation of the effort to simplify the documentation in the repository. 
Through hacking.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/637)

Improve the LRE README

---

nativelink-store/src/fast_slow_store.rs
nativelink-store/tests/fast_slow_store_test.rs

If there's a value in the fast store, but it's been removed from the slow store and the slow store happens to require that value because it's being used for the execution, then this causes the execution to fail.  Add an option to make checks on the store go to the slow store every time to ensure it has the values.  Serving still comes from the fast store.
Tested on local cluster and added new test for the change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/633)

Ignore fast store

---

nativelink-service/src/bytestream_server.rs
nativelink-service/tests/bytestream_server_test.rs

The ByteStreamServer write was amended to enable resuming of sessions.  However, Reclient just starts from the begining again.  This would be fine, except we expect it to resume.  Add in a check to see if the first message is the beginning (i.e. its write_offset is zero) and then force a new IdleStream to be created for it.
Reclient build testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/635)

Allow ByteStream write restart

---

deployment-examples/terraform/experimental_AWS/ami.tf

Fix AMI NativeLink Tarballing of a release so that it works for AWS.
Fixes #644
I ran it a few times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/645)

Fix AWS Terraform (Tarball Operation)

---

nativelink-store/src/grpc_store.rs

If a read request fails, it is retried in GrpcStore::read, however if a stream
breaks while it's being read from then it is not retried.  Therefore, break
the read retry logic from the get_part_ref retry logic to allow a read to
resume from where it left off.
Tested in local cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/646)

Retry GrpcStore get_part_ref

---

README.md

In the beginning, there were clear instructions for users that had the problems addressed by NativeLink but were not necessarily Rust users. Rust is an implementation detail and Rust knowledge cannot be a pre-requisite.
Getting started ticket
User interviews
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/648)

Re-Add Rustup to the README

---

nativelink-docs/docs/Quickstart.mdx

Fixes #652
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/654)

Fix cargo install tag and start command

---

src/bin/nativelink.rs

Fixes #655
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/660)

Autogenerate version from Cargo.toml

---

nativelink-store/src/ac_utils.rs
nativelink-store/src/verify_store.rs
nativelink-store/tests/completeness_checking_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-util/src/digest_hasher.rs
nativelink-util/src/store_trait.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/running_actions_manager_test.rs

Minor change to cleanup the way we deal with the hashing functions to be flexible and easier to work with.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/691)

Cleanup hash functions to be more idomatic

---

deployment-examples/docker-compose/Dockerfile
tools/pre-commit-hooks.nix

This hardens the Dockerfile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/422)

Add hadolint to pre-commit hooks

---

nativelink-docs/docusaurus.config.js
nativelink-docs/package.json
nativelink-docs/yarn.lock

Add basic search functionality to documentation now that it is getting more complex.
Preview Deployment: [nativelink-docs-git-fork-blakehat-9b6242-native-link-web-assets.vercel.app](https://vercel.live/link/nativelink-docs-git-fork-blakehat-9b6242-native-link-web-assets.vercel.app?via=deployment-domains-list-branch)
Fixes #739 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/740)

Add search functionality to docs

---

nativelink-docs/package.json
nativelink-docs/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/753)

Update TypeScript dependencies

---

nativelink-docs/yarn.lock

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/766)

Update js dependencies in docs

---

.github/workflows/nix.yaml
nativelink-store/src/completeness_checking_store.rs

Just a formatting issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/769)

Unbreak CI

---

tools/publish-ghcr.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/777)

Fix image publishing workflow after 1a43ef9

---

.github/workflows/native-cargo.yaml

Fixes #773
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/775)

Don't update rustup in native Cargo workflow

---

.bazelrc
nativelink-scheduler/src/worker.rs
nativelink-service/src/ac_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/src/capabilities_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-service/tests/ac_server_test.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/ac_utils.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/tests/ac_utils_test.rs
nativelink-store/tests/cas_utils_test.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/src/common.rs
nativelink-util/src/fastcdc.rs
nativelink-util/src/fs.rs
nativelink-util/src/health_utils.rs
nativelink-util/src/metrics_utils.rs
nativelink-util/src/resource_info.rs
nativelink-util/src/store_trait.rs
nativelink-util/tests/buf_channel_test.rs
nativelink-util/tests/fs_test.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

Much more readable. The new setting is enforced for Bazel tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/789)

Globally inline format args

---

nativelink-docs/yarn.lock

Update node dependencies for docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/805)

Update node dependencies

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
README.md

added mac os warning
Fixes #729 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/803)

Update README for More Clarity

---

nativelink-docs/docs/Configuration.mdx

Points to the main repo in documentation rather than a personal fork, which may fall out of date. XXS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/822)

[Docs Site] Update Configuration.mdx

---

README.md

We need to make the software and the community more accessible. Adds a badge for license and Slack channel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/841)

Update README.md to include License and Slack

---

.github/workflows/tagged_image.yaml
tools/publish-ghcr.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/844)

Fix semver image workflow after 646253d

---

deployment-examples/chromium/03_build_chrome_tests.sh

Fixes a minor typo in the chrome tests bash script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/856)

Fix a typo in the script comments

---

deployment-examples/chromium/README.md

Warn about Nix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/865)

Warn people about Nix in Chrome README.md

---

CONTRIBUTING.md

This should help new contributors to get started more easily. The new guidelines are more explicit than the previous ones and go into more detail on common development workflows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/827)

Rewrite contribution documentation

---

nativelink-store/src/fast_slow_store.rs

Adds metrics on what store was being hit in FastSlowStore.
towards: #650
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/884)

Add hit metrics to FastSlowStore

---

nativelink-store/src/completeness_checking_store.rs

CompletenessCheckingStore will now publish metrics about the underlying store.
towards: #650
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/882)

Add metrics to CompletenessCheckingStore

---

.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yml
.github/workflows/nix.yaml
.github/workflows/pre-commit.yaml
.github/workflows/tagged_image.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/879)

Update Nix installers in CI

---

nativelink-docs/docusaurus.config.js
nativelink-docs/static/img/dark.svg
nativelink-docs/static/img/favicon.svg
nativelink-docs/static/img/light.svg

Updates the favicon and header images for docs.nativelink.com
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/930)

Update images for docs

---

deployment-examples/docker-compose/Dockerfile

Fixes #939
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/940)

Unbreak docker-compose workflow

---

nativelink-config/examples/redis.json
nativelink-config/src/stores.rs

include relevant motivation and context
#958 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/967)

Add JSON config examples to store.rs

---

nativelink-scheduler/tests/cache_lookup_scheduler_test.rs
nativelink-store/src/default_store_factory.rs
nativelink-store/src/memory_store.rs
nativelink-store/tests/ac_utils_test.rs
nativelink-store/tests/completeness_checking_store_test.rs
nativelink-store/tests/compression_store_test.rs
nativelink-store/tests/dedup_store_test.rs
nativelink-store/tests/existence_store_test.rs
nativelink-store/tests/fast_slow_store_test.rs
nativelink-store/tests/memory_store_test.rs
nativelink-store/tests/ref_store_test.rs
nativelink-store/tests/shard_store_test.rs
nativelink-store/tests/size_partitioning_store_test.rs
nativelink-store/tests/verify_store_test.rs
nativelink-util/tests/default_store_key_subscribe_test.rs
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

This will make memory store much more efficient for cases where subscribe is used.
closes #987
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nativelink/nativelink/988)

Add memory store optimized subscription API

---

nativelink-docs/package.json
nativelink-docs/yarn.lock

Fixes CVE-2024-4068
Fixes CVE-2024-37168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1015)

Bump yarn deps

---

.github/workflows/lre.yaml
.github/workflows/native-bazel.yaml
.github/workflows/nix.yaml
deployment-examples/docker-compose/Dockerfile

Let's see if this fixes CI, shall we?
We're running CI on it right now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1024)

Update git to 1:2.25.1-1ubuntu3.13 and add "free disk space" CI step

---

nativelink-config/src/stores.rs
nativelink-service/src/bep_server.rs
nativelink-service/tests/bep_server_test.rs
nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

This optional publisher for stores writes is a cleaner, more flexible, and simpler alternative to using keyspace notifications.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1027)

Add optional pub sub publisher to store writes

---

nativelink-config/src/cas_server.rs
src/bin/nativelink.rs

This disambiguates it from `stores::CompressionAlgorithm`.
Fixes #1049
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1052)

Rename cas CompressionAlgorithm to HttpCompressionAlgorithm

---

nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-scheduler/src/simple_scheduler.rs

Fixes https://github.com/TraceMachina/nativelink/issues/1067
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1068)

[Refactor] Workers::find_worker_for_action to use PlatformProperties

---

README.md

Added the Repobeats project. It's requested by Krish.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1077)

Reorder `README`

---

README.md
docs/scripts/md_to_mdx.ts

Improved links and branding in the primary README to boost conversion rate on growth efforts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1074)

Improve README branding and links

---

nativelink-config/src/cas_server.rs
nativelink-service/tests/bytestream_server_test.rs

Cleanup and fix test_configured_default_limits so it actually tests what it was designed to test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1087)

Fix bystream_server_tests

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
.vale.ini
docs/src/content/docs/explanations/history.mdx
docs/src/content/docs/reference/glossary.mdx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1086)

Fix vale issues in MDX files

---

nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/client_action_state_result.rs
nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs
nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/BUILD.bazel
nativelink-service/src/execution_server.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-store/tests/cas_utils_test.rs
nativelink-util/src/action_messages.rs

Introduces various code quality improvements to scheduler-v2 which allow bazel test to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1092)

QA fixes for scheduler-v2

---

nativelink-scheduler/src/scheduler_state/awaited_action.rs
nativelink-scheduler/src/scheduler_state/state_manager.rs

Update naming and documentation around upgrading priority
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1112)

Rename set_priority to upgrade_priority

---

native-cli/components/flux.go
native-cli/programs/local.go

Preparation for the NativeLink operator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1096)

Add Flux to development cluster

---

nativelink-scheduler/src/scheduler_state/workers.rs
nativelink-service/src/execution_server.rs

Worker stream now properly terminated on action complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1114)

Fix worker execution issues

---

nativelink-config/src/cas_server.rs

self-explanatory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1099)

Converted Single Defaults from Plural

---

.vale.ini
README.md
docs/.gitignore
docs/README.md
docs/astro.config.mjs
docs/scripts/md_to_mdx.ts
docs/scripts/md_to_mdx_aot.ts
docs/src/content/docs/contribute/bazel.mdx
docs/src/content/docs/contribute/cargo.mdx
docs/src/content/docs/contribute/nix.mdx
docs/src/content/docs/explanations/architecture.mdx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1127)

Move installation instructions to new docs

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1132)

Fix README after 612b86e

---

nativelink-scheduler/src/simple_scheduler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1139)

Rename workers to `worker_scheduler`

---

nativelink-scheduler/src/simple_scheduler.rs
nativelink-worker/tests/running_actions_manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1141)

Fix test on running_actions_manager_test

---

docs/scripts/md_to_mdx.ts
docs/scripts/metaphase.ts

Fixes caution rendering and adds an extra warning about auto-generation in the config autogen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1147)

Fix script bugs

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1149)

Fix an accessibility issue in the README

---

nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/memory_awaited_action_db.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1162)

Fix sequence bug in new memory store manager

---

.bazelrc
nativelink-scheduler/tests/simple_scheduler_test.rs
nativelink-service/src/capabilities_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/ac_utils.rs
nativelink-util/src/action_messages.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1106)

Fix clippy::manual_string_new

---

nativelink-util/src/store_trait.rs

Retreives -> Retrieves
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1184)

chore: update store_trait.rs

---

Cargo.lock
Cargo.toml
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-metric/nativelink-metric-macro-derive/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

Detected from `cargo-features-manager`. Marked `blake3` as a special cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1211)

Remove unused features in dependencies

---

Cargo.lock
Cargo.toml
nativelink-config/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-proto/genproto/build.bazel.remote.execution.v2.pb.rs
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-proto/genproto/google.bytestream.pb.rs
nativelink-proto/genproto/google.devtools.build.v1.pb.rs
nativelink-proto/genproto/google.longrunning.pb.rs
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

A fix outlined here:
https://github.com/ToBinio/cargo-features-manager/issues/37
This change is to make nativelink compatible with those changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1212)

Make Cargo.toml feature pins compatible with project/main

---

flake.nix
tools/create-worker-experimental.nix

Creating an experimental toolchain that contains clang/rust/go. 
Fixes https://github.com/TraceMachina/nativelink/issues/1201
```
nix build .#nativelink-worker-buck2-toolchain.copyToDockerDaemon
docker run -it <hash> /bin/sh
sh-5.2$ clang --version
clang version 17.0.6
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/c0za00cgiclxd41cz72qlxvw845hgp4f-clang-17.0.6/bin
sh-5.2$ rustc --version
rustc 1.79.0-nightly (aed2187d5 2024-04-27)
sh-5.2$ go version
go version go1.22.5 linux/amd64
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1200)

Example clang/rust/go toolchain

---

Cargo.toml
nativelink-store/src/dedup_store.rs
nativelink-store/src/redis_store.rs
nativelink-store/src/s3_store.rs
nativelink-util/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1231)

Fix compile time warnings from rustc version upgrade

---

.github/workflows/image.yaml
.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1240)

Remove some needless CI tests

---

docs/src/content/docs/faq/lre.mdx

In this PR, I modified the LRE file path and instead of keeping `lre.mdx`, I removed the `.mdx` extension from it.
**Here is a problem**
Even if the `.mdx` is removed, the page still shows me a `404 page not found error`. First of all, there is no `lre.mdx` file in the explanations directory; the second point is that a `README.md` file is present in the `local-remote-execution` containing the LRE content.
What did I do?
1. I tried to give a path of the `local-remote-execution/README.md` file but it gave me this error.
- You can see there is a `404` error.
- Plus the next and the previous page links are also gone that are normally present in the `404` error page
2. I created a `lre.mdx` file in the explanations directory but it gave me this error.
Now let me know what are the improvements …

modified the lre file path

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
Cargo.toml
MODULE.bazel
README.md
cliff.toml
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1252)

Release NativeLink v0.5.1

---

README.md

Just added YouTube to ReadMe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1254)

Add 90s Explainer to README.md

---

README.md
docs/scripts/md_to_mdx_aot.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1261)

add static size and fix meta-typo

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
Cargo.toml
MODULE.bazel
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1283)

Release NativeLink v0.5.2

---

nativelink-store/src/s3_store.rs

S3Store was not retrying under some conditions if the s3 side of the stream closed. This will make S3Store a bit more stable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1302)

S3 store will now retry more aggresively

---

nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs

To help with pre-work needed for redis scheduler we make this struct usable in mods outside of MemoryAwaitedActionDb.
towards #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1305)

Move ClientActionStateResult to SimpleSchedulerStateManager

---

.github/workflows/docs.yaml

Pass deno deploy token
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1321)

Pass deno deploy token

---

.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/nix.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1323)

Disable various test for docs only PRs

---

docs/src/content/docs/nativelink-cloud/rbe.mdx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1324)

Update RBE docs for private image repository headers

---

.github/workflows/scorecard.yaml

Fixes #1329
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1330)

Bump the scorecard action

---

.github/workflows/docs.yaml
docs/src/content/docs/nativelink-cloud/rbe.mdx

Update Cloud RBE docs for private image repositories and advanced config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1333)

Update Cloud RBE docs for private image repositories and advanced config

---

CONTRIBUTING.md
README.md
SECURITY.md
deployment-examples/chromium/README.md
deployment-examples/kubernetes/README.md
local-remote-execution/README.md

Currently, when Markdown Linting is run, there are some minor format issues in markdown files. Checked all markdown files and fixed all relevant issues in them.
Detailed issues can be find in the link below.
Fixes #1331 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1332)

Fix format issues in markdown files

---

nativelink-service/src/bytestream_server.rs
nativelink-service/tests/bytestream_server_test.rs

If a client tries to upload a file, but the first payload fails, the client may call query_write_status(), which we now return "0" (no data received yet) instead of NotFound to increase compatibility with clients.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1341)

ByteStreamServer now responds with no-data-received instead of NotFound

---

nativelink-scheduler/BUILD.bazel
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/lib.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/store_trait.rs

This is pre-work for the introducing a distributed redis scheduler. This is the API for how to interact between the scheduler and the stores.
towards: #359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1342)

Add StoreAwaitedActionDb API

---

docs/src/content/docs/nativelink-cloud/rbe.mdx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1350)

Update docs for RBE exec properties to support GPU etc.

---

README.md

Update the version in the README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1351)

Update README.md with newest version

---

deployment-examples/docker-compose/Dockerfile

Fixes #1366
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1367)

Fix broken ca-certificates version in integration tests

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1374)

Enable Nativelink Cloud Cache workflow for macos-14

---

.bazelrc
nativelink-metric/nativelink-metric-macro-derive/src/lib.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-service/tests/worker_api_server_test.rs
nativelink-store/src/size_partitioning_store.rs
nativelink-store/src/verify_store.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1361)

Fix clippy::manual_let_else

---

.bazelrc
nativelink-metric/nativelink-metric-macro-derive/src/lib.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-service/src/cas_server.rs
nativelink-store/src/redis_store.rs
nativelink-store/src/redis_utils/ft_aggregate.rs
nativelink-util/src/evicting_map.rs
nativelink-util/src/fastcdc.rs
nativelink-util/src/origin_context.rs
nativelink-util/src/store_trait.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1379)

Fix clippy::single_match_else

---

.bazelrc
nativelink-store/src/redis_store.rs
nativelink-store/tests/shard_store_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1392)

Fix clippy::unreadable_literal

---

.bazelrc
nativelink-service/src/bytestream_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-util/src/action_messages.rs
nativelink-util/src/common.rs
nativelink-util/src/connection_manager.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1412)

Fix clippy::inconsistent_struct_constructor

---

.bazelrc
nativelink-metric-collector/src/tracing_layers.rs
nativelink-store/src/cas_utils.rs
nativelink-store/src/size_partitioning_store.rs
nativelink-worker/tests/utils/mock_running_actions_manager.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1411)

Fix clippy::match_wildcard_for_single_variants

---

.bazelrc
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-store/src/filesystem_store.rs
nativelink-store/src/grpc_store.rs
nativelink-store/src/s3_store.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1384)

Fix clippy::implicit_clone

---

.bazelrc
nativelink-metric-collector/src/tracing_layers.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/src/evicting_map.rs
nativelink-util/src/store_trait.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1410)

Fix clippy::explicit_deref_methods

---

.bazelrc
nativelink-scheduler/src/awaited_action_db/awaited_action.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-store/src/redis_store.rs
nativelink-util/src/retry.rs
src/bin/nativelink.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1416)

Fix clippy::trivially_copy_pass_by_ref

---

.bazelrc
nativelink-metric-collector/tests/metric_collector_test.rs
nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-service/tests/worker_api_server_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1409)

Fix clippy::unnecessary_wraps

---

.bazelrc
nativelink-service/tests/cas_server_test.rs
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/src/shard_store.rs
nativelink-store/tests/compression_store_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1426)

Fix clippy::cast_lossless

---

nativelink-worker/tests/running_actions_manager_test.rs

Injects PATH env at appropriate times in tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1427)

Fix tests to support nixos pathing

---

.bazelrc
nativelink-service/src/execution_server.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1415)

Fix clippy::map_unwrap_or

---

.bazelrc
nativelink-store/tests/ref_store_test.rs
nativelink-util/src/origin_context.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1430)

Fix clippy::ref_as_ptr

---

.bazelrc
nativelink-util/src/task.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1431)

Fix clippy::inline_always

---

.bazelrc
nativelink-scheduler/src/simple_scheduler_state_manager.rs
nativelink-store/src/redis_utils/ft_aggregate.rs
nativelink-util/src/resource_info.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1432)

Fix clippy::redundant_else

---

.bazelrc
nativelink-util/src/health_utils.rs
nativelink-util/src/store_trait.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1435)

Fix clippy::return_self_not_must_use

---

web/platform/src/components/qwik/components/footer.tsx
web/platform/src/components/qwik/pages/company.tsx
web/platform/src/components/qwik/sections/benefits.tsx
web/platform/src/components/qwik/sections/community.tsx
web/platform/src/components/qwik/sections/hero.tsx
web/platform/src/content/posts/Announcement_NativeLink.md
web/platform/src/content/posts/Announcement_TraceMachina_Seedfunding.md
web/platform/src/content/posts/CaseStudy_CIQ.md
web/platform/src/content/posts/CaseStudy_Samsung.md
web/platform/src/pages/compliance.astro
web/platform/starlight.conf.ts

Transition static content from wix to s3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1440)

Add static content from s3 bucket to web platform

---

.github/workflows/lre.yaml

The previous variant didn't work for pushes on main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1441)

Fix LRE/Remote workflow after b44383f

---

.github/workflows/lre.yaml
web/platform/src/content/docs/docs/deployment-examples/chromium.mdx
web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx

The previous implementation didn't correctly resolve the repo URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1443)

Really fix LRE/Remote workflow after b44383f

---

web/platform/src/components/qwik/components/header.tsx
web/platform/src/components/qwik/components/video.tsx
web/platform/src/layouts/Layout.astro
web/platform/src/pages/product.astro

Transition remaining static content to the new s3 nativelink-cdn
`bun dev`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1444)

Move remaining static content to s3

---

web/platform/src/components/qwik/pages/company.tsx

Update the company site on the web platform
`bun dev` && `bun preview`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1451)

Update company site on web platform

---

.bazelrc
nativelink-metric/src/lib.rs
nativelink-service/src/cas_server.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1453)

Fix clippy::explicit_iter_loop

---

.github/workflows/lre.yaml

Fixes #1454
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1455)

Correctly wait for LRE/Remote tekton pipelines

---

.github/styles/alex/README.md
.github/styles/write-good/README.md
deployment-examples/docker-compose/README.md
kubernetes/README.md
local-remote-execution/README.md
nativelink-config/README.md
nativelink-config/examples/README.md
web/platform/README.md

Add Matomo analytics to rest of public READMES
Extension of #1450
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1460)

Add Matomo tracking pixel to rest of public READMEs

---

web/platform/astro.config.ts
web/platform/src/thirdParty/GoogleTagManager.astro

Nothing to see
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1467)

Adds Analytics to Data Layer

---

web/platform/src/content/docs/docs/introduction/on-prem.mdx

Fix broken links on docs/introduction/on-prem site
`bun dev` && `bun run build`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1480)

Fix Broken Links on docs/introduction/on-prem

---

web/platform/src/components/qwik/sections/hero.tsx

Fix the broken video link on the homepage
Fixes #1487
`bun dev`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1488)

Fix broken video link

---

nativelink-service/src/bytestream_server.rs
nativelink-store/src/grpc_store.rs
nativelink-util/src/proto_stream_utils.rs
src/bin/nativelink.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1492)

Cleanup some template type definitions

---

flake.nix

- Remove obsolete {stable|nightly}-rust-native toolchains
- Inline maybeDarwinDeps for host
- Simplify unnecessarily complicated if-else statement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1515)

Slightly clean up flake

---

web/platform/src/pages/terms.astro

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1517)

Update terms on web/platform

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
web/platform/src/content/posts/NativeLink_for_Semiconductors.md

This is a blog post for the semiconductor industry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1518)

Semiconductor blog

---

README.md
deployment-examples/docker-compose/docker-compose.yml
deployment-examples/docker-compose/local-storage-cas.json5
deployment-examples/docker-compose/scheduler.json5
deployment-examples/docker-compose/worker.json5
kubernetes/base/nativelink.yaml
kubernetes/base/worker.yaml
kubernetes/configmaps/kustomization.yaml
kubernetes/configmaps/nativelink-config.json5
kubernetes/configmaps/worker.json5
kubernetes/overlays/lre/worker-lre-cc.yaml
nativelink-config/examples/basic_cas.json5
nativelink-config/examples/filesystem_cas.json5
nativelink-config/examples/s3_backend_with_local_fast_cas.json5

Rename json to jsonc, which is just json with comments.
Fixes #1507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1508)

Rename example configs to json5

---

Cargo.lock
nativelink-metric-collector/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1540)

Fix `cargo test -p nativelink-store` after 4896b5c

---

nativelink-scheduler/src/memory_awaited_action_db.rs
nativelink-scheduler/src/store_awaited_action_db.rs
nativelink-scheduler/tests/simple_scheduler_test.rs

Fix case when an action is scheduled, then disconnected, then sits in an idle stat until it is considered
timed out, then it gets joined onto another client, the matching engine logic will mark it timed out before the client is able to mark it keep_alive.
closes: #1568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1569)

Fix bug where actions rarely get timed out on rejoin

---

nativelink-proto/com/github/trace_machina/nativelink/remote_execution/events.proto
nativelink-proto/genproto/com.github.trace_machina.nativelink.events.pb.rs
nativelink-util/src/origin_event.rs
nativelink-util/tests/origin_event_test.rs

Adds an event for when a stream is closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1570)

Add `Closed` stream event to OriginEvents

---

CHANGELOG.md
Cargo.lock
Cargo.toml
MODULE.bazel
README.md
native-cli/default.nix
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-metric/nativelink-metric-macro-derive/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml
web/platform/utils/md_to_mdx.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1572)

Release NativeLink v0.5.4

---

Cargo.lock
nativelink-macro/src/lib.rs
nativelink-scheduler/Cargo.toml
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-service/Cargo.toml
nativelink-service/src/worker_api_server.rs
nativelink-store/Cargo.toml
nativelink-store/src/grpc_store.rs
nativelink-store/src/s3_store.rs
nativelink-store/tests/ac_utils_test.rs
nativelink-store/tests/dedup_store_test.rs
nativelink-store/tests/filesystem_store_test.rs
nativelink-util/Cargo.toml
nativelink-util/src/common.rs
nativelink-util/src/origin_event.rs
nativelink-util/tests/fastcdc_test.rs
nativelink-worker/Cargo.toml
nativelink-worker/tests/local_worker_test.rs
nativelink-worker/tests/running_actions_manager_test.rs

Upgrades the rand crate version and ensures that every new test
gets a new random seed by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1583)

Upgrade rand crate version and stabalize test rand generation

---

nativelink-store/src/grpc_store.rs

GrpcStore will now properly send the digest function over Grpc from the origin context. Previously this had to be set in the config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1587)

GrpcStore now sends digest function from context

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1601)

Change remote exec CI to new endpoints

---

nativelink-store/src/grpc_store.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1602)

Remove GrpcStore from health checker registry

---

.gitignore
nativelink-config/examples/README.md

Fixes # ([1610](https://github.com/TraceMachina/nativelink/issues/1610))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1611)

Update config readme to reflect new store and scheduler 

---

CHANGELOG.md
Cargo.lock
Cargo.toml
MODULE.bazel
README.md
cliff.toml
native-cli/default.nix
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-metric/nativelink-metric-macro-derive/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1604)

Release NativeLink v0.6.0

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
web/platform/src/content/posts/CaseStudy_ThirdwaveAutomation.md

Adds Thirdwave Automation case study
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1615)

Add Thirdwave Automation case study

---

web/platform/src/components/qwik/pages/company.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1617)

Adjust team to show leaders

---

Cargo.lock
Cargo.toml
nativelink-config/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric-collector/tests/metric_collector_test.rs
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/BUILD.bazel
nativelink-store/Cargo.toml
nativelink-store/src/s3_store.rs
nativelink-store/tests/s3_store_test.rs
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

Also bumps some other trivially bumpable deps.
Fixes RUSTSEC-2025-0009
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1620)

Bump AWS SDK for Rust

---

kubernetes/resources/gateway-routes/routes.yaml
native-cli/components/cilium.go
native-cli/programs/local.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1631)

Bump Cilium to 1.17.2

---

native-cli/programs/local.go

Fixes #1643 
On Linux (NixOS, x86).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1644)

Start cilium before capacitor

---

local-remote-execution/README.md
web/platform/README.md
web/platform/src/content/docs/docs/faq/lre.mdx
web/platform/src/content/docs/docs/faq/remote-execution.mdx
web/platform/src/content/docs/docs/introduction/non-bre.mdx
web/platform/src/content/docs/docs/nativelink-cloud/Reclient.mdx
web/platform/src/content/docs/docs/nativelink-cloud/rbe.mdx

A few links in the documentation were broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1655)

Fix links in documentation

---

README.md
web/platform/src/components/qwik/components/cards.tsx
web/platform/src/components/qwik/components/footer.tsx
web/platform/src/components/qwik/pages/company.tsx

Miscellaneous changes to the website, as requested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1658)

Fix website nits

---

nativelink-error/src/lib.rs

There is not need to use a custom type here. Also removes some unused existing trait implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1656)

Remove indirection for wrapping tonic error codes

---

Cargo.lock
Cargo.toml
flake.nix
nativelink-error/Cargo.toml
nativelink-metric-collector/Cargo.toml
nativelink-metric-collector/tests/metric_collector_test.rs
nativelink-proto/Cargo.toml
nativelink-proto/genproto/build.bazel.remote.asset.v1.pb.rs
nativelink-proto/genproto/build.bazel.remote.execution.v2.pb.rs
nativelink-proto/genproto/com.github.trace_machina.nativelink.remote_execution.pb.rs
nativelink-proto/genproto/google.bytestream.pb.rs
nativelink-proto/genproto/google.devtools.build.v1.pb.rs
nativelink-proto/genproto/google.longrunning.pb.rs
nativelink-scheduler/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-util/src/connection_manager.rs
nativelink-worker/Cargo.toml
src/bin/nativelink.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1674)

Update Rust dependencies

---

nativelink-util/src/origin_context.rs

The previous implementation appears to avoid undefined behavior as written given that the pointer was never actually used. Even so, the implementation of `Send` and `Sync` for `RawSymbolWrapper` was unsound as there were no checks to ensure this would always be the case. On the contrary, the pointer could trivially be accessed and dereferenced, falsely relying on the `Send`/`Sync` implementations.
The new implementation accomplishes the same behavior by exposing the address of the pointer and storing that. This approach ensures that anyone attempting to access the data at that address must first create a pointer, at which point *they* are responsible for ensuring soundness invariants (namely thread safety) when dereferencing.
not work as …

Ensure soundness of, rename `RawSymbolWrapper`

---

native-cli/components/embedded/envoy.template.yaml
native-cli/components/loadbalancer.go
native-cli/programs/local.go
web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx

Also updates documentation around NixOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1670)

Update native-cli loadbalancer and flux

---

web/platform/src/content/docs/docs/nativelink-cloud/rbe.mdx

Add accurate information about the ECR use for private registries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1667)

Update ECR private registry docs

---

tools/pre-commit-hooks.nix

Remove custom entry points of the default hooks and use default names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1723)

Use default hooks

---

nativelink-service/tests/bytestream_server_test.rs

This PR adds a simple test to exercise what happens when a message too large for the bytestream_server is sent. While it should not happen, we need to test against its handling to improve coverage and preempt regressions. 
Here is the branch being tested:
https://github.com/TraceMachina/nativelink/blob/1d944178ec309fd97681688014a2ebc2e6d9969c/nativelink-service/src/bytestream_server.rs#L486-L488
Fixes #1401 (very slightly). It will never be fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1721)

Test bytestream message too large

---

README.md

Removes unnecessary photos to keep our page loading time low.
Preview of README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1733)

Remove unnecessary photos

---

nativelink-store/README.md

We need to to start to support more stores as more and more companies start to adopt the platform. It would be helpful if our customers and our community had a bit more detailed information about the store module. This will improve understanding of the system and overall usability. 
Fixes #1738 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1739)

Add store README

---

deploy/chromium-example/build_chromium_tests.sh
integration_tests/simple_cache_test.sh
integration_tests/simple_remote_execution_test.sh
integration_tests/simple_tls_test.sh
local-remote-execution/generated-cc/cc/cc_wrapper.sh
local-remote-execution/generated-cc/cc/validate_static_library.sh
run_integration_tests.sh
tools/pre-commit-hooks.nix
tools/toolchain-buck2/toolchain-buck2.sh
tools/toolchain-drake/toolchain-drake.sh
tools/toolchain-nativelink/toolchain-nativelink.sh
tools/tsan.sh

Use the default `shfmt` pre-commit hook with 4 spaces indent and spaces around redirects.
Keep https://github.com/mvdan/sh#caveats in mind.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1749)

Add shfmt to lint shell scripts

---

.github/workflows/coverage.yaml
.github/workflows/image.yaml
.github/workflows/lre.yaml
.github/workflows/main.yaml
.github/workflows/native-bazel.yaml
.github/workflows/native-cargo.yaml
.github/workflows/nix.yaml
.github/workflows/sanitizers.yaml
.github/workflows/templates.yaml

Changes in `web/` shouldn't affect the remaining code. In particular this change doesn't affect the hashes of images created by `image.yaml`.
Updated web deps with `bun update`, changed `web/platform/README.md`, and commited the changes. Then `nix eval .#nativelink-worker-lre-cc.imageTag` was the same before and after.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1750)

Disable unnecessary workflows for web changes

---

web/platform/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1755)

Fix outdated homepage link

---

deploy/chromium-example/build_chromium_tests.sh
run_integration_tests.sh
tools/pre-commit-hooks.nix
tools/toolchain-buck2/toolchain-buck2.sh
tools/toolchain-drake/toolchain-drake.sh
tools/toolchain-nativelink/toolchain-nativelink.sh
tools/tsan.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1759)

Add shellcheck to lint shell scripts

---

web/platform/src/components/qwik/pages/company.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1760)

Change title on website

---

flake.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1762)

Fix remote build against lre-rs on NixOS

---

.bazelrc
Cargo.toml
nativelink-util/src/origin_event_middleware.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1766)

Fix clippy::if_not_else

---

.bazelrc
Cargo.toml
nativelink-util/src/proto_stream_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1765)

Fix clippy::option_option

---

.bazelrc
Cargo.toml
nativelink-util/src/connection_manager.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1768)

Fix clippy::from_iter_instead_of_collect

---

nativelink-store/src/redis_store.rs
nativelink-store/tests/redis_store_test.rs

The intent of this functionality was that downstream consumers should be able to easily see the hardcoded value for this index. It's unnecessary and unconventional to expose this through the metrics system. Instead we can use an info log message to achieve the same goal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1773)

Move redis fingerprint logic to logs

---

web/platform/src/components/qwik/sections/hero.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1776)

Update website hero

---

.bazelrc
Cargo.toml
nativelink-proto/gen_lib_rs_tool.py
nativelink-proto/genproto/lib.rs
nativelink-scheduler/src/awaited_action_db/awaited_action.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1777)

Fix clippy::similar_names

---

nativelink-service/src/ac_server.rs
nativelink-service/src/bytestream_server.rs
nativelink-service/src/cas_server.rs
nativelink-service/src/execution_server.rs
nativelink-service/src/worker_api_server.rs
nativelink-store/src/filesystem_store.rs
nativelink-util/src/evicting_map.rs
nativelink-worker/src/local_worker.rs
nativelink-worker/src/running_actions_manager.rs

This makes the log output for default info level more readable by moving various messages to the debug level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1778)

Reduce verbosity of the info trace level

---

.github/styles/config/vocabularies/TraceMachina/accept.txt
web/platform/src/content/posts/Adding_Support_for_Trust_Roots.mdx

This blog summarizes the new feature of trust root support.
I tested the PR. I have read the blog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1788)

Blog about trust root support

---

web/platform/src/content/posts/Adding_Support_for_Trust_Roots.mdx

Make the post more concise. Fix configuration example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1795)

Improve root cert blog post

---

web/platform/src/content/posts/Adding_Support_for_Trust_Roots.mdx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1811)

Modify blog image

---

Cargo.lock
nativelink-store/Cargo.toml
nativelink-store/src/compression_store.rs
nativelink-store/src/dedup_store.rs
nativelink-store/tests/compression_store_test.rs

Keep `legacy` config with `Fixint` encoding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1803)

Update bincode to 2.0.1

---

Cargo.lock
nativelink-store/Cargo.toml
nativelink-store/src/mongo_store.rs
nativelink-store/tests/mongo_store_test.rs

Upgrades the mongo library from 2.x to 3.x. ~~Needs https://github.com/TraceMachina/nativelink/pull/1853 merging first to test the code.~~
As a side-effect, fixes https://github.com/advisories/GHSA-h97m-ww89-6jmq
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1854)

Upgrades Mongo library to 3.x

---

deployment-examples/docker-compose/Dockerfile
src/bin/nativelink.rs

When you're adding new gRPC calls, it's sometimes hard to check you called the right thing v.s. maybe calling some other endpoint. This PR adds logging to the `fallback` function so we know what wasn't implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1861)

Log fallback calls to help with adding new gRPC bits

---

flake.nix

https://github.com/TraceMachina/nativelink/pull/1871 removed it, but turns out it's needed by CI on merge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1873)

Readd publish-ghcr as needed by deploy

---

README.md
nativelink-scheduler/src/cache_lookup_scheduler.rs
nativelink-scheduler/src/grpc_scheduler.rs
nativelink-scheduler/src/property_modifier_scheduler.rs
nativelink-scheduler/src/simple_scheduler.rs
nativelink-store/tests/mongo_store_test.rs
nativelink-util/src/platform_properties.rs
web/platform/src/components/qwik/components/book-download-form.tsx
web/platform/src/components/qwik/components/header.tsx
web/platform/src/components/qwik/pages/community.tsx
web/platform/src/components/qwik/sections/community.tsx
web/platform/src/content/docs/docs/deployment-examples/on-prem-overview.mdx
web/platform/src/content/docs/docs/faq/cost.mdx
web/platform/src/content/docs/docs/introduction/on-prem.mdx
web/platform/src/content/docs/docs/nativelink-cloud/api-key.mdx
web/platform/src/content/docs/docs/nativelink-cloud/nix.mdx
web/platform/starlight.conf.ts

Due to security concerns for some members of our community, we modified the Slack link to be a Google form.
```shell
rm -r dist && bun run build
bun preview
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1894)

Repository hygiene, Rust 1.89.0, enter to submit

---

Cargo.lock
README.md
native-cli/go.mod
nativelink-config/Cargo.toml
nativelink-error/Cargo.toml
nativelink-macro/Cargo.toml
nativelink-metric/Cargo.toml
nativelink-proto/Cargo.toml
nativelink-service/Cargo.toml
nativelink-store/Cargo.toml
nativelink-util/Cargo.toml
nativelink-worker/Cargo.toml

Updates version in README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1911)

Updating version in README and package manifests

---

web/platform/src/components/qwik/sections/hero.tsx

Basic update to our hero text to reflect our principal value prop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1942)

update hero with tagline

---

deployment-examples/rhel/Dockerfile.rhel8

Demoing build with RHEL8 (well, ubi8, [which is close enough](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image))
`docker build -f deployment-examples/rhel/Dockerfile.rhel8 -t nativelink-rhel8 . && docker run --rm nativelink-rhel8`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1933)

RHEL8 demo image
